### ISSUE TITLE
BCC are not working when using mail gem

### ISSUE THREAD

**Issue by wolfedale** [mikel/mail#1006]
Hi All,

I'm using content_filter (postfix) to send all e-mails from the postfix to my ruby script which is using mail gem to parse them, and send them back. I have configured everything as in the example here: http://www.postfix.org/FILTER_README.html and with this bash script it works ok, so I'm able to send e-mails using cc and bcc, but when I switch bash to ruby I can only send e-mails to To: and Cc:, all with BCC are somehow ignored.

This is my code in ruby:
```
class Encryptor
  def initialize
    @mail = Mail.new(STDIN.read)
  end

  def sendmail
    @mail.delivery_method :sendmail
    @mail.deliver
  end
end
```

So it looks like a bug?
I even created another method which is calling `%x{ /usr/sbin/sendmail -G -i .... }` and again, this is working ok.

**Comment by jeremy** [comment]
> all with BCC are somehow ignored.

BCC fields are used as SMTP recipients. They aren't included in the mail message itself.  #426.

Set `mail.bcc.include_in_headers = true` to override this and include the BCC field anyway, anticipating that a downstream MTA will strip the fields instead. #872.

**Comment by emcmanus** [comment]
> Set `mail.bcc.include_in_headers = true`

Results in NoMethodError (undefined method `include_in_headers=' for ["mikel@test.lindsaar.net", "ada@test.lindsaar.net"]:Mail::AddressContainer)

Use `mail[:bcc].include_in_headers = true` instead.

To reproduce:
```
mail = Mail.new
mail.bcc = 'Mikel Lindsaar <mikel@test.lindsaar.net>, ada@test.lindsaar.net'
mail.bcc.include_in_headers = true # Raises NoMethodError
```

I spent a few minutes looking into this but couldn't determine why `[]` works but `.bcc` (which I assume hits `method_missing`) doesn't.
