### ISSUE TITLE
decoding quoted-printable strings fails if lines broken in the middle of UTF-8 character

### ISSUE THREAD

**Issue by decklin** [mikel/mail#1007]
I'm attempting to decode a header that has been flowed into multiple lines, like so:

    Subject: =?utf-8?Q?This_is_a_demonstration_of_the_decoding_bug_=C2=AF\=5F(=E3=83?=
     =?utf-8?Q?=84)=5F/=C2=AF?=

Note that the quoted-printable data is wrapped in the middle of the three bytes that make up one UTF-8 character.

With the field all on one line, it works (for brevity i've removed the blah blah text):

    > Mail::Encodings.unquote_and_convert_to("Subject: =?utf-8?Q?=C2=AF\\=5F(=E3=83=84)=5F/=C2=AF?=", 'utf-8')
    => "Subject: ¯\\_(ツ)_/¯"

But when continued on a second line, the entire character is dropped without warning:

    >> Mail::Encodings.unquote_and_convert_to("Subject: =?utf-8?Q?=C2=AF\\=5F(=E3=83?=\n =?utf-8?Q?=84)=5F/=C2=AF?=", 'utf-8')
    => "Subject: ¯\\_()_/¯"

**Comment by jeremy** [comment]
Note that the line break is unrelated:
```ruby
>> Mail::Encodings.unquote_and_convert_to("Subject: =?utf-8?Q?=C2=AF\\=5F(=E3=83?==?utf-8?Q?=84)=5F/=C2=AF?=", 'utf-8')
=> "Subject: ¯\\_()_/¯"
```
The problem is that ツ is a three-byte character that's been split in the middle!

Each quoted-printable chunk is independent of the others, so we can't see the rest of the truncated character in the following chunk.

That means we decode the first two bytes of ツ and set it as utf-8 encoded. Then we cleanse the string: https://github.com/mikel/mail/blob/master/lib/mail/version_specific/ruby_1_9.rb#L121-L122 That drops the invalid truncated character.

This is invalid quoted-printable encoding, not much we can do to reliably fix it. We could attempt to detect and collapse adjacent chunks with the same encoding *and* charset before decoding, but that's inviting a world of errors and edge cases.

**Comment by jeremy** [comment]
Closer look:
```ruby
>> Mail::Encodings.value_decode("=?UTF-8?Q?=E3=83=84?=")
=> "ツ"
>> Mail::Encodings.value_decode("=?UTF-8?Q?=E3=83?=")
=> ""
```

In detail, decoding the valid ツ character:
```ruby
>> Mail::Encodings::QuotedPrintable.decode("=E3=83=84")
=> "\xE3\x83\x84"
>> Mail::Encodings::QuotedPrintable.decode("=E3=83=84").encoding
=> #<Encoding:ASCII-8BIT>
>> Mail::Encodings::QuotedPrintable.decode("=E3=83=84").force_encoding('utf-8')
=> "ツ"
>> Mail::Encodings::QuotedPrintable.decode("=E3=83=84").force_encoding('utf-8').valid_encoding?
=> true
```
versus decoding the invalid truncated character:
```
>> Mail::Encodings::QuotedPrintable.decode("=E3=83")
=> "\xE3\x83"
>> Mail::Encodings::QuotedPrintable.decode("=E3=83").encoding
=> #<Encoding:ASCII-8BIT>
>> Mail::Encodings::QuotedPrintable.decode("=E3=83").force_encoding('utf-8')
=> "\xE3\x83"
>> Mail::Encodings::QuotedPrintable.decode("=E3=83").force_encoding('utf-8').valid_encoding?
=> false
```

**Comment by decklin** [comment]
Okay, I should have said two quoted-printable chunks, not two lines. It is correct that the line break is not relevant.

I expect this to happen more often in email I receive in the future, even though the encoding is technically incorrect. Could you have something raise an exception if invalid-encoding bytes are discarded? I would find this preferable to silently dropping them.

**Comment by jeremy** [comment]
> expect this to happen more often

Curious—Why? Do you have any leads on the sender of these messages?

You can provide a custom charset encoder implementation that raises if it encounters invalid characters. Check out https://github.com/mikel/mail/blob/master/lib/mail/version_specific/ruby_1_9.rb#L4-L35

```ruby
class ValidatingCharsetEncoder
  def encode(string, charset)
    string.force_encoding(Mail::Ruby19.pick_encoding(charset)).tap do |encoded|
      raise "Invalid #{encoded.encoding} encoding: #{encoded.inspect}" unless encoded.valid_encoding?
    end
  end
end

Mail::Ruby19.charset_encoder = ValidatingCharsetEncoder.new
```

**Comment by decklin** [comment]
Thanks, looks like that should work for me.
