### ISSUE TITLE
Mail::Address constructor for raw values

### ISSUE THREAD

**Issue by ioquatix** [mikel/mail#1013]
It would make more sense for `Mail::Address` to be immutable by design and to have a constructor which allows to make sane To addresses from unquoted inputs.

As changing this would break the public API, I suggest the following changes:

Introduce a new class `Mail::Mailbox` which reflects the mailbox spec in RFC822. Make this class immutable by design. It represents the Mailbox address and display name and is constructed from those parameters and has a simple API to generate the "To" string which is quoted correctly.

Refactor the functionality of `Mail::Address.new(string)` to `Mail::Mailbox.parse(string)` which parses the data and calls `Mail::Mailbox.new(address, display_name)`.

This design improve the flexibility and maximise the functionality of the awesome work you did writing the RFC compliant parser (?).

**Comment by jeremy** [comment]
Generally agree. Good instincts. We're overly coupled with mail parsing in quite a few places, leading to this sort of awkwardness where we pass encoded strings to constructors instead of to a separate parsing method. I'll take a look at this case in particular to see what it'd take.
