### ISSUE TITLE
`Message#smtp_envelope_to=` and `Message[:smtp_envelope_to]=` are not equivalent. Is this desired behavior?

### ISSUE THREAD

**Issue by fiedl** [mikel/mail#1015]
An issue with a rails application where mail messages were sent to all of the `To` recipients rather than to the recipients specified in `smtp_envelope_to`, led me to investigate.

I've prepared a [test application](https://github.com/fiedl/smtp_envelope_send_test) with a rake task that basically does:

```ruby
recipients = ENV['RECIPIENTS'].split(",")
recipients.each do |recipient|
  mail = TestMailer.test_mail(to: recipients, smtp_envelope_to: recipient)
  mail.smtp_envelope_to = recipient if ENV['USE_SMTP_ENVELOPE_TO_SETTER']
  mail.deliver
end
```

For two recipients, test1@example.com and test2@example.com, I would have expected each recipient to receive one email. But in fact, unless `smtp_envelope_to` is set directly (`USE_SMTP_ENVELOPE_TO_SETTER=true` in the above code snippet), each recipient receives two emails.

Steps to reproduced as well as example results are documented in the [test app's README](https://github.com/fiedl/smtp_envelope_send_test/blob/master/README.md).

## How do *rails* and *mail* interact?

The `mail` method used in the `TestMailer` is defined [here, `ActionMailer::Base#mail` ](https://github.com/rails/rails/blob/4-2-stable/actionmailer/lib/action_mailer/base.rb#L800).

As one can see there, the `smtp_envelope_to` is passed to the `Mail::Message` object like this:

```ruby
def mail(headers = {}, &block)
  # ...
  m = @_message
  headers.except(...).each { |k, v| m[k] = v }
end
```

The `smtp_envelope_to` value is passed using `[]=`.

The [documentation of `Mail::Message`](https://github.com/mikel/mail/blob/master/lib/mail/message.rb) reads:

>        ===Making an email via assignment
>
>        You can assign values to a mail object via four approaches:
>
>        * Message#field_name=(value)
>        * Message#field_name(value)
>        * Message#['field_name']=(value)
>        * Message#[:field_name]=(value)
>
>        Examples:
>
>         mail = Mail.new
>         mail['from'] = 'mikel@test.lindsaar.net'
>         mail[:to]    = 'you@test.lindsaar.net'
>         mail.subject 'This is a test email'
>         mail.body    = 'This is a body'
>
>         mail.to_s #=> "From: mikel@test.lindsaar.net\r\nTo: you@...

[The `[]=` method](https://github.com/mikel/mail/blob/master/lib/mail/message.rb#L1306) just sets the header field, but does not pass it to `#smtp_envelope_to=`.

```ruby
# mikel/mail: lib/mail/message.rb

    def []=(name, value)
      if name.to_s == 'body'
        self.body = value
      elsif name.to_s =~ /content[-_]type/i
        header[name] = value
      elsif name.to_s == 'charset'
        self.charset = value
      else
        header[name] = value
      end
    end

    def smtp_envelope_to=( val )
      @smtp_envelope_to =
        case val
        when Array, NilClass
          val
        else
          [val]
        end
    end
```

Therefore, `mail[:smtp_envelope_to] = ...` and `mail.smtp_envelope_to = ...` are not equivalent, which explains the observed behavior.

## Is this a bug?

The parameter of `def mail(headers = {}, &block)` is called "`headers`". In fact, the `smtp-envelope-to` header is set correctly, as can be seen in the [Results](https://github.com/fiedl/smtp_envelope_send_test/blob/master/README.md#Results). Thus, the method does what can be expected from the definition.

Nevertheless, the smtp envelope itself is not set.

From my understanding, the header field `smtp-envelope-to`, which can be found in raw emails, is just a copy of the real smtp envelope. The mail servers do not look at the header fields but at the real smtp envelope.

Considering that the `mail` parameter in Rails is called "`headers`" and that the `Mail::Message#smtp_envelope_to=` and `Mail::Message#[:smtp_envelope_to]=` are not equivalent, I'd tend to try to resolve this in [mail](https://github.com/mikel/mail) rather than in [rails](https://github.com/rails/rails).

Is the current behavior, for some reason, the desired one, or could `Message#[]=` be modified like the following?

```ruby
# lib/mail/message.rb

    def []=(name, value)
      # ...
      elsif name.to_s == 'smtp_envelope_to'
        self.smtp_envelope_to = value
      else
        header[name] = value
      end
    end
```

**Comment by jeremy** [comment]
Hey @fiedl –

> unless smtp_envelope_to is set directly

The envelope recipient address is meant to be set directly. It's not a *message* header, after all!

Set `#smtp_envelope_to=` on the message just before delivering it.

**Comment by fiedl** [comment]
@jeremy : Thanks for the clarification.

Now, that I've spent some time looking into email headers and smtp envelopes, I agree that it makes sense from a technical standpoint.

But, for convenience, I still think I'd prefer the `mail` method to handle that magically somehow:

```ruby
# Does not work:
mail(smtp_envelope_to: recipient_user.email, to: "mailing-list@example.com", ...)
```


### Solution

For people googling this issue, later:

```ruby
recipients = %w(test1@example.com test2@example.com)
recipients.each do |recipient|
  mail = TestMailer.test_mail(to: recipients, smtp_envelope_to: recipient)
  mail.smtp_envelope_to = recipient   # <--- THIS LINE MAKES IT WORK
  mail.deliver_later
end
```

**Comment by jeremy** [comment]
> I still think I'd prefer the mail method to handle that

That'd be a good feature for Action Mailer's `#mail` !

**Comment by lunaru** [comment]
For people googling (or ChatGPTing) this same problem that @fiedl documented above (https://github.com/mikel/mail/issues/1015#issuecomment-234401743) 

I also find that encapsulating the `smtp_envelope_to` logic into the Mailer methods cleaner. So while the following does not work:

```ruby
# Does not work:
mail(smtp_envelope_to: recipient_user.email, to: "mailing-list@example.com", ...)
```

This does work:

```ruby
# Works by calling smtp_envelope_to on the Mail instance rather than the ActionMailer mail method:
mail(to: "mailing-list@example.com", ...).tap{|m| m.smtp_envelope_to = recipient_user.email}
```

Doing this would allow for the logic of setting the `smtp_envelope_to` out of the external for loop. This really ought to be a supported feature in ActionMailer and not really a problem of the Mail gem.
