### ISSUE TITLE
mail headers issue for multibyte (chinese) characters.

### ISSUE THREAD

**Issue by yogendra689** [mikel/mail#1016]
I have been using mandrill template to send mail.
when I assign some multibyte characters in mail header part, mail is sent but body part doesn't appear on mail received.  After much discussion with Mandrill support team, they said 

> It looks like there may be an issue with how line breaks are being inserted in the merge variable JSON. If line breaks occur in the middle of a multi-byte character, this can render the JSON invalid and Mandrill would be unable to parse that content as expected.

here is data (it has one chinese character):

```
"X-MC-MergeVars" @value="{\"user_name\":\" Yogendra\",\"data\":[{\"group_name\":\"RK\",\"group_url\":\"https://99t.abc.com/learn\",\"posts\":[],\"posts_empty\":true,\"show_more\":false},{\"group_name\":\"netwrking\",\"group_url\":\"https://99t.abc.com/learn\",\"posts\":[],\"posts_empty\":true,\"show_more\":false},{\"group_name\":\"Golf\",\"group_url\":\"https://99t.abc.com/courses/3525/learn\",\"posts\":[],\"posts_empty\":true,\"show_more\":false},{\"group_name\":\"sdaf\",\"group_url\":\"https://99t.abc.com/learn\",\"posts\":[],\"posts_empty\":true,\"show_more\":false},{\"group_name\":\"塔\",\"group_url\":\"https://99t.abc.com/learn\",\"posts\":[],\"posts_empty\":true,\"show_more\":false}],\"arrow\":\"http://localhost:4000/assets/arrows.png\",\"rf_banner\":\"http://localhost:4000/assets/mailer_header.png\",\"facebook\":\"http://localhost:4000/assets/facebook.png\",\"google_plus\":\"http://localhost:4000/assets/gmail.png\",\"linkedin\":\"http://localhost:4000/assets/linkedin.png\",\"twitter\":\"http://localhost:4000/assets/twitter.png\"}"
```

mail.header.encoded part:

```
X-MC-MergeVars: =?UTF-8?Q?{=22user=5Fname=22:=22yogendra=22,=22data=22:[{=22group=5Fname=22:=22RK=22,=22group=5Furl=22:=22https://99t.abc.com/courses/learn=22,=22posts=22:[],=22posts=5Fempty=22:true,=22show=5Fmore=22:false},{=22group=5Fname=22:=22netwrking=22,=22group=5Furl=22:=22https://99t.abc.com/courses/learn=22,=22posts=22:[],=22posts=5Fempty=22:true,=22show=5Fmore=22:false},{=22group=5Fname=22:=22Golf=22,=22group=5Furl=22:=22https://99t.abc.com/courses/learn=22,=22posts=22:[],=22posts=5Fempty=22:true,=22show=5Fmore=22:false},{=22group=5Fname=22:=22=E5=A1=94=E5=A1=94=E5=A1=94=22,=22group=5Furl=22:=22https://99t.abc.com/courses/learn=22,=22posts=22:[],=22posts=5Fempty=22:true,=22show=5Fmore=22:false}],=22arrow=22:=22http://localhost:3000/assets/arrows.png=22,=22rf=5Fbanner=22:=22http://localhost:3000/assets/mailer=5Fheader.png=22,=22facebook=22:=22http://localhost:3000/assets/facebook.png=22,=22google=5Fplus=22:=22http:/\n /localhost:3000/assets/gmail.png=22,=22linkedin=22:=22http://localhost:3000/assets/linkedin.png=22,=22twitter=22:=22http://localhost:3000/assets/twitter.png=22}?=
```

Mandrill team told to update SMTP library to fix issue.
I am not sure. Let me know if any possible way to fix this.

Let me know if any more details required.

**Comment by jeremy** [comment]
Looks like Mandrill may be hitting an issue with header folding.

Header folding is splitting a header value into multiple lines to ensure no line exceeds SMTP length limits, per RFC 2822. See the "\n  " in the encoded header.

Could you verify that you see the same issue with non-multibyte characters and long (> 998 char) header values on Mandrill?

I can verify that your message round-trips correctly:
```ruby
>> mergevars = "{\"user_name\":\" Yogendra\",\"data\":[{\"group_name\":\"RK\",\"group_url\":\"https://99t.abc.com/learn\",\"posts\":[],\"posts_empty\":true,\"show_more\":false},{\"group_name\":\"netwrking\",\"group_url\":\"https://99t.abc.com/learn\",\"posts\":[],\"posts_empty\":true,\"show_more\":false},{\"group_name\":\"Golf\",\"group_url\":\"https://99t.abc.com/courses/3525/learn\",\"posts\":[],\"posts_empty\":true,\"show_more\":false},{\"group_name\":\"sdaf\",\"group_url\":\"https://99t.abc.com/learn\",\"posts\":[],\"posts_empty\":true,\"show_more\":false},{\"group_name\":\"塔\",\"group_url\":\"https://99t.abc.com/learn\",\"posts\":[],\"posts_empty\":true,\"show_more\":false}],\"arrow\":\"http://localhost:4000/assets/arrows.png\",\"rf_banner\":\"http://localhost:4000/assets/mailer_header.png\",\"facebook\":\"http://localhost:4000/assets/facebook.png\",\"google_plus\":\"http://localhost:4000/assets/gmail.png\",\"linkedin\":\"http://localhost:4000/assets/linkedin.png\",\"twitter\":\"http://localhost:4000/assets/twitter.png\"}"
=> "{\"user_name\":\" Yogendra\",\"data\":[{\"group_name\":\"RK\",\"group_url\":\"https://99t.abc.com/learn\",\"posts\":[],\"posts_empty\":true,\"show_more\":false},{\"group_name\":\"netwrking\",\"group_url\":\"https://99t.abc.com/learn\",\"posts\":[],\"posts_empty\":true,\"show_more\":false},{\"group_name\":\"Golf\",\"group_url\":\"https://99t.abc.com/courses/3525/learn\",\"posts\":[],\"posts_empty\":true,\"show_more\":false},{\"group_name\":\"sdaf\",\"group_url\":\"https://99t.abc.com/learn\",\"posts\":[],\"posts_empty\":true,\"show_more\":false},{\"group_name\":\"塔\",\"group_url\":\"https://99t.abc.com/learn\",\"posts\":[],\"posts_empty\":true,\"show_more\":false}],\"arrow\":\"http://localhost:4000/assets/arrows.png\",\"rf_banner\":\"http://localhost:4000/assets/mailer_header.png\",\"facebook\":\"http://localhost:4000/assets/facebook.png\",\"google_plus\":\"http://localhost:4000/assets/gmail.png\",\"linkedin\":\"http://localhost:4000/assets/linkedin.png\",\"twitter\":\"http://localhost:4000/assets/twitter.png\"}"

>> mergevars == Mail.new(Mail.new('X-MC-MergeVars' => mergevars).encoded)['X-MC-MergeVars'].to_s
=> true
```

[Mandrill's docs make it pretty clear that they limit header values to 1000 chars](https://mandrill.zendesk.com/hc/en-us/articles/205582117-How-to-Use-SMTP-Headers-to-Customize-Your-Messages) and suggest using multiple headers if you exceed that length:
> Use a separate header for each recipient of an email being transmitted via SMTP. SMTP headers have a maximum length of 1000 characters, so if the header content for the global values or for an individual recipient exceeds 1000 characters, it can be broken into two (or more) headers. Just be sure to specify the recipient email address for every header for that recipient.
> 
> SMTP headers may contain only ASCII characters, so if you have non-ASCII characters like accents, they'll need to be escaped. Typically, you'll want to use a JSON library that automatically escapes any non-ASCII characters.

**Comment by yogendra689** [comment]
it works perfect for non-multibyte characters with > 998 chars.
I think issue with multibyte characters JSON encoding
How I can achieve `JSON library that automatically escapes any non-ASCII characters.` in rails?

let me know If I am wrong here.

**Comment by yogendra689** [comment]
is there any issue with Mail Encoding part?
I see default encoding used for mail headers is 7 bit.
https://github.com/mikel/mail/blob/8130b9c216bfb3149e10aef294696400da0b0954/lib/mail/message.rb#L122

Checked issue here:
http://stackoverflow.com/questions/11720270/how-to-change-the-mailer-content-transfer-encoding-settings-in-rails

Let me know If issue is on Mandrill end.
Also If multibyte character issue can be resolved , then let me know how I can do that.

**Comment by jeremy** [comment]
JSON is UTF-8, so it's a bit puzzling that Mandrill wants ASCII-safe JSON from you. This is something to pursue with their support. (It's unrelated to message transfer encoding.)

**Comment by yogendra689** [comment]
@jeremy thanks for your support.
I used mandrill-api gem `send-template` method , it worked for multibyte characters.
