### ISSUE TITLE
mime-types gem compatibility

### ISSUE THREAD

**Issue by sandstrom** [mikel/mail#1024]
When using this gem along with others using `mime-types` there are often conflicts.

This gem requires `(>= 1.16, < 3)`. Would be great if it worked with 3.0 too! ⛵ 

Perhaps the code can be adapter to handle both the old and newer version of `mime-types`?

**Comment by kjg** [comment]
It looks like support for mime-types 3.x was added in [commit d4ffe72](https://github.com/mikel/mail/commit/d4ffe72b0b2b0c6c8a49130bfe8e792d0542ac0e) and released in v2.6.4 of the mail gem

**Comment by sandstrom** [comment]
@kjg you are right, I'm blind! 🙈  Thanks for pointing it out!
