### ISSUE TITLE
If address header cannot be parsed, Mail.new leaves it as a string

### ISSUE THREAD

**Issue by cg2v** [mikel/mail#1031]
I am using mail to parse some incoming messages.
Some of the messages have incorrect To headers and mail's behaviour is strange; it does not split the address list up at all, the to field returns the raw string value of the header:

2.2.0 :027 > Mail.new("To: user1@example.org, user2@example.org").to
 => ["user1@example.org", "user2@example.org"] 
2.2.0 :028 > Mail.new("To: user1@example.org, user2@example.org.").to
 => "user1@example.org, user2@example.org." 

(the error is the trailing dot in example.org; Mail::AddressList.new() cannot parse this string)

**Comment by keysen** [comment]
+1 same thing for me

And it's very annoying because it occurs even when it's well formatted. Here I reproduce a case where it don't work because it's quoted printable with encoding...

For example: 
```ruby
[1] pry(main)> m = Mail.new("To: =?UTF-8?Q?Alain_DUBOUILLON_<contact@dubouillon.fr>,_TLM_<tlm@tlm.fr>,?=\n =?UTF-8?Q?_=222=C2=B0_BUREAU=22_<culture1@2e-bureau.com>,_491_<mensuel491@o?=\n =?UTF-8?Q?range.fr>,_=22ACTUART_=28Eliza_PLOIA=29=22_<elizaploia@yahoo.fr>?=")
[2] pry(main)> m.to
=> "Alain DUBOUILLON <contact@dubouillon.fr>, TLM <tlm@tlm.fr>, \"2° BUREAU\" <culture1@2e-bureau.com>, 491 <mensuel491@orange.fr>, \"ACTUART (Eliza PLOIA)\" <elizaploia@yahoo.fr>"

[3] pry(main)> m = Mail.new("To: Alain DUBOUILLON <contact@dubouillon.fr>, TLM <tlm@tlm.fr>, \"2° BUREAU\" <culture1@2e-bureau.com>, 491 <mensuel491@orange.fr>, \"ACTUART (Eliza PLOIA)\" <elizaploia@yahoo.fr>")
[4] pry(main)> m.to
=> ["contact@dubouillon.fr", "tlm@tlm.fr", "culture1@2e-bureau.com", "mensuel491@orange.fr", "elizaploia@yahoo.fr"]
```

**Comment by kjg** [comment]
So the question is, what SHOULD the behavior be when Mail cannot parse the header. Should it still return an array, but with just one item and that one item is the entire header contents?

**Comment by keysen** [comment]
It should still return an array of course, consistency is key...

But here in my provided example, you can see when I unescape the quoted printable encoding, the mail gem is perfectly able to parse all email address. So we don't care about parsing issue here, I think the mail gem HAVE TO support quoted printable addresses.

**Comment by kjg** [comment]
Supporting quoted printable addresses would be great! But it's also a seperate discussion from what to do when the address field is not parsable for whatever reason.

Still returning an array makes sense, but there should be some indicator that something went wrong. I know many objects have an error method to list any errors, I'm not sure if this is one of them, but that could maybe be used.

This would change the interface of the object, so it certainly could only be changed in a "breaking" release, but do you have time to make the change and the PR?

**Comment by jeremy** [comment]
#997
