### ISSUE TITLE
MIME::Types usage bug?

### ISSUE THREAD

**Issue by ioquatix** [mikel/mail#1039]
https://github.com/mikel/mail/blob/a217776355befa3d8191c4bd3c1fad54e0e27471/lib/mail/attachments_list.rb#L97-L100

Seems like this shouldn't be necessary any more?

**Comment by ioquatix** [comment]
We are also discussing whether memory usage can be improved. 70% of memory required by a default setup of mail is simply by the mime-types gem. https://github.com/mime-types/ruby-mime-types/issues/123

It seems a pity that this gem is well engineered to be memory efficient and yet it's not possible to use it without a huge overhead which for 99% of cases probably isn't even relevant.

**Comment by jeremy** [comment]
Seems like it, but we support a wide range of mime-types versions. Can we limit it to specific versions only?

**Comment by ioquatix** [comment]
Regarding the ruby code, have we checked that this is still a problem? What version of mime-types suffered this problem? I just saw this code when reviewing how `mail` uses `mime-types`. But I don't really know more than that.

**Comment by jeremy** [comment]
Switched to mini_mime #1059, #1060
