### ISSUE TITLE
Does this gem allow for specifying HTML Views in the 'body' for the Mail?

### ISSUE THREAD

**Issue by jourdan-jobox** [mikel/mail#1041]
Hello,

I'm looking for a solution that would allow me to easily send a styled email (rather than just a plain text email). 

This solution works great for sending text, but does this also allow me to write HTML/CSS inside an HTML view and then pass that HTML view over to the body parameter of the Mail object?

**Comment by jeremy** [comment]
Sure does: https://github.com/mikel/mail#writing-and-sending-a-multipartalternative-html-and-text-email
