### ISSUE TITLE
Output if mail send successul or with an error

### ISSUE THREAD

**Issue by lectricas** [mikel/mail#1044]
Hi. I'm using heroku and I set up Scheduler to run my script. The script send emails as soon as executed. So I adjust Scheduler to run every ten minutes. It worked. Then every day - it didn't  work. I tried everything and then search through output logs and they are the same.
So logs are telling me that script is executed every day, but I got no mails. 
I want to output the delivery report in order to find the culprit. 
Thanks.

**Comment by jeremy** [comment]
Assuming you're sending using an SMTP server, a message submission failure will raise an exception.

But once the message hits the mail server, the only delivery report you'll get is a bounce message that's returned to the From address.

(Of course, you may have some other bug in your script before sending emails. Ensure you're logging results and exceptions.)
