### ISSUE TITLE
Mail parses envelope From header incorrectly

### ISSUE THREAD

**Issue by Tensho** [mikel/mail#1049]
https://github.com/mikel/mail/blob/master/lib/mail/message.rb#L2035
I guess here we should have another regex in the mentioned line – `/\AFrom:\s/` – according to RFC822 and RFC2822. If I'm right, don't mind to create PR ^_^

Generally speaking `Mail::Message#to` and `Mail::Message#from` methods behave not quite as 
expected. I saw libs and custom code snippets, where people do tricky stuff with fields to get email address actual value and display name. For example:
```
from_field_name = mail[:from]
from_field_value = from_field_name.value # OR from_field_name.formatted
from_address = Mail::Address.new(from_field_value)
from_address_name = from_address.display_name
from_address_email = from_address.address
```
One of them [mandrill_dm](https://github.com/spovich/mandrill_dm). So if you have consistent opinion on the current `mail` behaviour regarding to this, please let me know.

**Comment by jeremy** [comment]
PR welcome! Address field handling is indeed idiosyncratic… 😊
