### ISSUE TITLE
AttachmentsList chooses obsolete MIME type for CSV attachments

### ISSUE THREAD

**Issue by ethanherbertson** [mikel/mail#1050]
https://github.com/mikel/mail/blob/a217776355befa3d8191c4bd3c1fad54e0e27471/lib/mail/attachments_list.rb#L102

As seen here, the `set_mime_type` function simply chooses the first MIME type returned by the MIME gem(s).

Unfortunately, in at least some circumstances, the first MIME type that is returned is one marked "obsolete" by those same gems. Such is the case with filenames ending in ".csv":

```
irb(main):003:0> MIME::Types.type_for('test.csv')
=> [#<MIME::Type: text/comma-separated-values>, #<MIME::Type: text/csv>]
irb(main):004:0> MIME::Types.type_for('test.csv').first.obsolete?
=> true
irb(main):005:0> MIME::Types.type_for('test.csv').last.obsolete? 
=> false
```

Suggest changing https://github.com/mikel/mail/blob/a217776355befa3d8191c4bd3c1fad54e0e27471/lib/mail/attachments_list.rb#L102 to

```ruby
types = MIME::Types.type_for(filename)
@mime_type = types.find {|type| !type.obsolete?} || type.first # use first non-obsolete type, if there is one
```

**Comment by jeremy** [comment]
#1046
