### ISSUE TITLE
Incompatible encoding errors out

### ISSUE THREAD

**Issue by bnvk** [mikel/mail#1070]
Upon trying to interact with an email that has the following encoding and characters:

```
Subject: Redactío Automático - For Privacy Sake=?UTF-8?Q?=F0=9F=94=92?=                  
From: "Contact Name" <contact_name@domain.com>                  
MIME-Version: 1.0                                                               
Content-type: text/html; charset=iso-8859-1;                                    
Content-Transfer-Encoding: 7bit 
```

And specifically accessing the `email.subect` value throws the following error:

```
[1] pry(#<Emailparser>)> test = email.subject
Encoding::CompatibilityError: incompatible character encodings: ASCII-8BIT and UTF-8
from /home/user/.rvm/gems/ruby-2.3.0/gems/mail-2.6.4/lib/mail/encodings.rb:138:in `join'
```

It seems to me the `mail` gem should not error like this.

**Comment by jeremy** [comment]
Looks like you're on an older version. On current master:
```ruby
>> Mail.new('Subject: Redactío Automático - For Privacy Sake=?UTF-8?Q?=F0=9F=94=92?=').subject
=> "Redactío Automático - For Privacy Sake🔒"
```

**Comment by bnvk** [comment]
@jeremy thanks for the response. Weird. Running `mail (2.7.0.edge)` it still crashes with same error. However, manually doing the command like you do seems to work :/

**Comment by bnvk** [comment]
The issue I was experiencing had to do with how `File.read('file.eml')` was storing / representing the data from the email. By running this `file_data.unpack('C*').pack('U*')` and then passing that to `Mail.new()` I no longer had an issue

**Comment by jeremy** [comment]
Check out `File.binread 'file.eml'` to read as binary 👍
