### ISSUE TITLE
Using in multi-threaded multi-user app?

### ISSUE THREAD

**Issue by wrzasa** [mikel/mail#1071]
How would you suggest using your mail library in multi-threaded application to retrieve and send mail using different mailboxes in different threads? The settings singleton is not thread safe. If multi-threaded use is currently not possible, how would you suggest solving this in an acceptable pull request?

**Comment by carsonreinke** [comment]
@wrzasa you could use the [retriever/delivery](https://github.com/mikel/mail/tree/master/lib/mail/network) classes directly instead of the static configuration.

So, roughly `Mail::POP3.new({...}).find`

**Comment by wrzasa** [comment]
Thank you for your answer! That leaves two questions. First, is the retriever/delivery part of the API subject to future changes? It's rather an internal API. And second, don't you consider changes to the main API that would make the gem thread-safe?

**Comment by jeremy** [comment]
1. These classes are part of this library's stable public API.
2. Default config is global, not thread-local, so thread safety is not a consideration here.

**Comment by wrzasa** [comment]
Thanks a lot for your answers!
