### ISSUE TITLE
Sinatra Local Variable Not a Valid SMTP To Address?

### ISSUE THREAD

**Issue by daBee** [mikel/mail#1072]
Switching from a normal variable to an instance variable (needed for output in erb files when using Sinatra), the SMTP To field becomes invalid:

		require 'mail'
		hostdomain = 'thisdomain.local'
		@s_email = "wopple405@gmail.com"

		smtp = {
			:address 								=> 'alfred.domain.com',
			:domain 								=> hostdomain
			}

		Mail.defaults { delivery_method :smtp, smtp }
		bodycontent = "There was a request for info on blah blah blah"
		mail = Mail.new do
			from 'admin@mydomain.com'
			to "#{ @s_email }"         # <== in here, this is the problem
			subject "#{ hostdomain } Info Request"
			body bodycontent
		end

		mail.deliver

Manually setting it gets the expected behaviour, which is an email properly sent.  Only local variable (`@var`) sets something off to indicate that field is not valid.

**Comment by jeremy** [comment]
This code isn't enough to reproduce the issue you're hitting, but it smells like you aren't actually setting `@s_email` so it's coming through as `nil` and you're ending up with an empty string as the To address.

Time to do some debugging (check the value of `@s_email` before using it) to nail this down.

**Comment by carsonreinke** [comment]
I think this is because `Mail.new` uses `instance_eval` which changes `self`.  If you did not use an instance variable and instead used `s_email` it will work.

```
2.3.3 :001 > require 'mail'
 => true 
2.3.3 :002 > @test = 'Hi'
 => "Hi" 
2.3.3 :003 > Mail.new{subject @test}
 => #<Mail::Message:15347000, Multipart: false, Headers: > 
2.3.3 :004 > test = 'Hi'
 => "Hi" 
2.3.3 :005 > Mail.new{subject test}
 => #<Mail::Message:12474560, Multipart: false, Headers: <Subject: Hi>> 
```
