### ISSUE TITLE
NPE caused by ParseException on generated content-id if hostname contains illegal characters

### ISSUE THREAD

**Issue by dounan** [mikel/mail#1073]
For example, if the hostname is "Bob's Macbook Pro", the auto generated content-id
(https://github.com/mikel/mail/blob/master/lib/mail/fields/content_id_field.rb#L59) will fail to parse due to the apostrophe. This results in a nil content_id value and a NPE when calling unbracket(content_id)
https://github.com/mikel/mail/blob/master/lib/mail/part.rb#L30

**Comment by sj26** [comment]
It seems if `::Socket.gethostname` returns non-ASCII characters and the message is transferred through an SMTP server which doesn't support the 8 bit extension then this may leak illegal characters into an encoded message over the wire.

**Comment by jeremy** [comment]
Good catch! We'll need sanitize our own header.

**Comment by jeremy** [comment]
Original issue: #555
