### ISSUE TITLE
subtle changes to DateField values

### ISSUE THREAD

**Issue by jeremybmerrill** [mikel/mail#1075]
The `mail` gem seems to subtly modify the value of a field in emails that I parse with it. Specifically, if the email's `Date:` header field has the `day` element without leading zeros, e.g. `Fri, 4 Dec 2015 08:50:48 -0500`, calling `Mail.read("email.eml")["Date"].value` will return `"Fri, 04 Dec 2015 08:50:48 -0500"`, with a leading zero.

By my reading of RFC2822, either leading-zeros or no leading-zeros in the `day` element are both acceptable. `day             =       ([FWS] 1*2DIGIT) / obs-day`

This subtle difference causes a problem only because I'm trying to write a [library to verify DKIM signatures](https://github.com/jeremybmerrill/dkimverify). 

The email I'm parsing is a real world example that was exported out of GMail. 

This minimal case demonstrates the problem:

````
> m = Mail.read("email.eml")
> m.header["Date"].instance_variable_get("@value")
=> "Fri, 4 Dec 2015 08:50:48 -0500"
> m.header["Date"].value
=> "Fri, 04 Dec 2015 08:50:48 -0500"
````

In terms of expected behavior, I think it's okay that `#value` returns a slightly different, standardized date. But there ought to be a way to get the exact value from the email, e.g. for use in validating DKIM signatures.

And big thanks to you all for maintaining this terrific gem. It makes my life so much easier in uncountably many ways. 😄

**Comment by jeremy** [comment]
Thanks for the kind words. I've been in the same boat. Round-tripping is really tough since we've designed for liberal parsing and strict generation rather than faithful in-place manipulation.

We parse and normalize the date header to account for the huge range of date formats we encounter. For one, it'd be great to leave the existing value as-is *if* it's already in the proper format.

You can get at the raw field value, but it's a super hack:
```ruby
>> Mail.new('Date: Fri, 4 Dec 2015 08:50:48 -0500')['Date'].instance_eval { unfold(split(@raw_value)[1]) }
=> "Fri, 4 Dec 2015 08:50:48 -0500"
```

+1 to have DateField expose something like `#unparsed_value`.

**Comment by jeremybmerrill** [comment]
@jeremy: Right, make sense about it being hard. Thanks for the explanation and for the tip on how to get the original value. I'll try incorporating that.

PS: jealous of the username... :grin:

**Comment by jeremybmerrill** [comment]
FYI, the fix you suggested worked. Thanks!

**Comment by jeremybmerrill** [comment]
Oh, thanks for closing, @jeremy . I ended up writing my own minimal RFC822 parser to maintain the fields exact values: https://github.com/jeremybmerrill/dkimverify/commit/e632bc3d1a5c1a62b29fb3860653ca7ff01b48e9

**Comment by jeremy** [comment]
Super cool @jeremybmerrill!
