### ISSUE TITLE
Wronge CEDT / CEST parsing

### ISSUE THREAD

**Issue by larcara** [mikel/mail#1078]
i'm exepriencing this issue.
https://gist.github.com/larcara/feb1bffb2d61a627b9f82c013527a8c8

```
require "mail"

mail = Mail.new do
  from     'me@test.lindsaar.net'
  to       'you@test.lindsaar.net'
  subject  'Here is the image you wanted'
  date     '06-Jul-2016 09:32:29 CEDT'
end

puts mail.date #2016-07-06T09:32:29+00:00 WRONG!
mail.date = Time.parse( mail["Date"].instance_variable_get("@value")) # HACK
puts mail.date

mail = Mail.new do
  from     'me@test.lindsaar.net'
  to       'you@test.lindsaar.net'
  subject  'Here is the image you wanted'
  date     '06-Jul-2016 09:32:29 CEST'
end

puts mail.date #2016-07-06T09:32:29+02:00  OK!

```

I tried to use ruby Time and DateTime:
Time.strptime("2016-07-23 05:32:52 CEDT",'%Y-%m-%d %H:%M:%S %z') #2016-07-23 05:32:52 +0200
DateTime.strptime("2016-07-23 05:32:52 CEDT",'%Y-%m-%d %H:%M:%S %z') #2016-07-23T05:32:52+00:00

**Comment by jeremy** [comment]
We use delegate to Ruby stdlib `DateTime.parse` to parse the Date header, so Mail will exhibit the same underlying features (and bugs) as Ruby.

Is there a Ruby bug with DateTime.parse for the time zones you're working with? If so, let's track it down. You can file at https://bugs.ruby-lang.org.
