### ISSUE TITLE
Fixnum deprecated in Ruby 2.4.0

### ISSUE THREAD

**Issue by Jacotb** [mikel/mail#1079]
I'm getting deprecation warnings such as the following:

`/cache/ruby/2.4.0/gems/mail-2.6.4/lib/mail/attachments_list.rb:33: warning: constant ::Fixnum is deprecated`

Fixnum and Bignum have been deprecated in favor of Integer:
http://blog.bigbinary.com/2016/11/18/ruby-2-4-unifies-fixnum-and-bignum-into-integer.html

**Comment by jeremy** [comment]
Thanks @Jacotb. This was addressed in #1053.
