### ISSUE TITLE
AddressListsParser failing with non-ASCII character in address

### ISSUE THREAD

**Issue by estraph** [mikel/mail#1088]
It appears that the parser fails when it encounters non-ASCII characters. Is this by design or a bug? I am having trouble digging through the Ragel code to better understand it.

I created a little PR with a failing spec here: https://github.com/mikel/mail/pull/1087

**Comment by estraph** [comment]
This looks very much like: https://github.com/mikel/mail/issues/39

**Comment by jeremy** [comment]
Confirmed, #39. Thanks for the failing specs!
