### ISSUE TITLE
Support using mail without `core_extensions`

### ISSUE THREAD

**Issue by andrew-stripe** [mikel/mail#1092]
We try to avoid monkeypatching the Ruby standard library to reduce the interface surface new engineers need to reason about. The mail gem's `core_extensions` are the largest contributor of standard library monkeypatches in our codebase today. We regularly run into bugs where code runs properly in a context where mail has been required and breaks in another context where the monkeypatches are not available. 

Would you be amenable to removing `core_extensions`? For backwards compatibility, I imagine the first step would be to remove any dependency on `core_extensions`, continue to load them by default and support a `require 'mail/base'` that doesn't load any patches.

**Comment by jeremy** [comment]
The extensions are for mail internals, so we needn't maintain back-compat in new mail releases.

Best approach here is to do separate PRs for each extension removal. As a starting point, check out https://github.com/mikel/mail/pull/937 for @darrencauthon's extensive `String#blank?` → `Mail::Utilities#blank?` migration.
