### ISSUE TITLE
Support for 1.9

### ISSUE THREAD

**Issue by monkeysuffrage** [mikel/mail#1104]
Mail is supposed to support 1.9 but doesn't seem to:

root@localhost:~/# ruby -v
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
root@localhost:~/# gem install mail
ERROR:  Error installing mail:
        mime-types-data requires Ruby version >= 2.0.

Can someone offer insight?

**Comment by jeremy** [comment]
Mail supports a wide range of mime-types gem versions. Newer versions (> 3.0) require Ruby 2.0+.

To work around this requirement, manually install an older mime-types gem first:
```bash
gem install mime-types --version "< 3"
```
