### ISSUE TITLE
2.7.0.rc1 in Rails apps results in spurious string parsing exceptions because Mail::Multibyte.mb_chars is not defined

### ISSUE THREAD

**Issue by dennisfaust** [mikel/mail#1108]
https://github.com/mikel/mail/blob/master/lib/mail.rb#L35 prevents Mail::Multibyte.mb_chars from being defined and Rails inflectors does not define it. 

Then when the parsing code: https://github.com/mikel/mail/blob/bf418912133d0aee5fdd9a5140fe5fb44cf4091f/lib/mail/field.rb#L243,
is called a "WARNING: Could not parse (and so ignoring) " exception message is displayed incorrectly.
 
A work around is to add 'require 'mail/multibyte' to an initializer.

**Comment by jeremy** [comment]
Thanks for the report, @dennisfaust. Checking it out!
