### ISSUE TITLE
Please release versions with security fix OSVDB-131677

### ISSUE THREAD

**Issue by david-a-wheeler** [mikel/mail#1116]
Currently there are only release candidates that fix OSVDB-131677 by including [PR 1097](https://github.com/mikel/mail/pull/1097).  Can I talk you into making a full release soonish?

Thanks!

**Comment by vassilevsky** [comment]
Yes, it would have been awesome to patch Rails 3 🙏

**Comment by jeremy** [comment]
Yep! [2.5.5](https://github.com/mikel/mail/releases/tag/2.5.5) and [2.6.6](https://github.com/mikel/mail/releases/tag/2.6.6) were released in June 2017. 😊
