### ISSUE TITLE
Performance downgrade introduced with Mail::Utilities.to_crlf/to_lf change

### ISSUE THREAD

**Issue by dalibor** [mikel/mail#1118]
I'm seeing a big performance downgrade with this [PR](https://github.com/mikel/mail/pull/956) and would propose reverting it. The original benchmark shows very positive results because the test string consist only of new line characters that is never the case with real email content.

Here's my benchmark:

```ruby
require 'benchmark'

CRLF = "\r\n"
CRLF_REGEX = /\n|\r\n|\r/

line = 'a' * 100
string = "#{line} \n\r\n\n" * 100
number_of_samples = 10000

Benchmark.bm do |x|
  x.report('regexp:') do
    number_of_samples.times do
      string.gsub(CRLF_REGEX, CRLF)
    end
  end

  x.report('encode:') do
    number_of_samples.times do
      string.encode(:universal_newline => true).encode!(:crlf_newline => true)
    end
  end
end
```

Results:

```
regexp:  1.190000   0.030000   1.220000 (  1.231583)
encode:  1.510000   0.070000   1.580000 (  1.578965)
```

Now, it becomes more interesting when lines are longer, with `'a' * 200`

```
regexp:  1.690000   0.020000   1.710000 (  1.711932)
encode:  2.990000   0.020000   3.010000 (  3.033241)
```

Or even `'a' * 1000` (that usually could be more with inline html):

```
regexp:  5.690000   0.100000   5.790000 (  5.864328)
encode: 14.250000   0.270000  14.520000 ( 14.601885)
```

I see performance downgrade of ~ 100% in my tests when benchmarking base64 encoded attachments where I originally noticed this issue.

The boundary where `encode` performs better vs `regex` would be when new line characters sequence appears after every 55 character which I would say is not frequent especially where this matters that is attachments and lots of content.

**Comment by jeremy** [comment]
Ouch. Good catch and diagnosis.

On latest master we're no longer doing newline conversion on body parts. Do you think it makes this performance issue moot?

**Comment by dalibor** [comment]
The performance downgrade I'm seeing in my benchmarks with that change is:

```
30 attachments of ~ 10MB each:   4.757560 sec -> 9.101804 sec
10000 html parts of ~ 40KB each: 8.909483 sec -> 10.272647 sec
```

It's the big emails (attachments) where this change is slowing things for 100%.

Also, my test suite time with this "improvement" is 1.62 sec and without it 1.48 sec. :) You can check out locally by disabling that change.

**Comment by jeremy** [comment]
Ah, because we're still calling `to_crlf` in 8bit and base64 encodings…

**Comment by jeremy** [comment]
Please do open a revert PR to address this 👍
