### ISSUE TITLE
Validate domain and local-part having consecutive dots.

### ISSUE THREAD

**Issue by rahulbajaj0509** [mikel/mail#1124]
According to rfc2822 : 
Local part must not contain consecutive dots : ex: "abc..@gmail.com"
Also, the Domain part must not have consecutive dots : ex: "abc@gmail...com"

In both cases an exception must be raised saying " Invalid e-mail address "

**Comment by jeremy** [comment]
Thanks for the report. This is intentional.

https://github.com/mikel/mail/pull/797#issuecomment-299770471
> Previously reported in #279 as a deviation from RFC, patched in #286, and reverted in #397. These deviations are not-uncommonly seen in the wild, so we purposefully support parsing them.
