### ISSUE TITLE
eml attachments encoding regression

### ISSUE THREAD

**Issue by ahorek** [mikel/mail#1127]
I found out that my change wasn't enough https://github.com/mikel/mail/pull/1106

Mail::Body.encoded calls get_best_encoding twice (correct transfer encoding should already be set for example in identify_and_set_transfer_encoding)
in my opinion, the encoding availability check shouldn't be called here.

the problem is in my case get_best_encoding('7bit') without available encodings always chooses base64 which is not compatible with eml file, but it encodes the content.

So as a result I have an eml attachment which claims to have
Content-Transfer-Encoding: 7bit (which is correct)
but in reality the content is encoded in base64 (which is forbidden), that makes the attachment unreadable

**Comment by jeremy** [comment]
Thanks @ahorek. Moving to #1128.
