### ISSUE TITLE
LF emails can't be parsed anymore

### ISSUE THREAD

**Issue by ahorek** [mikel/mail#1129]
removed in #1113 / master branch

I have many eml files in my specs with just LF separator, that passes on 2.6.6 stable
```
HEADER
LFLF
BODY
```

when normalization was removed, header separator doesn't work with it anymore, the parser thinks that the whole email is a header which is wrong.
```
HEADER_SEPARATOR = /#{CRLF}#{CRLF}/
```

according to the RFC, header separator should be always 2x CRLF
https://www.ietf.org/rfc/rfc2822.txt

so my question is, should eml files with just LF separators be parsable or not?
It doesn't comply with RFC, but standard mail clients like Outlook or Thunderbird can open and work with these files just fine. It also used to work with mail 2.6.6.

**Comment by jeremy** [comment]
Yep, looking at supporting this before release. Correctness first!

Some related discussion on the commit: https://github.com/mikel/mail/commit/21222e1b48f08f6f848d26643d6b6fb1d873d18c#commitcomment-22366140

**Comment by ahorek** [comment]
great, thanks!
