### ISSUE TITLE
undefined method `attachments' when using within Rails as serialized column.

### ISSUE THREAD

**Issue by Flauschbaellchen** [mikel/mail#1134]
Currently I have trouble accessing the attachments variable of `Mail::Message` within Rails.
I'm not sure if this is a bug within the mail-gem, rails or if I myself did something wrong.

I have a class `Letter` which has `serialize :mail` to store the `Mail::Message` object:
```ruby
2.4.0 :001 > l = Letter.new
 => #<Letter id: nil, mail: nil, created_at: nil, updated_at: nil> 
2.4.0 :003 > l.mail = Mail.new
 => #<Mail::Message:15757780, Multipart: false, Headers: > 
2.4.0 :004 > l.mail
 => #<Mail::Message:15651480, Multipart: false, Headers: >
```
Accessing the (empty) Mail::Message's attachments throws the following error:
```ruby
2.4.0 :007 > l.mail.attachments
NoMethodError: undefined method `attachments' for []:Array
        from /usr/local/rvm/gems/ruby-2.4.0/bundler/gems/mail-f0dbe4853856/lib/mail/message.rb:1658:in `attachments'
        from (irb):7
```
However, accessing it without going over the Letter an empty array is returned:
```ruby
2.4.0 :008 > Mail.new.attachments
 => [] 
```

Any help pointing me into the right direction would be greatly appreciated.
As `l.mail` successfully returning a `Mail:Message` object I don't think that the `serialize :mail` is the problem, is it?

Used versions:
* mail (2.7.0.rc1 f0dbe48)
* ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]
* rails (5.0.4)

**Comment by jeremy** [comment]
Active Record `serialize` uses YAML dump/load by default. That's not round-tripping correctly. To troubleshoot, check `YAML.load(YAML.dump(message)).attachments`.

More broadly, I'd recommend storing the encoded message (`message.encoded`) rather than serializing the Message object. You can implement this as a custom coder for `serialize`, or handle it yourself in callbacks.

**Comment by Flauschbaellchen** [comment]
Thanks for reminding me to use `message.encoded`.. I really do not know why I did not use it. Thanks!

**Comment by Flauschbaellchen** [comment]
In case someone is interesed in the implementation:
```ruby
class Letter < ApplicationRecord
  serialize :mail, MailSerializer
end
```

```ruby
class MailSerializer
  def self.dump(value)
    value.encoded if value
  end

  def self.load(value)
    Mail.new(value) if value
  end
end
```

**Comment by jeremy** [comment]
Thanks for sharing, @Flauschbaellchen 😎
