### ISSUE TITLE
Unable to install from local

### ISSUE THREAD

**Issue by devvpm** [mikel/mail#1137]
I am installing all the gem using the following command

gem install --local <<path>>/gems/mail-2.6.4.gem
It worked for all the gems except for this mail-2.6.4.gem.  In this case, I am getting below response:

> **ERROR: Could not find a valid gem 'mime-types' (< 4, >= 1.16) in any repository**

How to resolve this?

**Comment by jeremy** [comment]
When you install gems locally, you need to have the dependencies available locally too. Install the dependencies, then `gem install --local` will work.
