### ISSUE TITLE
Retrieve mail request fails 

### ISSUE THREAD

**Issue by solasdev** [mikel/mail#1139]
I can successfully retrieve mail using the gem, however after the first request I get back nil. If I wait some time I can query all the mails back otherwise it fails.

example:
```ruby
mail=Mail.defaults do
  retriever_method :pop3, :address    => "pop.gmail.com",
                   :port       => 995,
                   :user_name  => 'xxxx',
                   :password   => 'xxxx',
                   :enable_ssl => true
end

mail.all.count
= 15

then further requests:
mail.all.count
= 0

mail.all[0]
 = nil
```
Any ideas?

**Comment by jeremy** [comment]
Retrieving POP messages removes them from the Inbox, so when you try to retrieve them again, they're already gone.

Try using IMAP instead.
