### ISSUE TITLE
Allowing for a different TO in email header and SMTP

### ISSUE THREAD

**Issue by julien51** [mikel/mail#1142]
There are cases where one wants to have a different `to` header and where the email is actually delivered. One example that comes to mind is redirects. 
When an email provider allows for multiple email "accounts" in their inboxes, it is pretty convenient to receive emails inside that provider with a different email address than the main one of the account while maintaining the `to` header so that for example, responding does not reveal the actual identifier inside the service provider.
Gmail actually supports that.

Right now the `smtp_connection.rb` pulls the destination from the message which is a good default but it would also be convevient to pass a different value.

**Comment by julien51** [comment]
Found what I was looking for... sorry for the early message! Closing now.

**Comment by jeremy** [comment]
For other folks arriving here via search: `mail.smtp_envelope_to = …` is what you're looking for!
