### ISSUE TITLE
Forward method?

### ISSUE THREAD

**Issue by julien51** [mikel/mail#1154]
Is there a simple forward method one can use to forward emails parsed from a `*.eml` file?
If not, what are the recommended changes to make? to the Mail::Message object? I guess the `to` header, but maybe also some other things? :like the signatures?

**Comment by jeremy** [comment]
There isn't a baked-in method because there's no standard way to do email forwards, especially with text/html multipart.

You'd want to create a new Mail object, set its To address to the person you're forwarding to, set its Subject to something like `Fwd: #{source.subject}`, and set its body to the quoted `source.text_part.decoded` with a "Forwarded …" message at the top.

**Comment by julien51** [comment]
Thanks. I am afraid though that this would miss a lot of things like attachements for example :( I'll to create something from scratch then!

**Comment by jeremy** [comment]
👍

**Comment by btrd** [comment]
I just did that and it seems to work fine (even for attachments)

```ruby
transfer_message = message.dup
transfer_message[:to] = new_to
transfer_message[:subject] = "Fwd: #{transfer_message[:subject]}"
transfer_message.deliver!
```

**Comment by reiz** [comment]
@btrd This only works if the original email was send from your own domain. If the email is from another domain, the DKIM checks will fail. In that case you have to build the mail object from scratch. 

> I just did that and it seems to work fine (even for attachments)
> 
> transfer_message = message.dup
> transfer_message[:to] = new_to
> transfer_message[:subject] = "Fwd: #{transfer_message[:subject]}"
> transfer_message.deliver!

**Comment by der-flo** [comment]
You do not have to start from scratch. Our solution based on ActionMailer:

```ruby
class OurMailerBuildingAForwardedMail < ActionMailer::Base
  def build_forwarded_mail
    mimic_mail_method
    set_addresses
    delete_headers_if_present
  end

  private

  def set_addresses
    message[:reply_to] = message.from
    message[:from] = 'sender@company.example'
    message[:to] = 'target@forwarding.example'
  end

  def delete_headers_if_present
    # This header can be an empty string in the original message, for example.
    # Amazon SES does not like this.
    # See: https://stackoverflow.com/q/43157065
    delete_header_if_present :return_path

    # We delete any existing DKIM signature because it is certainly not valid for the
    # forwarded message.
    # This would probably not be necessary because SES overwrites the header anyway,
    # but this way we have explicitly thought about it once,
    # which headers must be overwritten or deleted and which can be retained.
    delete_header_if_present :dkim_signature

    # If the original mail has also been sent via CC,
    # do not send it to this target again.
    # BCC is not relevant, as this field is not output with received mails.
    delete_header_if_present :cc

    # Do not duplicate the original message ID. Instead, remove it and let Rails generate a new message ID.
    # Add the old message ID to the References header.
    # Existing References entries should be retained.
    if message.references.present?
      message.references += " #{message.message_id}"
    else
      message.references = message.message_id
    end
    delete_header_if_present :message_id
  end

  def delete_header_if_present(header)
    # You may only delete a header with 'nil' if it already exists.
    # Otherwise it will be created and filled with an empty string.
    # See: https://github.com/mikel/mail/blob/2-7-stable/lib/mail/header.rb#L182
    message[header] = nil if message[header]
  end

  def mimic_mail_method
    # The mail gem maintainer recommends, in our case, simply modifying an
    # an existing mail object:
    # https://github.com/mikel/mail/issues/884
    self.message = params[:original_mail]

    # From `ActionMailer::Base#mail`
    @_mail_was_called = true
    wrap_delivery_behavior!
  end
end
```

Feel free to use and customize it, hints regarding possible problems to our solution are very welcome!
