### ISSUE TITLE
Update state of Mail::Message if a delivery is attempted

### ISSUE THREAD

**Issue by ledhed2222** [mikel/mail#1156]
Didn't see an issue about this, so pardon if this has already been requested.

I'd like to know if delivery has been attempted at all for a `Mail::Message`. I'm envisioning a boolean instance variable on `Mail::Message` that is set to `true` at the end of `Mail::Message#deliver`. There would then be a method on `Mail::Message` like this:
```ruby
def delivered?
  @delivered == true
end
```

The use case for this functionality would be to allow library users to prevent sending a message object twice. IE:

```ruby
def paranoid_sender(mail)
  if mail.delivered?
    raise DontSpamUsPlease
  end
  mail.deliver
end
```

Yes, I can hook into this part of the code via an observer, but without monkey patching I would then be forced to keep a very memory-expensive hash of Mail object_ids to message delivery status.

If this sounds good happy to make a PR.

**Comment by jeremy** [comment]
Could you share more about the context in which you've seen multiple delivery crop up as a usage risk?

**Comment by ledhed2222** [comment]
Sure - I haven't encountered this in production, but I was working on a refactor of a notification system that would have been able to do some fancy tricks by passing `Mail::Message`s around and then calling `deliver` in a centralized location. But given the common usage pattern in Rails of invoking `deliver` directly on the mailer, it would have created this risk.

So - abbreviated:

```ruby
class Notification
  def execute
    mailer.deliver
  end
end

# imagine having many of these subclasses
class MyNotification < Notification 
  def mailer
    MyMailer.my_message #risk that developer calls `deliver` here, resulting in two messages
  end
end

# invoked as
MyNotification.execute
```

**Comment by jeremy** [comment]
Agreed. This usage isn't covered well by using an observer. You can accomplish it with a delivery handler, though!

Assuming you're working with Action Mailer (given `MyMailer.my_message` invocation), use an Action Mailer hook to [intercept delivery](http://edgeguides.rubyonrails.org/action_mailer_basics.html#intercepting-emails) and add "do not redeliver" handler:
```ruby
module DisallowRedeliveryInterceptor
  class DeliverOnceHandler
    def deliver_mail(mail)
      raise 'Message was already delivered' if @delivered
      @delivered = true
      yield
    end
  end

  def self.delivering_email(message)
    message.delivery_handler = DeliverOnceHandler.new
  end
end

ActionMailer::Base.register_interceptor DisallowRedeliveryInterceptor
```

Can use a Mail interceptor outside of Action Mailer, too.

**Comment by ledhed2222** [comment]
@jeremy sweet! That works like a charm thank you for clarifying. Looks like we will have to store that instance variable on the mail via
```ruby
mail.instance_variable_set(:@delivered, true)
```
which does seem a bit hack-tastic but I think it's OK.

Will leave issue open just in case I'm missing something about the instance variable there. Otherwise looks ready to close to me.

**Comment by jeremy** [comment]
No instance variable needed with the delivery handler, since the handler itself is tracking that state 😁

**Comment by ledhed2222** [comment]
Ahh I see what my issue was. Obviously with this:

```ruby
def self.delivering_email(message)
  message.delivery_handler = DeliverOnceHandler.new
end
```

We'll have a new instance of DeliverOnceHandler, blowing away our instance variables. Should be the following:

```ruby
def self.delivering_email(message)
  # actionmailer assigns a delivery handler itself
  if !message.delivery_handler.is_a?(DeliverOnceHandler)
    message.delivery_handler = DeliverOnceHandler.new
  end
end
```

Closing
