### ISSUE TITLE
Parsing email with non-ASCII headers but without \r produces unexpected results

### ISSUE THREAD

**Issue by rubys** [mikel/mail#1167]
Test case.  Expected results: all three tests pass.  Actual results: the second test fails.

    require 'test/unit'
    require 'mail'

    class I18N_Mail_test < Test::Unit::TestCase
      TEST1 = %{
        To:   dest@example.org
        From: source@example.org
        Subject: ASCII
   
        body
      }.strip.gsub(/^\s+/, '')

      TEST2 = TEST1.sub("ASCII", "Iñtërnâtiônàlizætiøn")

      TEST3 = TEST2.gsub("\n", "\r\n")

      def test_pass1
        assert_equal ["dest@example.org"], Mail.new(TEST1).to
      end

      def test_fail2
        assert_equal ["dest@example.org"], Mail.new(TEST2).to
      end

      def test_pass3
        assert_equal ["dest@example.org"], Mail.new(TEST3).to
      end
    end

This worked with versions of mail < 2.7.0

**Comment by jeremy** [comment]
Right. We no longer auto-convert the convenient `\n` to the required `\r\n` when it may be unsafe. Our safety heuristic is pretty weak: just that the message is ASCII-only. We may expand this to allow UTF-8 with valid encoding on Ruby 1.9+, but using CRLF for test fixtures is a good route to pursue in any case.

https://github.com/mikel/mail/issues/1166#issuecomment-341535151

**Comment by jeremy** [comment]
Fixed by #1168
