### ISSUE TITLE
Regression in parsing multipart mails with Mail.new

### ISSUE THREAD

**Issue by obfuscoder** [mikel/mail#1177]
Up to version 2.6.6 it was possible to create a mail object of a multipart raw mail with this:

```
data = File.binread(''/path/to/raw_mail.txt')
mail = Mail.new(data)
```

The object correctly contained the headers, parts and bodies of the mail.

Doing this with version 2.7.0, however, yields an object which does not provide access to any of the headers, parts or bodies of the mail.

The mail content I was testing with can be found here:

https://github.com/obfuscoder/flee_rails/blob/master/spec/requests/registration_mail.txt

I have to stick to version 2.6.6 for now.

**Comment by jeremy** [comment]
See #1167 and #1168
