### ISSUE TITLE
2.7.0 breaks parsing of mail messages without content type and broken encoding in message body

### ISSUE THREAD

**Issue by sriedel** [mikel/mail#1182]
I'm not sure if this change was intentional or not.

With 2.7.0 if we have the a message in a file with the contents

    From: "The Sender" <sender@example.com>                                         
    To: The Receiver <receiver@example.com>                                         
    Subject: The mail subject
    
    This is a message without content type and broken encoding: fÃ¼r                                                        

the parsed message ends up completely inside the emails from field:

    email = Mail::Message.new( File.read( "message.txt" ) )
    email.to # => nil
    email.from # => "\"The Sender\" <sender@example.com>\nTo: The Receiver <receiver@example.com>\nSubject: The mail subject\n\nThis is a message without content type and broken encoding: fÃ¼r"

Remove the broken encoding from the message:

    From: "The Sender" <sender@example.com>                                         
    To: The Receiver <receiver@example.com>                                         
    Subject: The mail subject
    
    This is a message without content type  

and things work as expected:

    email = Mail::Message.new( File.read( "message.txt" ) )
    email.to # => ["receiver@example.com"]l
    email.from # => ["sender@example.com"]

In 2.6.6 the parsing worked even with the broken encoding.

**Comment by jeremy** [comment]
See #1167 and #1168
