### ISSUE TITLE
Project's docs not available at rubydoc.info

### ISSUE THREAD

**Issue by nitsas** [mikel/mail#1187]
Hello, I'm trying to access the project's documentation at http://www.rubydoc.info/github/mikel/mail and I get an error:

> Oops,
> We Couldn't Find That GitHub Project
> 
> We haven't generated any docs for mikel/mail. You can add the project yourself by entering the GitHub project information below. You can also see a list of available projects here.

**Comment by jeremy** [comment]
This is an external site that fetches and generates docs for gems and GitHub repositories. It's open source (https://github.com/docmeta/rubydoc.info), which may help track down why adding this repo isn't working! Looks like http://www.rubydoc.info/gems/mail isn't generating either. http://www.rubydoc.info/gems/mail/2.6.6 is working.

**Comment by fwolfst** [comment]
As of today the link in the original post works. Issue can be closed.

**Comment by nitsas** [comment]
Thanks!
