### ISSUE TITLE
Mail parse error

### ISSUE THREAD

**Issue by iggant** [mikel/mail#1193]
Hi I have this email file: 

> Received: by vps26241 (Postfix)
	id B0DS6207232; Wed, 10 Jan 2018 02:50:19 -0500 (EST)
MIME-Version: 1.0
Content-Transfer-Encoding: 8bit
Content-Type: text/plain; charset=UTF-8
Date: Wed, 10 Jan 2018 02:50:13 -0500
From: Some User <jon@example.com>
To: Some Client <jan@example.com>
Subject: Re: Test
Message-ID: <4e10e841b79d60778a3a27cc2888d115@vps26241>
User-Agent: Roundcube Webmail/1.2.3
>
> física

` irb(main):018:0> f=Mail.read('email_sample.msg') `
> => #<Mail::Message:70276927430100, Multipart: false, Headers: <Received: by vps26241 (Postfix)
	id B0DS6207232; Wed, 10 Jan 2018 02:50:19 -0500 (EST)
MIME-Version: 1.0
Content-Transfer-Encoding: 8bit
Content-Type: text/plain; charset=UTF-8
Date: Wed, 10 Jan 2018 02:50:13 -0500
From: Some User <jon@example.com>
To: Some Client <jan@example.com>
Subject: Re: Test
Message-ID: <4e10e841b79d60778a3a27cc2888d115@vps26241>
User-Agent: Roundcube Webmail/1.2.3
> física>>

reason is because string from file: 

> => "Received: by vps26241 (Postfix)\n\tid B0DS6207232; Wed, 10 Jan 2018 02:50:19 -0500 (EST)\nMIME-Version: 1.0\nContent-Transfer-Encoding: 8bit\nContent-Type: text/plain; charset=UTF-8\nDate: Wed, 10 Jan 2018 02:50:13 -0500\nFrom: Some User <jon@example.com>\nTo: Some Client <jan@example.com>\nSubject: Re: Test\nMessage-ID: <4e10e841b79d60778a3a27cc2888d115@vps26241>\nUser-Agent: Roundcube Webmail/1.2.3\n\nfísica\n"

and 

`::Mail::Utilities.to_crlf`

doesn't insert \r\n to the string

**Comment by jeremy** [comment]
See #1167 and #1168
