### ISSUE TITLE
Error occurs if there is a space in the OS/X machine name.

### ISSUE THREAD

**Issue by mileslane** [mikel/mail#1197]
A bunch of our rspec tests were failing with this error:

     # NoMethodError:
     #   undefined method `match' for nil:NilClass
     #   .rvm/gems/ruby-2.4.2/gems/mail-2.7.0/lib/mail/utilities.rb:134:in `unbracket'

If you read the last few comments in the following page, you'll see that the problem is identified as a bug in the mail gem where it is failing to handle spaces in the host name:

https://stackoverflow.com/questions/21580578/rails-mailer-error-with-inline-attachment
http://osxdaily.com/2012/10/24/set-the-hostname-computer-name-and-bonjour-name-separately-in-os-x/

**Comment by jeremy** [comment]
See #555
