### ISSUE TITLE
html_part not always present?

### ISSUE THREAD

**Issue by JerryGreen** [mikel/mail#1203]
![image](https://user-images.githubusercontent.com/13215662/36378070-36e200b0-159b-11e8-95ee-b9b0d3ba5e3a.png)

I understand if there's no `text_part` but `html_part`... I'm not sure, am I missing something? For me it looks like there should always be `html_part`!

P.S. I probably need to attach this email message here so it'll be possible to reproduce?

**Comment by jeremy** [comment]
text/html parts are for multipart/alternative messages. You have a non-multipart message here whose body is raw HTML.

For example, a raw HTML body:
```ruby
>> message = Mail.new(body: '<html>here</html>')
=> #<Mail::Message:70320720271180, Multipart: false, Headers: >
>> message.html_part
=> nil
```

And a multipart/alternative body:
```ruby
>> message = Mail.new
=> #<Mail::Message:70320720084440, Multipart: false, Headers: >
>> message.html_part = 'foo'
=> "foo"
>> message.html_part
=> #<Mail::Part:70320720065560, Multipart: false, Headers: <Content-Type: text/html>>
```
