### ISSUE TITLE
can't receive an iso-8859-1 email with \n linefeeds

### ISSUE THREAD

**Issue by Phlip** [mikel/mail#1204]
A test in Redmine, version '3.4.2.stable', called "test_add_issue_with_localized_attributes", fails when it tries to import an email with \n linefeeds, and a couple é characters. We're using mail-2.7.0.

The symptom is Message.new(raw_string) returns a Message object with no header fields filled out.

The root problem is the method Mail::Utilities.to_crlf. It first checks if your string has non-US-ASCII characters in it, then it refuses to replace \n with \r\n. Then the system that creates header Field objects splits the header by "\r\n", which fails, leaving the header blank.

I fixed the test by making .to_crlf not check if my string has any 8-bit characters.

Is there a better fix? I thought multiple-byte encodings always defined non-ASCII characters using bytes with their 8th bit set, so they would never accidentally use an escaped byte that resembled a \r or \n. Hence brute-force searches for \n would never mistake a byte in a multi-byte glyph for a \n. How does 'mail' read any emails with \n for linefeeds?

**Comment by krisdigital** [comment]
@Phlip I think I might have the same issue https://github.com/mikel/mail/issues/1205? Only it is an utf-8 email...

**Comment by jeremy** [comment]
Due to LF (`\n`) line separators rather than CRLF (`\r\n`). See #1167 and #1168.
