### ISSUE TITLE
Parse attachment filenames when missing RFC-required quotes

### ISSUE THREAD

**Issue by pdg137** [mikel/mail#1213]
We have been receiving emails from the order-processing system of a large company that are missing required quotes around the attachment `filename` and `name` values, which happen to be encoded in Base64.  Other email software can apparently handle these invalid emails, but this gem can't find the filename.  Here is a minimal example demonstrating the problem:

```
Mail::Part.new('Content-Type: text/plain; name="=?utf-8?B?dGVzdC50eHQ=?="').filename
=> "test.txt"
Mail::Part.new('Content-Type: text/plain; name==?utf-8?B?dGVzdC50eHQ=?=').filename
=> ""
```

With `Content-Disposition`, the returned filename is `nil` instead of the empty string:

```
Mail::Part.new('Content-Disposition: attachment; filename="=?utf-8?B?dGVzdC50eHQ=?="').filename
=> "test.txt"
Mail::Part.new('Content-Disposition: attachment; filename==?utf-8?B?dGVzdC50eHQ=?=').filename
=> nil
```

I thought that this was related to Issue #1153, but the gem still fails to get the filename on 1.7.0 and on the master branch.

It would be great if the Mail gem could be tolerant of these improperly-formatted attachments!  I might look into fixing this but thought I should post here first in case anyone is working on it or can point me in the right direction.

**Comment by jeremy** [comment]
Yikes. That one's new to me!

Take a look at https://github.com/mikel/mail/blob/master/lib/mail/parsers/rfc2045_content_type.rl#L10-L13 for Content-Type parameter parsing and experiment with broadening the allowed `token` set.

**Comment by pdg137** [comment]
Something changed in version 2.7.1 so that we get a filename, but it's hopelessly corrupted:

```ruby
irb(main):006:0> Mail::Part.new('Content-Type: text/plain; name="=?utf-8?B?dGVzdC50eHQ=?="').filename
=> "test.txt"
irb(main):007:0> Mail::Part.new('Content-Type: text/plain; name==?utf-8?B?dGVzdC50eHQ=?=').filename
=> "v\v�u�tz\u001A"
irb(main):008:0> 
```

This is worse than the previous behavior since it's not obvious how to tell from the `Mail::Part` data that there is a problem.

**Comment by pdg137** [comment]
Seems to be working correctly in 2.8.1.  Thanks!
