### ISSUE TITLE
Email body encoding is not right and decoded email body without MIME info

### ISSUE THREAD

**Issue by hoksilato** [mikel/mail#1224]
I'm running this problem when using [ruby-gmail](https://github.com/dcparker/ruby-gmail) to fetch emails from Gmail. And this 

The mail content is in Vietnamese so that I need to decode it to UTF-8 to extract some data from the message, such as: amount of the money, description of transaction...

I don't understand why the encoding of email body is `7bit`? Should it be `quoted-printable`? Response of `email.body`

```
#<Mail::Body:0x007f99809731c0 @boundary="----=_Part_2910_551645065.1523594097131", @preamble="", @epilogue="", @charset="US-ASCII", @part_sort_order=["text/plain", "text/enriched", "text/html", "multipart/alternative"], @parts=[#<Mail::Part:70148632056400, Multipart: false, Headers: <Content-Type: text/html; charset=utf-8>, <Content-Transfer-Encoding: quoted-printable>>], @raw_source="------=_Part_2910_551645065.1523594097131\r\nContent-Type: text/html; charset=utf-8\r\nContent-Transfer-Encoding: quoted-printable\r\n\r\nS=E1=BB=91 d=C6=B0 t=C3=A0i kho=E1=BA=A3n v=E1=BB=ABa t=C4=83ng 123 v=\r\n=C3=A0o 11/04/20xx 11:34 VN\r\nS=E1=BB=91 d=C6=B0 hi=E1=BB=87n t=E1=BA=A1i: 123 VND\r\nM=C3=B4 t=E1=BA=A3: Description here\r\nS=E1=BB=91 t=C3=A0i kho=E1=BA=A3n: xxxxx4924\r\n------=_Part_2910_551645065.1523594097131--\r\n", @ascii_only=true, @encoding="7bit">
```

Are there anyways to get the decoded email body without MIME info? Here is the response of `email.body.decoded`.

```
------=_Part_2910_551645065.1523594097131\nContent-Type: text/html; charset=utf-8\nContent-Transfer-Encoding: quoted-printable\n\nS=E1=BB=91 d=C6=B0 t=C3=A0i kho=E1=BA=A3n v=E1=BB=ABa t=C4=83ng 123 v=\n=C3=A0o 11/04/20xx 11:34 VN\nS=E1=BB=91 d=C6=B0 hi=E1=BB=87n t=E1=BA=A1i: 123 VND\nM=C3=B4 t=E1=BA=A3: Description\nS=E1=BB=91 t=C3=A0i kho=E1=BA=A3n: xxxxx4924\n------=_Part_2910_551645065.1523594097131--\n
```

I have a workaround solution for those but still want to know there are any better solutions.

Thanks for your help.

**Comment by jeremy** [comment]
> I don't understand why the encoding of email body is 7bit? Should it be quoted-printable? Response of email.body

The email message uses 7bit content encoding because the multipart body uses quoted-printable content encoding for its parts, resulting in a 7bit-safe message.

> Are there anyways to get the decoded email body without MIME info?

This is due to the source email using LF (\n) line separators rather than CRLF (\r\n). See #1167 and #1168.
