### ISSUE TITLE
Difference between `deliver` and `deliver!` response

### ISSUE THREAD

**Issue by dv** [mikel/mail#1225]
Using `deliver!` with `return_response: true` returns the SMTP response, however using `deliver` ignores `return_response` and always returns `self`.

Is there a reason for this difference? Returning the SMTP response is handy for example when sending through Amazon SES, which adjusts and returns the MessageID in the SMTP response.

If I make a PR to make this consistent, would it be accepted?

**Comment by jeremy** [comment]
No reason that I could discern from https://github.com/mikel/mail/commit/15c3fa7ce152d4c1da7fb0caa391ebf847d6fcd7. Consistent behavior is welcome 👍
