### ISSUE TITLE
Mail fails to parse UTF-8 email with umlaut in body

### ISSUE THREAD

**Issue by Quintus** [mikel/mail#1230]
Mail can't parse this email:

~~~~~~~~~~
To: redacted@redacted.invalid
From: otherperson@redacted.invalid
Message-ID: <xxxxx1xx@example.com>
Date: Tue, 17 Apr 2018 03:32:45 +0200
MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8; format=flowed
Content-Transfer-Encoding: 8bit

Text mit Umlaut: Bär
~~~~~~~~~~

The following code demonstrates the issue (save this as an utf-8-encoded file):

~~~~~~~~~ ruby
# coding: utf-8
require "mail"

str=<<EOF
To: redacted@redacted.invalid
From: otherperson@redacted.invalid
Message-ID: <xxxxx1xx@example.com>
Date: Tue, 17 Apr 2018 03:32:45 +0200
MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8; format=flowed
Content-Transfer-Encoding: 8bit

Text mit Umlaut: Bär
EOF

m = Mail.read_from_string(str)
puts m.from
puts m.body.decoded
~~~~~~~~~

This outputs nothing (i.e., puts is given `nil` twice). It should print the from email address and the mail body. What I find especially surprising is that it even fails to parse the headers due to the sole umlaut in the message body. Try removing the `ä` from the message body and everything works fine.

This is mail 2.7.0 with Ruby `ruby 2.3.7p456 (2018-03-28 revision 63024) [x86_64-linux]` on Gentoo.

**Comment by jeremy** [comment]
This is due to the source email using LF (\n) line separators rather than CRLF (\r\n). See #1167 and #1168.

**Comment by Quintus** [comment]
I can confirm that using `Mail::Utilities.binary_unsafe_to_crlf` fixes this problem. #1168 says that the use of this method may corrupt attachments. I'm using `mail` to process my personal batch of e-mails as stored by my mutt+offlineimap setup, i.e., I do have quite a lot of mails with attachments. Appearently offlineimap stores e-mails only using LF and not CRLF then.

Since mutt has never complained about this, shouldn't `mail` be able to parse LF-only emails just as well, and not just as a hack to ease writing of fixtures as explained in #1168?
