### ISSUE TITLE
Deprecate ruby < 2.0?

### ISSUE THREAD

**Issue by ahorek** [mikel/mail#1234]
Is there anyone that still using ruby 1.8 or 1.9? If we deprecate these versions we could remove a lot code, use refinements etc.

https://github.com/mikel/mail/pull/1231, https://github.com/mikel/mail/pull/1232

**Comment by jeremy** [comment]
Yep, they are, but numbers are dwindling. We will drop support for old Rubies in a future major release, but we've been pretty conservative about allowing other libraries and apps to take the lead on upgrading at their speed.
