### ISSUE TITLE
Mail::Message#to is sometimes an array, sometimes a string

### ISSUE THREAD

**Issue by tragiclifestories** [mikel/mail#1243]
It seems that usually, when one sets the address on a message (as happens under the hood in ActionMailer), it gets wrapped into an array, which makes sense given that emails can have *n* recipients.

However, for some values, this does not happen. The case I have come across is when we have a (clearly pathological) value that has only a period before the @.

```ruby
mailer.message.to "me@example.com"
#=> "me@example.com"
mailer.message.to
#=> ["me@example.com"]
mailer.message.to "me.@example.com"
#=> "me.@example.com"
mailer.message.to
#=> ["me.@example.com"]
mailer.message.to ".me@example.com"
#=> ".me@example.com"
mailer.message.to
#=> [".me@example.com"]
mailer.message.to ".@example.com"
#=> ".@example.com"
mailer.message.to
#=> ".@example.com"
```

I have no idea if this is intended behaviour or not, but it has caused a little confusion for us.

**Comment by jeremy** [comment]
Indeed. Invalid addresses that can't be parsed are returned as an unknown field which shows up as a string, not an array. This is a design issue, so it will need a breaking change (and a major version bump) to address it.
