### ISSUE TITLE
Wrong Content-Type parameters parsing

### ISSUE THREAD

**Issue by diko4096** [mikel/mail#1253]
Suddenly I found the strange behaviour of Mail gem: on some e-mails it didn't
found attachments, but other e-mail clients displays all attachments correctly. 
When I dig into the raw messages, what caused the issue, I found the Content-Type
header, folded on two lines:

```
Content-Type: multipart/mixed; charset = 'UTF-8';
 boundary="----------=_1533675981-30424-318"

```
But when I print message.header, the Content-Type looks like:

```
Content-Type: multipart/mixed;
 boundary="\\\"----------";
 charset='utf-8'
```

So boundary does not match and Mail can't find any attachment in the message.

When I print the original value of Content-Type header, it seems ok - unfolded
and looks pretty good:

`Content-Type: multipart/mixed; charset = 'UTF-8'; boundary="----------=_1533675981-30424-318"`

When I tried to override the header by re-assign unfolded value, I have the same thing:

```
message.header['Content-Type'] = message.header['Content-Type'].value.gsub("\n",'')
@logger.debug "header Content-Type AFTER: #{message.header['Content-Type']}"

> header Content-Type AFTER: multipart/mixed; boundary="\\\"----------"; charset='utf-8'

```
In all that story the most strange thing is when I taken original message and unfold Content-Type 
manually with nano editor, it processed by Mail as expected, and all attachments were detected.

I'm using:
    mail (2.7.0)
    mini_mime (1.0.0)

Messages with the issues generated by X-Mailer: MIME-tools 5.509 (Entity 5.509)

**Comment by jeremy** [comment]
Thanks for the report! Does look like an unfolding bug. 👍

**Comment by diko4096** [comment]
Maybe you have an estimation here?

**Comment by diko4096** [comment]
We found the master branch has no error described above, seems like it fixed here: https://github.com/mikel/mail/commit/6a019d5372c3792f32ab8423fd65f477e783856a but unfortunately it's not in recent 2.7.0

**Comment by diko4096** [comment]
Closing
