### ISSUE TITLE
Mail::Body#multipart does not always return a boolean

### ISSUE THREAD

**Issue by Onumis** [mikel/mail#1254]
`Mail::Body#multipart?`
(https://www.rubydoc.info/gems/mail/2.6.6/Mail/Body#multipart%3F-instance_method)
will return nil for non-multipart messages.

But `Mail::Message#multipart?` 
(https://www.rubydoc.info/gems/mail/2.6.6/Mail/Message#multipart%3F-instance_method)
will always return a boolean.

This should probably have a _more similar behaviour_.

**Comment by jeremy** [comment]
"[Truthiness](https://gist.github.com/jfarmer/2647362#conclusion)" is the behavioral standard for predicate methods. 😊
