### ISSUE TITLE
Is Mail gem faster then ActionMailer?

### ISSUE THREAD

**Issue by shcyiza** [mikel/mail#1260]
Hello,
I got a project where the main value is based on the ability to process a lot of mail. I find ActionMailer kinda slow for my purpose.

So my question is, are the deliver methods of you gem faster to generate the email then ActionMailer?

**Comment by jeremy** [comment]
Probably not. Action Mailer uses Mail to deliver, so if Action Mailer is kinda slow, then Mail probably is too 😊
