### ISSUE TITLE
Scrub invalid bytes instead of throwing an exception?

### ISSUE THREAD

**Issue by grin** [mikel/mail#1262]
I'm thinking how to properly deal with emails containing invalid characters in Subject (or From) fields, like:

```rb
mail = Mail.new do
  from    "\"Ericka Eames \" <erica@example.com>"
  to      'you@test.lindsaar.net'
  subject "Lorem ipsum\x85 "
end
```

this will throw `ArgumentError: invalid byte sequence in UTF-8`. Is it possible to make Mail not bomb in this case but just scrub the incorrect bytes?

**Comment by grin** [comment]
@jeremy When parsing emails in the wild.

**Comment by grin** [comment]
From what I can see Mail does already some scrubbing but only for values that are encoded in the Q or B format, like here: https://github.com/mikel/mail/blob/master/lib/mail/version_specific/ruby_1_9.rb#L131
and that doesn't seem to apply to plain ascii subjects.

Wouldn't it make sense to employ scrubbing somewhere around this case statement: https://github.com/mikel/mail/blob/6bc16b4bce4fe280b19523c939b14a30e32a8ba4/lib/mail/encodings.rb#L132
maybe in the `else` block?

**Comment by jeremy** [comment]
Supporting invalid binary headers is a rabbit hole that probably shouldn't be pursued for its own sake. Let's work from an example message. Could you share a raw message you received that failed to parse?
