### ISSUE TITLE
Release plan for 2.7.1 stable?

### ISSUE THREAD

**Issue by ahorek** [mikel/mail#1274]
Hi @jeremy, 2.7.0 version still has some bugs, but many of them were already fixed.

Do you have any release blockers?
I know about many users that are stuck with previous versions or have to use monkey-patching. Also using a release candidate isn't an option.

What do you think? Let me know if you need help with something. Thanks.

**Comment by jeremy** [comment]
Thanks @ahorek. I think I'll release and handle the remaining concerns in 2.7.2.

**Comment by ylecuyer** [comment]
@jeremy is the release planned for this week ?

**Comment by jeremy** [comment]
@ylecuyer I don't have a specific plan, but I'd like to.

**Comment by ylecuyer** [comment]
Thanks @jeremy :)
