### ISSUE TITLE
Cannot parse LF mail when body contains a non ascii character

### ISSUE THREAD

**Issue by DamienRobert** [mikel/mail#1276]
When a mail is separated by LF new lines rather than CRLF new lines, Mail will convert them to CRLF by using `Mail::Utilities.to_crlf(value)` in `raw_source=`. 

But `to_crlf` only convert the end lines when `string.ascii_only?` is true, so this won't happen for utf-8 bodies.

I receive a *lot* of emails in this case, where Mail cannot parse them anymore (older versions used to work, I did not bisect to see when the failure to parse these mails was introduced).

I don't see an easy solution, I understand why that check `safe_for_line_ending_conversion?` is to not mess up with binary encodings. I think the only solution would be to replace HEADER_SEPARATOR to allow LF (and maybe CR) lines.

**Comment by jeremy** [comment]
Thanks for investigating @DamienRobert. See #1167 and #1168.

Could you try the 2.7.1.rc1 gem?

**Comment by DamienRobert** [comment]
Ah yes, sorry I missed these since they were closed. I'll test the 2.7.1.rc1 gem, but looking at the patches from #1168 I am pretty sure it will solve my problem, thanks.
