### ISSUE TITLE
Release 2.8.0

### ISSUE THREAD

**Issue by Tensho** [mikel/mail#1282]
@jeremy Could you release `2.8.0` to rubygems.org please? 🙇

**Comment by jeremy** [comment]
2.8.0 release is not yet ready. 2.7.1 is next! 🙏

**Comment by Tensho** [comment]
Sorry, when `2.7.1`  will be released? What it a general time period for release?

**Comment by jeremy** [comment]
Today. 2.7.1 is [released](https://rubygems.org/gems/mail/versions/2.7.1).
