### ISSUE TITLE
Release 2.7.1 refers to removed PhraseListElement

### ISSUE THREAD

**Issue by dariota** [mikel/mail#1286]
Under the 2.7.1 tag,
https://github.com/mikel/mail/blob/2.7.1/lib/mail/parsers/phrase_lists_parser.rb#L872

On current master,
https://github.com/mikel/mail/blob/52c0e9c5eaf26154d3100312f21b1bc77d728261/lib/mail/parsers/phrase_lists_parser.rb#L875

It looks like the same commit is the latest on both versions (based on a quick comparison of author/committer/time), but with different parents - was history rewritten?

**Comment by eugeneius** [comment]
2.7.1 was released from the 2-7-stable branch, not master. The duplicate commits you noticed aren't evidence that history was rewritten, but rather that a change was backported to a stable branch.

The reference to `PhraseListsElement` was introduced in https://github.com/mikel/mail/pull/1030, which made it into 2.7, and later corrected as part of https://github.com/mikel/mail/pull/1120, which didn't. That commit is far too large to backport, so I think opening a pull request targeting the 2-7-stable branch that just fixes the constant name is the right thing to do.

**Comment by jeremy** [comment]
Great catch! Do you have a test case we could use to demonstrate the failure, and prevent future regression?

**Comment by dariota** [comment]
Thanks for the explanation @eugeneius!

@jeremy I can try get you the specific test case on Monday (or, at least, a minimal reproduction). I'll see if I can come up with something now, but I don't have a development environment of any sort for this on my personal machines.

**Comment by dariota** [comment]
cc @jeremy in case you haven't seen the above!

**Comment by SummerStorm** [comment]
This issue can now be closed now that PR #1326 has been merged.

**Comment by dariota** [comment]
I'll test this tomorrow and close the issue once I've confirmed it works. Thanks @SummerStorm !

**Comment by dariota** [comment]
Sorry for the delay reporting back - we've confirmed we're no longer hitting this issue.

**Comment by jacquescrocker** [comment]
It possible to do a new release for this? I'm using 2.7.1 from rubygems and it still has this error

**Comment by ramses7083** [comment]
@jacquescrocker what is the release version that includes this fix? I'm not able to get `2.7.2` from rubygems
