### ISSUE TITLE
Make a release with has_rdoc fix

### ISSUE THREAD

**Issue by alyssais** [mikel/mail#1289]
The fix in https://github.com/mikel/mail/pull/1247 should be released in advance of RubyGems' 2018-12-01 deadline. It's been in master for several months, but wasn't merged into the 2-7-stable branch, so didn't make it into 2.7.1.

**Comment by jeremy** [comment]
Backported to 2-7-stable in 904fc3299163771ca47d5cc5c2f540f6f828c2d6!
