### ISSUE TITLE
2.7.1 Unable to parse email with "Invalid byte sequence in UTF-8"

### ISSUE THREAD

**Issue by daveroberts** [mikel/mail#1294]
I can't include the mail file, but this is the error and partial backtrace:

    ArgumentError: invalid byte sequence in UTF-8

```
ruby-2.4.1/gems/mail-2.7.1/lib/mail/message.rb:2032:in `match'
ruby-2.4.1/gems/mail-2.7.1/lib/mail/message.rb:2032:in `match'
ruby-2.4.1/gems/mail-2.7.1/lib/mail/message.rb:2032:in `set_envelope_header'
ruby-2.4.1/gems/mail-2.7.1/lib/mail/message.rb:2132:in `init_with_string'
ruby-2.4.1/gems/mail-2.7.1/lib/mail/message.rb:137:in `initialize'
ruby-2.4.1/gems/mail-2.7.1/lib/mail/mail.rb:51:in `new'
ruby-2.4.1/gems/mail-2.7.1/lib/mail/mail.rb:51:in `new'
```

This Error wasn't thrown in 2.7.0

**Comment by wjessop** [comment]
I can trigger this with a really simple test case (Ruby 2.6.0, mail 2.7.1):

```
irb(main):001:0> Mail.new("\255")
Traceback (most recent call last):
       11: from /Users/will/.rbenv/versions/2.6.0/bin/irb:23:in `<main>'
       10: from /Users/will/.rbenv/versions/2.6.0/bin/irb:23:in `load'
        9: from /Users/will/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        8: from (irb):1
        7: from /Users/will/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/mail-2.7.1/lib/mail/mail.rb:51:in `new'
        6: from /Users/will/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/mail-2.7.1/lib/mail/mail.rb:51:in `new'
        5: from /Users/will/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/mail-2.7.1/lib/mail/message.rb:137:in `initialize'
        4: from /Users/will/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/mail-2.7.1/lib/mail/message.rb:2132:in `init_with_string'
        3: from /Users/will/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/mail-2.7.1/lib/mail/message.rb:2032:in `set_envelope_header'
        2: from /Users/will/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/mail-2.7.1/lib/mail/message.rb:2032:in `match'
        1: from /Users/will/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/mail-2.7.1/lib/mail/message.rb:2032:in `match'
ArgumentError (invalid byte sequence in UTF-8)
```

Obviously this is a simplistic example, but we're hitting this with real mail and unfortunately we're realistically not going to be able to fix up mail at the source so will have to work around it locally.

**Comment by jeremy** [comment]
Hey @wjessop 😊

We can likely account for malformed UTF-8 in this match. Workaround is to not use UTF-8 encoding for incoming emails which may not be UTF-8. Set them to ASCII-8BIT / binary encoding:
```ruby
>>  Mail.new("\255".b)
=> #<Mail::Message:2199392600, Multipart: false, Headers: >
```

**Comment by wjessop** [comment]
Hello @jeremy! So, I guess what's happening here is that we have an email string that somehow has been flagged as utf-8, but is actually 7bit and invalid as utf-8. mail/message.rb line 2032 tries to match but this is dependent on the encoding and we get the exception.

In this case I think your .b workaround works fine, thanks! Could a workaround to getting 7bit strings mistakenly passed as invalid utf-8 strings be to treat the email as 7bit in set_envelope_header, as headers should (hah) be in 7bit?

**Comment by daveroberts** [comment]
So is it safe to open all email as ASCII-8BIT?  When an email comes in, I don't always know the encoding

**Comment by wjessop** [comment]
> is it safe to open all email as ASCII-8BIT

Given this is the Internet you might get some ASCII-8BIT, a goat, and half a bag of leftover tortilla chips as part of the email data, so "safe" might be pushing it, but from my reading of the relevant RFCs, in particular [https://www.w3.org/Protocols/rfc1341/5_Content-Transfer-Encoding.html](https://www.w3.org/Protocols/rfc1341/5_Content-Transfer-Encoding.html), it seems that this should be expected.

There does seems to be an exception though, from that page:

> If an entity is of type "multipart" or "message", the Content-Transfer-Encoding is not permitted to have any value other than a bit width (e.g., "7bit", "8bit", etc.) or "binary". 

This seems to allow for more encodings than those stated though, so you might want to do some reading of your own :)
