### ISSUE TITLE
Question: Parsing encapsulated messages with a pkcs7-mime content type

### ISSUE THREAD

**Issue by weilandia** [mikel/mail#1310]
Hello,

I'm parsing inbound emails and ran into two problems where I was wondering if there was a better built-in solution (or just hoping for a sanity check on what I came up with as I'm new to all these email internals):

1. Parsing email parts with `message/rfc822` content types
2. Parsing email parts with `application/pkcs7-mime` content types

I ended up solving handling these situations with the following:

```ruby
class EmailParser
  attr_reader :mail

  delegate :text_part, :html_part, to: :mail

  def initialize(mail)
	# mail is an instance of Mail
    mail = pre_process(mail)
    @mail = mail
  end

  def body
    @body ||= begin
      (text_part || html_part || mail).decoded
    end
  end

  def subparts
    @subparts = mail.parts.map do |part|
      next if part.content_type != "message/rfc822"

      EmailParser.new(Mail.new(part.body))
    end.compact
  end

  private

    def pre_process(mail)
      mail = EmailParser::Pkcs7MimeParser.parse(mail) if EmailParser::Pkcs7MimeParser.should_parse?(mail.mime_type)

      mail
    end
end

class EmailParser::Pkcs7MimeParser
  PKCS7_MIME_TYPE = "application/pkcs7-mime"

  def self.should_parse?(mime_type)
    mime_type == PKCS7_MIME_TYPE
  end

  def self.parse(mail)
    unpacked = OpenSSL::PKCS7.new(Base64.decode64(mail.body.raw_source))
    unpacked.verify([], OpenSSL::X509::Store.new, nil, OpenSSL::PKCS7::NOVERIFY)

    Mail.new(unpacked.data)
  end
end
```

I noticed [PartsList#recursive_each](https://github.com/mikel/mail/blob/6bc16b4bce4fe280b19523c939b14a30e32a8ba4/lib/mail/parts_list.rb#L63) does something similar to `#subparts` above, but also that it is not released yet.

I struggled to find good resources for dealing with these two situations and it would be awesome to learn if there is a better way.

Thanks so much for the awesome library!!

**Comment by jeremy** [comment]
If you need the body parts to be transparently decrypted, that looks like a reasonable route!

Another possibility, depending on your application's needs, is to decrypt when the contents of the MIME part are decoded. Check out `Mail::Message#decoded` for how the body parts are retrieved for text, attachments, etc. For example:
```ruby
module PKCS7Decryption
  # Decrypt, verify signature, etc for PKCS7 parts.
  # For non-encrypted/signed parts, there's nothing to do, so return the part as-is.
  def decrypted
    if pkcs7?
      Mail::Part.new(decrypt_pkcs7_body)
    else
      self
    end
  end

  def pkcs7?
    sub_type == 'pkcs7-mime'
  end

  def decrypt_pkcs7_body
    signature = OpenSSL::PKCS7.new(decode_body)
    signature.verify …
    signature.data
  end
end

Mail::Message.include PKCS7Decryption

Mail.new(message_with_pkcs7_parts).parts.each do |part|
  puts part.decrypted.inspect
end
```

**Comment by weilandia** [comment]
Thank you! @jeremy
