### ISSUE TITLE
Multibyte strings in headers breaks header parser

### ISSUE THREAD

**Issue by vlazzle** [mikel/mail#132]
It looks like certain multibyte strings in the header prevent the headers from being parsed correctly.

In my case, the header in question is Content-Disposition and the multibyte string is a utf8-encoded Chinese attachment filename.

```
(rdb:1) p mail.parts.last.header[:content_disposition]
attachment; filename="商品出荷のお知らせ.rtf.zip"
(rdb:1) p mail.parts.last.header[:content_disposition].field.class
Mail::UnstructuredField
(rdb:1) p mail.parts.last.header[:content_disposition].errors
[["content-disposition", "attachment; filename=\"\xE5\x95\x86\xE5\x93\x81\xE5\x87\xBA\xE8\x8D\xB7\xE3\x81\xAE\xE3\x81\x8A\xE7\x9F\xA5\xE3\x82\x89\xE3\x81\x9B.rtf.zip\"", #<Mail::Field::ParseError: ContentDispositionElement can not parse |attachment; filename="商品出荷のお知らせ.rtf.zip"|
Reason was: Expected one of 
, \, (, ; at line 1, column 23 (byte 23) after 
>]]
```

As you can see, the content disposition field ends up as an UnstructuredField rather than a ContentDispositionField < StructuredField as a result of a parse error. I'm guessing the parse error was caused by having the string of bytes corresponding to ">]]" occur somewhere (byte 23?) in the multibyte string that is the attachment filename.

I'm curious if this is a bug in Mail or Treetop.

**Comment by jeremy** [comment]
Fixed by #1103.
