### ISSUE TITLE
UTF chars in domain

### ISSUE THREAD

**Issue by anoam** [mikel/mail#1331]
Hey there!

With `2.6.6` it works like this:
```ruby
> Mail::Address.new('test@пример.com')

Mail::Field::ParseError: Mail::AddressList can not parse |test@пример.com|
Reason was: Only able to parse up to test@п
```

With `2.7.1` like this:
```ruby
m = Mail::Address.new('test@пример.com')
=> #<Mail::Address:47006254243260 Address: |test@пример.com| >

m.domain
=> "пример.com"
```
But is it correct behavior? I suspect `пример.com` isn't a valid domain.

**Comment by jeremy** [comment]
Hey! Mail 2.7 supports internationalized mail headers. See https://github.com/mikel/mail/pull/1103/files#diff-9baf848f559092bcfc67b61114e6fd97R30 per [RFC6532](https://tools.ietf.org/html/rfc6532#section-3.2).
