### ISSUE TITLE
Mail doesn't correctly parse emails when read with 'rb'

### ISSUE THREAD

**Issue by Rakete1111** [mikel/mail#1334]
```ruby
s = File.read("/path/to/file")
Mail.new(s).text_part # okay

Mail.read("/path/to/file").text_part # nil!
```

(This is an email with non-ASCII characters).

This is because `Mail.read` internally uses the `'b'` flag when reading the email and this is causing some issues when parsing for some reason I think.

**Comment by Rakete1111** [comment]
Seems like the `'b'` is required, since I get `ArgumentError: invalid byte sequence in UTF-8` (message.rb:2032) for some emails. But then other multipart emails get parsed incorrectly.

**Comment by jeremy** [comment]
Try `File.binread(path)` to read a file contents as binary instead of UTF-8.

**Comment by Rakete1111** [comment]
If I do that then Mail can't correctly pase the email. The text_part is nil in that case.
