### ISSUE TITLE
Removing extra line-breaks added by some email clients (like gmail with quoted-printable encoding)

### ISSUE THREAD

**Issue by LucDelmon** [mikel/mail#1338]
Hi,

I am trying to extract the text/body from a mail sent from a gmail client. I discovered that a several number of line-break were added to the text_part (the email client automatically add line breaks so the text renders nicely on small screens/for printing). After googling a bit I stumbled across the mention of FWS and CFWS for email headers ([ref](https://stackoverflow.com/questions/37170893/what-does-cfws-and-fws-mean-in-this-abnf)) but I’m not sure this is what I see here (cf below, it seems that the folding is actually done via =\r\n)

The encoding is set to 'quoted-printable' in this case. I need to remove this encoding so I can render this text appropriately on large screens. I tried to decode the text in various ways but none removed the extra line break.

I was also unable to remove them manually (with a regex) after decoding, because then I have no way to distinguish between such an unwanted extra line-break from one actually meant by the sender.

You can see the extra unwanted “\r\n” in the image below alongside with the "wanted" ones.

![image](https://user-images.githubusercontent.com/35261367/57233537-1af3e780-701f-11e9-8d60-15883d1ee93f.png)

while looking at `email.text_part.body.raw_source` I managed to find a pattern for the extra line breaks.

![image](https://user-images.githubusercontent.com/35261367/57233758-8d64c780-701f-11e9-8287-63aec99ce334.png)

In raw_source every undesired `\r\n` is preceded by an `=\r\n`.

So my actual solution is to correct directly the raw_source before decoding like this :

```ruby
corrected_raw_source = email.text_part.body.raw_source.gsub(/(=\r\n)(.*)(\r\n)/, '\2 ')
email.text_part.body.instance_variable_set(:@raw_source, corrected_raw_source)
```

and then decode the results.

It works perfectly but I guess that directly modifying @raw_source is not recommended.

Did I miss an option that could have managed it?

Should I go on with a feature request or even a start of PR to add a method `#remove_folding_xxx` (what would be a good name for this `=\r\n` ?)

**Comment by jeremy** [comment]
*Should* be fixed by #1210.
