### ISSUE TITLE
Any best practices or recommendations for extracting only new message body from Mail::Message?

### ISSUE THREAD

**Issue by stevenmaguire** [mikel/mail#1340]
Greetings! 

I don't feel like this is a problem specifically for this library and I am hoping that someone has already solved this problem and can point me in the right direction. I'm looking for a gem or gist or blog post that offers some real-world best practices or suggestions for effectively extracting the new part of the email body from `Mail::Message` objects without the thread.

Given the following example...

```
Hay! I think this is a cool idea!

Best,
Steven 

--

Steven's pretty cool signature

On Thu, May 9, 2019 at 7:17 PM Example <example@foo.bar> wrote:

> Let's try to extract non-threaded, original content from emails. Cool?
>
> Example
```

I'd like to reliably extract...

```
Hay! I think this is a cool idea!

Best,
Steven 

--

Steven's pretty cool signature
```

Ideally for the plaintext and html parts of the `Mail::Message`

**Comment by jeremy** [comment]
Check out https://github.com/github/email_reply_parser 👍🏼
