### ISSUE TITLE
`deliver` fails when using instance variables in the block.

### ISSUE THREAD

**Issue by wowawiwa** [mikel/mail#1349]
The spec below describes the difference in `Mail.deliver` behaviour when 1) using local vars 2) using instance vars.

```ruby
require 'spec_helper'

RSpec.describe "Mail surprising behaviour when using instance vars" do
  before do
    Mail::TestMailer.deliveries.clear
  end

  describe "control" do
    it 'raises SMTP To address may not be blank: []' do
      Mail.deliver do
        to 'mikel@me.com'
        from 'you@you.com'
        subject 'testing'
        body 'hello'
      end

      expect(Mail::TestMailer.deliveries.count).to eq(1)
    end
  end

  describe "surprising behaviour" do
    it 'raises when using instance variables' do
      @to = 'mikel@me.com'

      expect do
        Mail.deliver do
          to @to
          from 'you@you.com'
          subject 'testing'
          body 'hello'
        end
      end.to raise_exception(ArgumentError, "SMTP To address may not be blank: []")
    end
  end
end
```

**Comment by jeremy** [comment]
The block is evaluated in the context of the new mail message, so the `@to` instance variable is pointing somewhere you don't expect! That's how the `to`, `from` etc invocations work: they're calling those methods on the new Mail::Message instance.

To yield without evaluation within the new mail message, accept a block argument like so:
```ruby
Mail.deliver do |m|
  m.to @to
  m.from 'you@you.com'
  m.subject 'testing'
  m.body 'hello'
end
```

**Comment by wowawiwa** [comment]
@jeremy Thanks for the answer. I could actually imagine why this happens, still I think this behaviour might be surprising for some users. Shouldn't it be stated in the README?

**Comment by karimtimer** [comment]
Also have ran into this! Agree that this would be handy to state in the README - shall I do so?
