### ISSUE TITLE
BCC is missing for received emails

### ISSUE THREAD

**Issue by maryshirl** [mikel/mail#1351]
I created a service that handles inbound emails for a certain domain, let's say example.com.

When I send an email with ABC@example.com as the only bcc, mail.bcc returns that email address ["ABC@example.com"].

However, when I send an email with more than 1 BCC (i.e. ABC@example.com  and another email address), the mail.bcc returns an empty array. 

I understand the the other email address shouldn't be returned.

I wanted to know the email address in our domain where the email was bcc to. If there's only one BCC, the mail.bcc works. But if multiple BCC, mail.bcc doesn't work.

Could this be a bug?  Or is there another way around?

Thank you!

**Comment by jeremy** [comment]
BCC handling depends on the original mail sender and your mailserver. Both typically strip the BCC header if it's present.

Depending on your mailserver, you can see who *received* the message, at least. Check out X-Original-To and Delivered-To for Postfix.

To diagnose further, take a look at the raw headers on the original message to see which recipient headers are included.
