### ISSUE TITLE
Access and read from multiple email accounts

### ISSUE THREAD

**Issue by p-sqr** [mikel/mail#1358]
Hello

This is a feature request more than an issue.

I have a series of tests in a number of feature files that generate emails when users are created. Part of each test is checking the content of the last unread email. 

Ideally, I'd like each feature file to have its own email address so the tests could be run concurrently, but as the email account is set in the mail defaults, I can't work out how to change it for each feature file.

Any help would be most appreciated. 

This is in the .env.rb file:
```
Mail.defaults do
  retriever_method :pop3,
                   :address => "pop.gmail.com",
                   :port => 995,
                   :user_name => gmail_file['gmail_username'],
                   :password => gmail_file['gmail_pw'],
                   :enable_ssl => true
end
```
Where gmail_username and gmail_pw are read in from another file.

And the last unread email is accessed like this:

` @recd_mail = Mail.last`

Thanks,

Peter

**Comment by p-sqr** [comment]
Is OK, I think I got it now.

**Comment by Maikell84** [comment]
There is a special place in hell for people, who ask a question and answer it with "nevermind, i figured it out" **without posting the actual solution!!** :rage1::rage2::rage3::rage4:

---


Here is what worked for me:
When I want to change the account, I overwrite the retreiver_method, before calling `Mail.all` (or `Mail.first` or whatever)
```
  def mail_account_login(user_name, password)
    Mail.retriever_method.settings[:user_name] = user_name
    Mail.retriever_method.settings[:password] = password
  end
```

**Comment by p-sqr** [comment]
Sorry about that.

If I still had the solution, I'd post it, but I had to change to the Gmail API client so all my code for the mail gem is gone.

Won't happen again.
