### ISSUE TITLE
Issues with lib/mail/elements/address.rb `format`

### ISSUE THREAD

**Issue by spartan218** [mikel/mail#1361]
Recently have been running into some issues where when you pass
in a display name with a single double-quote into either the `to:` or `from:` of a mail object 
the lower level parser just breaks. 

For example if I pass in `Brian "Guzman <myemail@domain.com>` the call to `format` will then detect the invalid character `"` in the display name and wrap it in a quoted string 

`Brian "Guzman <myemail@domain.com>`  - > `"Brian \"Guzman" <myemail@domain.com>` 

However this still breaks the parsing at some level because when `.formatted` is called on this instead of being able to format the address, it becomes cut off with no address (only sees `"Brian \"`. When the mail object is created the field becomes an `UnstructuredField` and cannot call the `formatted` method and can cause exceptions.

Returning andUnstructuredField essentially causes the exception to be hidden until the caller tries to call any method that a CommonAddress field might have. I'm not sure if this is the right behavior. This means any consumer of the mail object needs to check if the field being accessed through the mail hash is an `UnstructuredField` before using it. But then, what is the right way to handle it? Throw another Exception? Eat the Exception and move on?

Short of deleting any quotes in the string (or only when there are an odd number) I don't see a good way to deal with this. Any suggestions?

**Comment by rafbm** [comment]
You should instantiate a `Mail::Address` and set each of `address` and `name` individually:

```ruby
name = 'Brian "Guzman'
address = 'myemail@domain.com'

a = Mail::Address.new
a.display_name = name
a.address = address

p a.to_s
# => "\"Brian \\\"Guzman\" <myemail@domain.com>"

puts a.to_s
# => "Brian \"Guzman" <myemail@domain.com>
```

Rails master has recently introduced a new `email_address_with_name` helper that does just that: https://github.com/rails/rails/pull/36454/files#diff-df5a757beffcee1e175f7a82362a1800

**Comment by spartan218** [comment]
@rafbm Can you explain why setting these fields individually will fix this?

I believe thats just setting the values on the a new Mail:Address object.
I am more interested in calling `.formatted` on a `Mail::field` object that has the double quote.

Also I just head up my ruby version is `2.3.8` and my mail package is `2.6.4`

**Comment by rafbm** [comment]
@spartan218 The idea is that `Brian "Guzman <myemail@domain.com>` is an _invalid_ email address representation; the valid version would be `"Brian \"Guzman" <myemail@domain.com>`. Setting `display_name` and `address` individually on a `Mail::Address` instance and then calling `to_s` on it will return a valid representation of it, which you can pass to `to:` or `from:` without a problem.

**Comment by spartan218** [comment]
Thanks for explaining and the pointer.
