### ISSUE TITLE
To/From headers with quotation marks in them

### ISSUE THREAD

**Issue by pwim** [mikel/mail#1377]
It appears the mail gem doesn't handle creating a `Mail` object with a `to` or `from` value that has quotation marks in it.

For example

``` ruby
puts Mail.new(to: 'Nat "King" Cole <nat@example.com>')
```

results in

```
Date: Tue, 04 Feb 2020 14:34:17 +0900
To: King <nat@example.com>
Message-ID: <5e390259df064_f9af2c60244a4@example.local.mail>
Mime-Version: 1.0
Content-Type: text/plain
Content-Transfer-Encoding: 7bit
```

whereas I think it should be

```
Date: Tue, 04 Feb 2020 14:34:17 +0900
To: "Nat \"King\" Cole" <nat@example.com>
Message-ID: <5e390259df064_f9af2c60244a4@example.local.mail>
Mime-Version: 1.0
Content-Type: text/plain
Content-Transfer-Encoding: 7bit
```

Is quoting of display names something that should be handled by the mail gem, or is quoting and escaping display names something I'm supposed to do as a user of the gem?

**Comment by carolina-y** [comment]
Hi, @pwim, you can automatically escape them by doing (code extracted from `ActionMailer`):

```ruby
address = Mail::Address.new.tap do |builder|
  builder.address = 'nat@example.com'
  builder.display_name = 'Nat "King" Cole'
end
```

You can `address.to_s`.

Sorry for the late reply :) But I ran into this.

**Comment by pwim** [comment]
@carolina-y Awesome, thanks for pointing out this method!
