### ISSUE TITLE
No connection could be made because the target machine actively refused it. - connect(2) for "pop.163.com" port 25 (Errno::ECONNREFUSED)

### ISSUE THREAD

**Issue by kematy** [mikel/mail#1387]
No connection could be made because the target machine actively refused it. - connect(2) for "pop.163.com" port 25 (Errno::ECONNREFUSED)
from d:/Ruby25/lib/ruby/2.5.0/net/pop.rb:545:in `open'
	from d:/Ruby25/lib/ruby/2.5.0/net/pop.rb:545:in `block in do_start'
	from d:/Ruby25/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
	from d:/Ruby25/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
	from d:/Ruby25/lib/ruby/2.5.0/net/pop.rb:544:in `do_start'
	from d:/Ruby25/lib/ruby/2.5.0/net/pop.rb:537:in `start'
	from d:/Ruby25/lib/ruby/gems/2.5.0/gems/mail-2.7.1/lib/mail/network/retriever_methods/pop3.rb:133:in `start'
	from d:/Ruby25/lib/ruby/gems/2.5.0/gems/mail-2.7.1/lib/mail/network/retriever_methods/pop3.rb:63:in `find'
	from d:/Ruby25/lib/ruby/gems/2.5.0/gems/mail-2.7.1/lib/mail/mail.rb:140:in `find'
	from D:/ruby-lab/email/Mail_imap.rb:15:in `<main>'

**Comment by jeremy** [comment]
No POP service is running on the host you're connecting to 😊
