### ISSUE TITLE
Been a while, time for a release?

### ISSUE THREAD

**Issue by utkarsh2102** [mikel/mail#1391]
Hiya,

It has been 80 commits since the last release. Can we please have a new release? :)

**Comment by jeremy** [comment]
Yeah!

**Comment by sunsations** [comment]
+1 for the a new release

**Comment by simi** [comment]
Anything blocking release I can help with?

**Comment by MrJoy** [comment]
I'd be happy to contribute as well, if it could help get a new release minted.

**Comment by mikel** [comment]
Just released 2.8.0.rc1 that includes Ruby 3.x support - please test and let us know.
