### ISSUE TITLE
parsers are too big

### ISSUE THREAD

**Issue by ahorek** [mikel/mail#1393]
Ragel needs a new state for each possible character.

removing this parser would reduce the size by half
https://github.com/mikel/mail/blob/master/lib/mail/parsers/rfc3629_utf8.rl#L18

I think there's an opportunity to optimize this, perhaps replace it with a function? Thoughts?

see also https://github.com/mikel/mail/pull/1343

**Comment by jeremy** [comment]
Open to experimentation!

**Comment by mikel** [comment]
@ahorek go for it!
