### ISSUE TITLE
Issue parsing .msg file from Outlook

### ISSUE THREAD

**Issue by nocoli** [mikel/mail#1394]
Getting an `ArgumentError Exception: invalid byte sequence in UTF-8` error when trying to parse any .msg file saved to my computer from Outlook. 

## Steps to reproduce
1. Drag any email from your inbox onto somewhere on your local disc (eg Desktop) to save it.
2. Try the following code:
```
test = File.read(File.expand_path("path_to_file.msg"))
Mail.new(test)
```
and you wil get `*** ArgumentError Exception: invalid byte sequence in UTF-8`

also trying `Mail.new(test.b)` just returns what looks like encoded text

Any help would be much appreciated.

## Environment
Windows 10
Outlook Version 2004 Monthly Channel

**Comment by ahorek** [comment]
this gem doesn't support msg format, you have to convert it to eml first

there's a tool that will allow you to do that https://github.com/aquasync/ruby-msg

**Comment by nocoli** [comment]
Thanks for the heads up. Going to try and work with the gem you suggested and see how I go although getting a few warnings when using it.

Could I suggest mentioning something about this or more broadly the file extension types supported maybe in the README?

**Comment by mikel** [comment]
@nocoli if you would like, please create a PR explaining the other gems you can use to parse or read eml files.
