### ISSUE TITLE
Encoding with quoted-printable produces an extra CR character

### ISSUE THREAD

**Issue by dalibor** [mikel/mail#1420]
```ruby
>> p Mail.new(Mail.new(body: "®\n123\n123\n123").encoded).decoded
=> "®\r\n123\r\n123\r\n123"
```
(® is used to trigger quoted-printable encoding)

I believe we should revert https://github.com/mikel/mail/pull/1208. `::Mail::Utilities.to_crlf` should only be used with `raw_source=` i.e. when we're parsing an email (`Mail.new(content)`) and not when we're creating an email by specifying the body content `Mail.new(body: body)`. I think all the problems around CR LF are because we're not distinguishing between creating and parsing emails.

**Comment by jeremy** [comment]
Fixed by #1210
