### ISSUE TITLE
iso-2022-jp with utf-8 body

### ISSUE THREAD

**Issue by pwim** [mikel/mail#1423]
I've noticed that we're receiving emails where the charset is specified as `iso-2022-jp`, but the body itself is in `utf-8`. For example, the following:

``` eml
From: <sender@example.com>
To: <receiver@example.com>
MIME-Version: 1.0
Content-Type: text/plain; charset=iso-2022-jp
Content-Transfer-Encoding: 7bit

ほげ
```

When I call the `decoded` method, the result is `"������\n"` (i.e., all characters are treated as invalid and thus replaced).

I've dug a bit into ISO/IEC 2022, but to be honest it goes a bit over my head. However, as I have been seeing emails like this from multiple senders, I'm assuming that this is something that's allowed, and not just the result of a misconfigured sender

**Comment by johnnyshields** [comment]
If the body content is actually UTF-8, then its probably a misconfigured sender. I've seen quite a bit of this kind of weirdness from domestic Japanese mail vendors.

**Comment by pwim** [comment]
You're probably right that it is a misconfigured sender. I'm assuming email clients have built in a ton of hacks to work around things like this, but perhaps it's outside the scope of this gem. As I've moved on from the project using this, I'll close the issue.
