### ISSUE TITLE
Fix for README - multipart

### ISSUE THREAD

**Issue by kapfenho** [mikel/mail#1436]
In the README there is an example that creates broken emails.

I've seen open issues that are most likely based on this usage.

This applies to emails **containing plain text, HTML content, and attachments**.

For such emails you need to create a `multipart` hierarchy like this:

```
mail = Mail.new do
  part :content_type => "multipart/mixed" do |p1|
    p1.part :content_type => "multipart/related" do |p2|
      p2.part :content_type => "multipart/alternative",
              :content_disposition => "inline" do |p3|
        p3.part :content_type => "text/plain; charset=utf-8",
                :body => "Here is the attachment you wanted\n"
        p3.part :content_type => "text/html; charset=utf-8",
                :body => "<h1>Funky Title</h1><p>Here is the attachment you wanted</p>\n"
      end
    end
    add_file '/path/to/myfile.pdf'
  end
  from      "Mikel Lindsaar <mikel@test.lindsaar.net.au>"
  to        "nicolas@test.lindsaar.net.au"
  subject   "First multipart email sent with Mail"
end
```

See this discussion: https://stackoverflow.com/questions/3902455/mail-multipart-alternative-vs-multipart-mixed

**Comment by flanger001** [comment]
I ran into this very problem and decided to come here to see if someone else had raised an issue. I even looked at that same StackOverflow link. Thank you! This confirms exactly what I thought I would have to do.

**Comment by mikel** [comment]
@kapfenho please feel free to open a PR to fix the README

**Comment by kapfenho** [comment]
Señor,

That's what I did a month ago now.

Not sure what you are doing.

horst



On 26.04.2022, at 13:27, Mikel Lindsaar ***@***.***> wrote:


@kapfenho <https://github.com/kapfenho> please feel free to open a PR to fix the README
