### ISSUE TITLE
Add Ruby 3.1 support to Mail 2.7 branch

### ISSUE THREAD

**Issue by stomar** [mikel/mail#1482]
Please consider backporting d9d8dcc6bae1774a033ad488cea6217db3a3ebf3 to the 2.7 branch.

Currently, using the latest stable release (Mail 2.7.1) with Ruby 3.1 makes it necessary for end users to add `net-smtp` to their Gemfile.

**Comment by johnnyshields** [comment]
@mikel this would be a big help to many users if you could do this.

**Comment by mikel** [comment]
This has been discussed at length in https://github.com/mikel/mail/pull/1439 and is not a simple fix unfortunately.
