### ISSUE TITLE
Use RSpec's config.disable_monkey_patching! in tests

### ISSUE THREAD

**Issue by olleolleolle** [mikel/mail#1484]
This is a sign-post Issue about work that I'd like to try doing in this repo, now.

For more information, see https://relishapp.com/rspec/rspec-core/v/3-11/docs/configuration/zero-monkey-patching-mode

**Comment by mikel** [comment]
OK @olleolleolle , no objections, please add the changelog :)

**Comment by olleolleolle** [comment]
(Thanks for already adding this to the CHANGELOG!)
