### ISSUE TITLE
Semver break in 2.8.0.rc1 - CheckDeliveryParams

### ISSUE THREAD

**Issue by johnnyshields** [mikel/mail#1493]
Mail 2.8.0.rc1 removes the class `Mail::CheckDeliveryParams`. This is a public interface change which means that according to [Semver](https://semver.org/) either:

- Do a major version bump (3.0.0); or
- Re-add the class interface to ensure compatibility (can be marked `@deprecated`)

Otherwise, this may break some gems; I found that it broke the `mail-ses` gem which I maintain.
https://github.com/tablecheck/mail-ses/pull/4

**Comment by mikel** [comment]
Thanks for finding this, will investigate and fix.

**Comment by mikel** [comment]
Hi there @johnnyshields I think https://github.com/mikel/mail/pull/1502 should fix it for now.
