### ISSUE TITLE
The "Mime-Version" header capitalization is considered a spam signal by rspamd

### ISSUE THREAD

**Issue by borama** [mikel/mail#1497]
I noticed that the mail gem [generates](https://github.com/mikel/mail/blob/641060598f8f4be14d79bad8d703e9f2967e1cdb/lib/mail/fields/mime_version_field.rb#L8) the MIME version header capitalized as `Mime-Version` as opposed to `MIME-Version` mentioned in the [RFC 2045](https://www.rfc-editor.org/rfc/rfc2045#section-4). 

While this spelling is technically [perfectly correct](https://stackoverflow.com/a/6143644/1544012), it is specifically matched by an [rspamd](https://www.rspamd.com) antispam [rule called `MV_CASE`](https://github.com/rspamd/rspamd/blob/17cb2c06fd5d7dea31c1f1215ee3d5ba3cabe5f3/rules/headers_checks.lua#L589) which effectively raises the spam score by 0.5 for all emails with such header. I traced down the [original commit](https://github.com/rspamd/rspamd/commit/5c669479a0e0630f822929714332b615f11210a6) in rspamd, it has been there for years and seems to be included in the default configuration, but other than that I found no info about why this rule was added.

I briefly checked a few mail service providers and found that the header capitalization varies a lot:
- GMail uses "MIME-Version"
- FastMail uses "Mime-Version"
- HEY uses "Mime-Version" (but, being a Rails app, perhaps it uses this gem to generate emails :) )

I'll be glad to open a PR if you're interested, thanks!

**Comment by mikel** [comment]
Fixed in https://github.com/mikel/mail/pull/1503

**Comment by borama** [comment]
Thanks @mikel for taking a look at this!
