### ISSUE TITLE
Receiving `NoMethodError: undefined method address_list` on `Mail::FromField`

### ISSUE THREAD

**Issue by shayonj** [mikel/mail#1521]
Example
```ruby
      mail =
        Mail.new do
          from "mikel@test.lindsaar.net"
          to "you@test.lindsaar.net"
          subject "This is a test email"
        end
      mail.from_address.to_s
```

Exception:
```ruby
NoMethodError: undefined method `address_list' for #<Mail::FromField:0x0000000110305c30 @errors=[], @name="From", @element=#<Mail::AddressList:0x0000000110305af0 @addresses=[#<Mail::Address:96100 Address: |mikel@test.lindsaar.net| >], @group_names=[]>, @value="mikel@test.lindsaar.net", @charset="UTF-8">

      field.send(name, *args, &block)
           ^^^^^
```

This is happening on `2.8.0` and wasn't the case in `2.7.1`

**Comment by ahorek** [comment]
the example doesn't work for me on 2.7.1. Maybe you have a modification that enhances the gem somehow?

why don't you just use ```mail.from.first``` ?

**Comment by ahorek** [comment]
it comes from a Rails integration, it'll be fixed by https://github.com/rails/rails/pull/46643

**Comment by shayonj** [comment]
Yeah that is a good workaroud! Happy to close this issue too, or if you want to keep it open for tracking, feel free to reopen 🙌🏾
