### ISSUE TITLE
undefined method `disable_starttls_auto' 

### ISSUE THREAD

**Issue by seb-sykio** [mikel/mail#1550]
ruby 3.1.2p20
Rails 7.0.4
mail 2.8.0

exception : undefined method `disable_starttls_auto' for #<Net::SMTP localhost:25 started=false>

              smtp.disable_starttls_auto
                  ^^^^^^^^^^^^^^^^^^^^^^
Did you mean?  disable_starttls
               enable_starttls_auto
/shared/bundle/ruby/3.1.0/gems/mail-2.8.0/lib/mail/network/delivery_methods/smtp.rb:138:in `block in build_smtp_session'
<internal:kernel>:90:in `tap'
/shared/bundle/ruby/3.1.0/gems/mail-2.8.0/lib/mail/network/delivery_methods/smtp.rb:113:in `build_smtp_session'
/shared/bundle/ruby/3.1.0/gems/mail-2.8.0/lib/mail/network/delivery_methods/smtp.rb:109:in `start_smtp_session'

with mail 2.7.1, it works fine

**Comment by duc-hoang-kim** [comment]
Hi @seb-sykio, I saw this issue was fixed already in 2.8.1 version 
https://github.com/mikel/mail/issues/1541

**Comment by seb-sykio** [comment]
thanks for answer. I tried with 2.8.1 and still same issue

**Comment by eval** [comment]
This is fixed in [2.8.1.rc2](https://rubygems.org/gems/mail/versions/2.8.1.rc2) - feedback welcome.

**Comment by mmustala** [comment]
Works for me

**Comment by Polo2** [comment]
Works for me too, with 2.8.1.rc2 💪 

Email delivery was broken since release to version 2.8.0.1, included with `rails` last release (7.4.0.1).

Thanks!

**Comment by motine** [comment]
`2.8.1.` works like a charm. thanks for the fix!

**Comment by eval** [comment]
Thanks all for the feedback! Closing.
