### ISSUE TITLE
Why does mail add extra carriage return characters to raw_source?

### ISSUE THREAD

**Issue by kbaum** [mikel/mail#32]
We have a header

<pre><code>
irb(main):022:0> header
=> "MIME-Version: 1.0\nDate: Mon, 17 Aug 2009 11:45:47 -0700\nReceived: by 10.150.123.13; Mon, 17 Aug 2009 11:45:47 -0700 (PDT)\nMessage-ID: <18b14b9b0908171145h71d7c7e0m@mail.gmail.com>\nSubject: Get started with Gmail\nFrom: Gmail Team <mail-noreply@google.com>\nTo: weshop cucumber <weshopcucumber@gmail.com>\nContent-Type: multipart/alternative; boundary=000e0cd590f0686c8a04715acf14\n"
</code></pre>

We read it in to mail and compare it to the original header and we get false:

<pre><code>
irb(main):023:0> header==Mail.new(header).raw_source
=> false
</pre></code>

Turns out the Mail.raw_source has extra '\r' characters not in the original header:

<pre><code>
irb(main):024:0> Mail.new(header).raw_source
=> "MIME-Version: 1.0\r\nDate: Mon, 17 Aug 2009 11:45:47 -0700\r\nReceived: by 10.150.123.13; Mon, 17 Aug 2009 11:45:47 -0700 (PDT)\r\nMessage-ID: 18b14b9b0908171145h71d7c7e0m@mail.gmail.com\r\nSubject: Get started with Gmail\r\nFrom: Gmail Team mail-noreply@google.com\r\nTo: weshop cucumber weshopcucumber@gmail.com\r\nContent-Type: multipart/alternative; boundary=000e0cd590f0686c8a04715acf14"
</pre></code>

thx.

-karl

**Comment by mehagar** [comment]
Could someone explain why this is the case? I'm running into this after upgrading the `mail` gem.
