### ISSUE TITLE
Send an ERB file through this mail gem

### ISSUE THREAD

**Issue by nfriend21** [mikel/mail#474]
Hi there,

Im using Sinatra and this gem, and Im able to send email ok.  However, when I send an ERB file, it comes through as plain text and it doesnt render the ruby code.  For example:

---

 mail = Mail.deliver do
   to user_email
   from 'support@iconosites.com'
   subject 'Your Upgrade is being processed'
   body File.read('views/email.erb')
 end

---

Is there a way to have it render the Ruby code?  

Thanks!

Nick

**Comment by SolomonHD** [comment]
I had to modify it slightly
```ruby
body ERB.new(File.read(file_path_variable)).result(binding)
```
This allowed me to use variables in the .html.erb file. 
Maybe add this to the README? Should be useful for people.

**Comment by jeremy** [comment]
Good one for the ERB docs! Out of scope for this library, which is using the result.
