### ISSUE TITLE
more about the encoding

### ISSUE THREAD

**Issue by uranio-235** [mikel/mail#511]
codificaion=false
# take the encoding from the remote page(charset in html header)

codificacion=$pagina.split('charset=')[1].split('"')[0]
codificacion='UTF-8' unless codificacion
# encode it with the page encoding

$pagina.force_encoding(codificacion).encode!('UTF-8')
# then submit it in a email and get this:

/usr/local/lib/ruby/2.0.0/net/http.rb:384: warning: previous definition of HTTP was here
/usr/local/lib/ruby/gems/2.0.0/gems/mail-2.5.3/lib/mail/fields/unstructured_field.rb:149:in `encode!': "\xC3" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)

**Comment by jeremy** [comment]
Stale issue. @ConradIrwin is right on: This is a double-encoding error.
