### ISSUE TITLE
Attachment detection failure

### ISSUE THREAD

**Issue by benjamin-thomas** [mikel/mail#513]
Hello,
Please see the following sample email https://gist.github.com/PryFlack/6a676266c072d864d2e5

Basically this email came from an automated system and doesn't have a closing MIME boundary. string 

The code given on the README to download attachements in consequence fails (returns an empty array).

``` ruby
mail.attachments.each do | attachment |
...
```

I managed to trace back the problem to <code>lib/mail/body.rb</code>.
The <code>Body#split!</code> method relies on the fact that there is such a closing boundary.

The attachment data gets lost in <code>self.epilogue</code> and the following line cancels itself since the array size is equal to 2.

``` ruby
parts[1...-1].to_a.each { |part| @parts << Mail::Part.new(part) }
```

Please note  that I can open the attachment with other mail clients such as Rouncube web client and Thunderbird, without any error.

I don't feel I understand the code well enough, and the implications of modifying the parsing behaviour to propose a pull request.

**Comment by jeremy** [comment]
Stale issue, dead links. Thanks for the original report, though, @benjamin-thomas!

**Comment by benjamin-thomas** [comment]
Thanks, I fixed the links though, for history.

For info, I did a quick check with v2.6.4 and the attachment is correctly detected now.
