### ISSUE TITLE
Attachment missing on HTML/Plaintext/Attachment Mail when Attachment's content type text/plain

### ISSUE THREAD

**Issue by krissi** [mikel/mail#522]
I already posted this example in #118 (closed). This is another problem.

```
require 'mail'

mail = Mail.new
mail.delivery_method :sendmail
mail.sender = "me@example.com"
mail.to = "someguy@example.com"
mail.subject = "Multipart Test"
mail.content_type = "multipart/mixed"

html_part = Mail::Part.new do
  content_type 'text/html; charset=UTF-8'
  body "<h1>HTML</h1>"
end

text_part = Mail::Part.new do
  body "TEXT"
end

mail.part :content_type => "multipart/alternative" do |p|
  p.html_part = html_part
  p.text_part = text_part
end

mail.add_file :filename => "file.txt", :content => "FILE"

mail.deliver!
```

The attachment is not recognized as attachment in Thunderbird, becuase the attachment part gets sorted in front of the multipart/alternative part.

This is done in message.rb line 1704 (#ready_to_send!), because it is text/plain. The sorting code should consider if it is attachment and sort it to the back.

If you change the filename to e.g. "file.pdf" everything works.

**Comment by ccoenen** [comment]
i have the very same problem. renaming `:filename` is not an ideal workaround, but in my case, it gets the job done.

**Comment by ccoenen** [comment]
Better yet: i'm now specifying a mime_type like this, and i get to keep my filename:

    mail.attachments['changes.txt'] = {content: diff, mime_type: 'text/x-diff'}

**Comment by jeremy** [comment]
Moving to current issue with full history: #1022. Thanks @krissi!
