### ISSUE TITLE
Generating invalid content/message ID fields due to Socket.gethostname with invalid chars

### ISSUE THREAD

**Issue by psylinse** [mikel/mail#555]
I'm getting a `undefined method`match' for nil:NilClass`

![screen shot 2013-06-05 at 11 15 58 pm](https://f.cloud.github.com/assets/161737/615073/8bc8e00e-ce2d-11e2-9c2e-3cf17b79417e.png)

It seems to be originating from:

![screen shot 2013-06-05 at 11 16 31 pm](https://f.cloud.github.com/assets/161737/615076/97a4d694-ce2d-11e2-8bb5-6cb79722b7b0.png)

From what I can tell, on my machine, `Socket.gethostname` in the class `ContentIdField` class an unparsable value. Ragel returns this error "Only able to parse up to <51afba3eb0fef_fa683fe1f94606705508d@unknown-28:". 

My hostname is "unknown-28:cf:e9:4d:54:db.home".

What would be the best fix for this? Changing the Content-Id generator seems to be the easiest.

**Comment by psylinse** [comment]
I haven't used `mail` in some time. Is this still an issue or can I close this?

**Comment by jeremy** [comment]
Still an issue. Thanks @psylinse!

**Comment by psylinse** [comment]
Hey, I'm going to close this out as it just sits on top of my issues list in github and I have no way of removing it from my list of issues. It's been many years since I've written ruby. Feel free to reproduce this with the info under your name.
