### ISSUE TITLE
delivery_method settings don't seem to work as documented

### ISSUE THREAD

**Issue by timbray** [mikel/mail#573]
I should be able to change the port number, for example, by
```ruby
mail.delivery_method :sendmail, { :address => 'some.host' } // copied from rdoc.info
```
but this doesn’t seem to work.  To actually do this I had to do like this:

```ruby
 # doesn't work
 # mail.delivery_method  :smtp, { :openssl_verify_mode => 'none' }
 dm = mail.delivery_method
 dm.settings[:openssl_verify_mode]  = 'none'
```
Also in rdoc.info, it asserts this should work:
```ruby
 mail.delivery_settings = { :address => 'some.host' }
```
which seems wrong.  

Maybe the bug I’m reporting is that the docs at rdoc.info are wrong?  But I look at the #delivery_method method, it really looks like a getter not a setter.

**Comment by jeremy** [comment]
Long in the tooth here, but:

1. First example needs to be `:smtp`. The `:sendmail` delivery method uses the command-line program to submit to the local MTA, where `:address` isn't a meaningful option.
2. That's what's meant to be documented. `mail.delivery_settings = …` has never existed!
