### ISSUE TITLE
Mail::Message#html_part does not create text/html part

### ISSUE THREAD

**Issue by postmodern** [mikel/mail#589]
For some reason, the new part is `text/plain`.

```
email = Mail.new do
  to 'alice@example.com'
  from 'bob@example.com'
  subject 'hello'

  html_part do
    body 'hello world'
  end
end

email.parts
=> [#<Mail::Part:28604040, Multipart: false, Headers: <Content-Type: text/plain>>]
```

<pre>
puts email
Date: Thu, 25 Jul 2013 16:37:49 -0700
From: bob@example.com
To: alice@example.com
Message-ID: <51f1b6cd51140_eb7127f00014961@tank.lab.mail>
Subject: hello
Mime-Version: 1.0
Content-Type: multipart/alternative;
 boundary="--==_mimepart_51f1b6b05f4c3_eb7127f000147dd";
 charset=UTF-8
Content-Transfer-Encoding: 7bit

----==_mimepart_51f1b6b05f4c3_eb7127f000147dd
Date: Thu, 25 Jul 2013 16:37:49 -0700
Mime-Version: 1.0
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit
Content-ID: <51f1b6cd4fca1_eb7127f00014829@tank.lab.mail>

hello world

----==_mimepart_51f1b6b05f4c3_eb7127f000147dd--
</pre>

**Comment by jeremy** [comment]
Fixed by 9a902b386d80ca9d413df0e7aed96a7e77de5de3, first released in Mail 2.5.4. Also see #116.
