### ISSUE TITLE
Issue sending SMTP messages on Windows

### ISSUE THREAD

**Issue by get9** [mikel/mail#604]
First off, to be honest I'm not sure if this is an issue with the gem itself or with my setup. I'm writing a small script that parses directories and emails file owners when certain files get out of date.

My environment is a Windows 7 x64 VM running on an OS X 10.8.4 host. I'm using Ruby 2.0.0p195 via rubyinstaller.org with the most up-to-date version of mail. When I run my script, I get the following error:

```
 Permission denied - connect(2)
```

I'm using the following configuration before constructing and sending the message:

``` ruby
Mail.defaults do
  delivery_method :smtp, {
    address: 'my.server.com',
    port: '25',
    user_name: 'username',
    password: 'password',
    authentication: :login,
    enable_start_ttls_auto: true
  }
end
```

I'm kind of at a loss as to where to go next. I'm not sure whether the problem lies with my configuration, with my environment, or something else entirely.

**Comment by jeremy** [comment]
Windows firewall :)
