### ISSUE TITLE
Mail.new(string) calls force_encoding on input

### ISSUE THREAD

**Issue by substars** [mikel/mail#614]
commit c7818a95f9f9fddc675f75452ea5000c46c30d94 calls force_encoding on input strings, leading to strange behavior like this:

```
str.encoding 
# => 'UTF-8'
Mail.new(str)
str.encoding
# => 'ASCII-8BIT'
```

to_crlf makes a copy of the string anyway; I think force_encoding should get called on the copy since we got a surprise Encoding::UndefinedConversionError later on in our app.

**Comment by jeremy** [comment]
Fixed by #615
