### ISSUE TITLE
Need a way to handle Gmail's non-standard folding of Diagnostic-Code header

### ISSUE THREAD

**Issue by eburkitt** [mikel/mail#620]
In delivery report emails (those for which`Message#delivery_status_report`returns true) from Gmail I find the`Diagnostic-Code`header wrapped like so:

```
Diagnostic-Code: smtp;550-5.1.1 The email account that you tried...
550-5.1.1 double-checking the recipient's email address for typos or
550-5.1.1 unnecessary spaces. Learn more at
550 5.1.1 http://support.google.com/mail/bin/answer.py?answer=6596...
```

As far as I can determine this is non-standard, but as Gmail is to free email service what Microsoft once was to browsers it would be nice to gracefully handle this format. Properly unfolding this field would also eliminate the spurious warning caused by`Field#initialize`attempting (and failing) to process the last line as 'name:value' due to the ':' in the URL.

Any thoughts or suggestions on how or whether to handle this?

**Comment by jeremy** [comment]
Probably due to a naive DSN parser:
```ruby
    def parse_delivery_status_report
      @delivery_status_data ||= Header.new(body.to_s.gsub("\r\n\r\n", "\r\n"))
    end
```
It's building headers from the encoded body, when it should use the *de*coded body, which should unfold these headers appropriately.
