### ISSUE TITLE
Encoding changes when PHRASE_UNSAFE in Mail::Utilities#quote_phrase

### ISSUE THREAD

**Issue by bmorton** [mikel/mail#621]
When I do this:
address = Mail::Address.new(email)
address.display_name = name
address.format

If name is UTF-8, it gets force encoded to ASCII-8BIT and then doesn't get force encoded back to its original encoding because of: 
https://github.com/mikel/mail/blob/master/lib/mail/utilities.rb#L24

Do we need to pass the ASCII-8BIT string to dquote and then return the new string in its original encoding or can we pass the originally encoded string to dquote so that the string that's passed in gets set back to its proper encoding?

I'll throw together a quick pull request for this, but comments on the question above would be appreciated.

**Comment by jeremy** [comment]
Working on current master:
```ruby
>> name = "\u{101}\u{10d}\u{113}"
=> "āčē"
>> name.encoding
=> #<Encoding:UTF-8>
>> e = Mail::Address.new('ace@example.com')
=> #<Mail::Address:70260901962420 Address: |ace@example.com| >
>> e.display_name = name
=> "āčē"
>> e.format
=> "\"āčē\" <ace@example.com>"
>> name.encoding
=> #<Encoding:UTF-8>
>> name
=> "āčē"
```
