### ISSUE TITLE
Semicolon in "display name" of an email address breaks parser

### ISSUE THREAD

**Issue by benmoss** [mikel/mail#624]
Using an email address like `"Fo;o <foo@bar.com>"`, which I believe should be valid, makes the email return two different values for 'to'.

``` ruby
>> Mail.new(to: "Fo;o <foo@bar.com>").to
=> ["Fo", "foo@bar.com"]
>> Mail.new(to: "Foo <foo@bar.com>").to
=> ["foo@bar.com"]
```

**Comment by kennethkalmer** [comment]
@benmoss I had a long look again, I think my interpretation is from how quoted-string is built up:

```
   qtext           =   %d33 /             ; Printable US-ASCII
                       %d35-91 /          ;  characters not including
                       %d93-126 /         ;  "\" or the quote character
                       obs-qtext
   qcontent        =   qtext / quoted-pair
   quoted-string   =   [CFWS]
                       DQUOTE *([FWS] qcontent) [FWS] DQUOTE
                       [CFWS]
```

Looking at the ASCII table, a semi-colon sits there at 59, so it is included in the list... It is murky, really murky.

All I wanted to do was help triage the issue. Maybe it should be closed and left here for others to find and re-open if needs be. Wdyt?

**Comment by benmoss** [comment]
@kennethkalmer yeah, in the first example I was using the atom format, not the quoted-string. quoted-string would be `Mail.new(to: "\"Fo;o\" <foo@bar.com>")`, and that actually appears to parse correctly.

I appreciate the help. I am now under the impression that I am in the wrong here and so I didn't want to burden an already overburdened maintainer with another spurious issue.

**Comment by kennethkalmer** [comment]
@benmoss awesome, thanks! I thought I'd help by trying to triage issues here. Nice to see one gone, now to find the next one
