### ISSUE TITLE
Inconsistent removal of extra whitespace in header fields

### ISSUE THREAD

**Issue by edsinclair** [mikel/mail#625]
In the course of looking at the feasibility of using the Mail Gem edge build I'm pretty sure I found a bug in the 2.5.4 release / 2-5-stable branch that was fixed by this commit: 72befdc4dab3e6e288ce226a7da2aa474cf5be83

I've added a regression spec to this branch:

https://github.com/edsinclair/mail/commit/6aad4919c4def83e939d1955b4f332ae8b2248f7

Not sure if you'd be interested in a patch against the 2-5-stable branch. Feel free to close this, if not.

**Comment by jeremy** [comment]
Interested in a PR against master, for sure, but I don't follow the new specs or what was fixed/regressed :)  Could you explain?
