### ISSUE TITLE
Get n Number of emails

### ISSUE THREAD

**Issue by dagda1** [mikel/mail#626]
Can anyone tell me how I could get the 'n' most recent emails.

I have tried this:

```
imap.find(mailbox: 'INBOX', read_only: true, count: 50, order: :desc)
```

But this returns the 50 oldest emails in the inbox.  I've tried `order: :asc` also with the same result.

Does anybody know the correct parameters?

**Comment by jeremy** [comment]
Need `what: :last` as well.
