### ISSUE TITLE
no implicit conversion of Mail::AddressContainer into String

### ISSUE THREAD

**Issue by dagda1** [mikel/mail#631]
I am getting some weird errors when importing user's gmail emails.

I have this method that parses various email addresses into an array:

```
  def email_addresses
    array = mail.from

    if mail.to.class == String
      array << mail.to
    else
      array.concat mail.to
    end if mail.to

    array.concat mail.reply_to if mail.reply_to
    array.concat mail.cc if mail.cc
    array
  end
```

The weird thing is that sometimes mail.to is a string and not a Mail::AddressContainer with this code:

```
    if mail.to.class == String
      array << mail.to
    else
```

The other weird thing is that `array.concat mail.to` sometimes blows up with this error message:

> > no implicit conversion of Mail::AddressContainer into String

But if I inspect the array it looks like this:

> > ["someone@sanoserv.com"]

**Comment by jeremy** [comment]
Due to headers with parse errors leading to UnstructuredField fallbacks instead of valid address fields.
