### ISSUE TITLE
Multipart emails not being parsed properly

### ISSUE THREAD

**Issue by eviltrout** [mikel/mail#638]
I have a multipart email with an attachment that is not being parsed properly by Mail::Message. 

Here is the message: https://gist.github.com/eviltrout/7568298

``` ruby
  Mail.read("attachment.eml").parts.size
  #2 
```

When in fact there are 4 parts. It seems to put the text and html version inside the alternative part rather than parsing them out.

I would love to hear if there is a workaround for this of I can help with a patch.

**Comment by courtenay** [comment]
Potentially #539 and #781 - hidden whitespace between headers on the gap line.

**Comment by jeremy** [comment]
Unrelated to #539. MIME parts are hierarchical, so what you're seeing is normal 😊

Use `#text_part` and `#html_part` shorthands to grab the text and html parts within the multipart/alternative wrapper:
```ruby
>> m = Mail.read('attachment.eml')
# …
>> m.parts.size
=> 2
>> m.all_parts.size
=> 4
>> m.text_part
=> #<Mail::Part:70186611509480, Multipart: false, Headers: <Content-Type: text/plain; charset=ISO-8859-1>>
>> m.html_part
=> #<Mail::Part:70186611497580, Multipart: false, Headers: <Content-Type: text/html; charset=ISO-8859-1>, <Content-Transfer-Encoding: quoted-printable>>
```
