### ISSUE TITLE
Please implement Mail::AttachmentsList#merge! to allow method chaining

### ISSUE THREAD

**Issue by MarkDBlackwell** [mikel/mail#645]
I notice that method Mail::AttachmentsList#[]= accepts a string argument, so (of course) it somewhat resembles a Ruby Hash.

As you know, the method [signature](http://www.ruby-doc.org/core-2.0.0/Hash.html#method-i-5B-5D-3D) of Hash#[]= is `hsh[key] = value → value`.

Also, as you know, the simplest method [signature](http://www.ruby-doc.org/core-2.0.0/Array.html#method-i-5B-5D-3D) of Array#[]= is `ary[index] = obj → obj`.

However, when given a string argument, per this [final line](https://github.com/mikel/mail/blob/8e455b910607d439e1b369df0d66de8e3f7f707e/lib/mail/attachments_list.rb#L81) (which is `@parts_list << attachment`), the method signature of Mail::AttachmentsList#[]= seems to be `attachments_list[string] = hash → parts_list`.

This seems an interesting choice of return value. Is that intended?

Anyway, I myself don't have a motivation for the Mail::AttachmentsList#[]= method's return value to be the rvalue hash (from the right side) as happens with Ruby's Hash#[]= and Array#[]= (as mentioned above).

At present, after writing:

``` ruby
h = {content: (::Base64.encode64 some_string),
     mime_type: 'application/pdf',
     transfer_encoding: :base64}
```

we (sometimes) must write somewhat un-DRY code, such as:

``` ruby
key = 'abc'
mail.attachments[key] = h.dup
decoded = mail.attachments[key].decoded # Keep code duplication.
```

Instead, Hash has another useful method, Hash#merge! , with [signature](http://www.ruby-doc.org/core-2.0.0/Hash.html#method-i-merge-21) `merge!(other_hash) → hsh`.

This method returns the object itself (that is, `self`) which (as you know) is useful for chaining method calls.

Since `mail.attachments[string]` itself acts (somewhat) like a hash (in that it can be assigned a hash), would you consider implementing Mail::AttachmentsList#merge!  with signature `attachments_list.merge!(string, hash) → attachment`, making it somewhat resemble Ruby's Hash#merge! , thereby enabling us to write in a nice, DRY, chained manner, as in this code?:

``` ruby
decoded = mail.attachments.merge!('abc', h.dup).decoded
```

Or, you could substitute another meaningful name, such as Mail::AttachmentsList#add_attachment, if it returns the attachment also.

I notice that (at least) the [spec file](https://github.com/mikel/mail/blob/8e455b910607d439e1b369df0d66de8e3f7f707e/spec/mail/attachments_list_spec.rb) for Mail::AttachmentsList contains no test coverage of the return value of Mail::AttachmentsList#[]= . This leads me to hope you haven't yet thought about its return value, and (that) it is free to be set in a useful way.

Dare I suggest you set the return value of Mail::AttachmentsList#[]= (or Mail::AttachmentsList#[string]=) to be the attachment itself, so we could write even nicer code (such as this)?:

``` ruby
decoded = (mail.attachments['abc'] = h.dup).decoded
```

This could be implemented by adding another line after your present [final line](https://github.com/mikel/mail/blob/8e455b910607d439e1b369df0d66de8e3f7f707e/lib/mail/attachments_list.rb#L81), to make the last two lines be:

``` ruby
@parts_list << attachment
attachment
```

This is my favorite way. But you may not want overtly to break away from the pattern (and expectation) formed by the return values of Ruby's Array#[]= and Hash#[]= methods (as mentioned above).

**Comment by jeremy** [comment]
Note that the return value of `#[]=` methods is _always_ the right hand side, per Ruby syntax. Doesn't matter what the method returns. The return value is the assigned value.

**Comment by MarkDBlackwell** [comment]
Yes; I see that the return value of assignment methods (e.g., `def a=(value)`) *always* is the right-hand side, per the [Ruby docs](https://ruby-doc.org/core-2.4.2/doc/syntax/methods_rdoc.html#label-Return+Values).

So, that leaves:

> would you consider implementing Mail::AttachmentsList#merge!  with signature `attachments_list.merge!(string, hash) → attachment`, making it somewhat resemble Ruby's Hash#merge! , thereby enabling us to write in a nice, DRY, chained manner, as in this code?:

``` ruby
decoded = mail.attachments.merge!('abc', h.dup).decoded
```

> Or, you could substitute another meaningful name, such as Mail::AttachmentsList#add_attachment, if it returns the attachment also.

**Comment by jeremy** [comment]
> Or, you could substitute another meaningful name, such as Mail::AttachmentsList#add_attachment

I like that route, e.g. `mail.attachments.push filename, options`.

In your usage, I think working with `mail.parts` directly may be more natural. You're already very close to constructing the `Mail::Part` yourself and pushing it to `mail.parts`.
