### ISSUE TITLE
cannot load mime-type 

### ISSUE THREAD

**Issue by cmoulliard** [mikel/mail#654]
I have created a Ruby project to use your mail lib but mail 2.5.4 complains that it cannot `load such file -- mime/type` even if mime-type 1.16 is installed on my machine 

```
/Users/chmoulli/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/mail-2.5.4/lib/mail.rb:9:in `require': cannot load such file -- mime/types (LoadError)
    from /Users/chmoulli/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/mail-2.5.4/lib/mail.rb:9:in `<module:Mail>'
    from /Users/chmoulli/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/mail-2.5.4/lib/mail.rb:2:in `<top (required)>'
    from /Users/chmoulli/MyProjects/hyla/lib/hyla/send_mail.rb:4:in `require'
```

and gem mime-types

```
ll /Users/chmoulli/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/mime-types-1.16/
```

Is there a workaround ?

**Comment by kaleemullah360** [comment]
just remove `require 'mime-types'` in your ruby file.

as `mime-types` is built in ruby. you don't need to install its gem or include its explicitly. 

just use it.
this works for me.
