### ISSUE TITLE
Broken subject

### ISSUE THREAD

**Issue by avkvl** [mikel/mail#658]
Hello.
I'm using mail to read from file.
In some letters i have broken subject.
For example:
In file subject is^
Subject: [RC] =?UTF-8?B?0L7QsdC90L7QstC70LXQvdC40LUg0LjQvdGB0YLRgNGD0LrRhg==?=
 =?UTF-8?B?0LjQuCDQtNC70Y8gaXBob25l?=
but after parsing I have only part of subject:
irb(main):017:0> mail.subject
=> "[RC] \u043E\u0431\u043D\u043E\u0432\u043B\u0435\u043D\u0438\u0435 \u0438\u043D\u0441\u0442\u0440\u0443\u043A\u0446"

Message was generated by Thunderbird 24.2.0

**Comment by tjpnz** [comment]
See #852
