### ISSUE TITLE
Possible issue with line endings when parsing Mime Message

### ISSUE THREAD

**Issue by pascalbetz** [mikel/mail#667]
First: i abused Mail to parse a SOAP response which was formatted as Mime Message.

Two parts, the SOAP envelope as XML and TIFF image attachment.
After extracting the attachment part the image was corrupted.

It took a while of poking around in the attachment to find that  **x0d** got replaced with **x0dx0a**

There is **String#to_crlf** which would explain the behaviour. Could it be that it get's applied to (binary) attachment content as well?

I created a spec ( https://github.com/pascalbetz/mail/commit/1c998554df9ca922c68cc872c8ec2b36345c0c19)
which fails for me. And i think it should pass.

**Comment by jeremy** [comment]
#408
