### ISSUE TITLE
dot-stuffing is not performed on SMTP transmission

### ISSUE THREAD

**Issue by yyyc514** [mikel/mail#669]
```
Mail.new :body => "Next is a bad line\n.\nBut the email goes on."
```

This will blow up when trying to send over standard SMTP because the single period on its own line is interpreted as the end of the SMTP DATA block.  I feel like either Mail or Ruby's SMTP should be handling this - it's not something the user needs to be thinking about at this high level.

Thoughts?

**Comment by jeremy** [comment]
#683
