### ISSUE TITLE
Mail::TestMailer.deliveries and multiple messages

### ISSUE THREAD

**Issue by kswope** [mikel/mail#682]
Multiple calls to deliver can fill up 'test queue' with same message object.  Is this a design decision or oversight? I expected to find a new mail object for each deliver! call.

```
destinations = ['one@example.com', 'two@example.com]

mail = Mail.new

destinations.each do |destination|
  mail.smtp_envelope_to = destination
  # and further manipulations
  mail.deliver!
end

deliveries = Mail::TestMailer.deliveries

assert deliveries.first == deliveries.second

```

**Comment by jeremy** [comment]
It's intentional. It would be clearer if it pushed newly-encoded messages rather than mail objects, but it's for general use convenience.
