### ISSUE TITLE
Security of enable_starttls_auto vs. enable_starttls

### ISSUE THREAD

**Issue by the8472** [mikel/mail#694]
Looking at https://github.com/mikel/mail/blob/master/lib/mail/network/delivery_methods/smtp.rb#L100-109 it seems that only Net::SMTP's `.enable_starttls_auto` is supported, but not `.enable_starttls`.

As I understand it the auto-method is susceptible to downgrade attacks, thus voiding all advantages of authentication and only leaving passive security in place.

**Comment by jeremy** [comment]
#521
