### ISSUE TITLE
Attachments in mail messages with both html_part and text_part don't show up in Yahoo! or AOL webmail.

### ISSUE THREAD

**Issue by lighth7015** [mikel/mail#706]
As per this [StackOverflow post](http://stackoverflow.com/questions/8217213/html-emails-missing-attachments), I've been running into this myself, and its got me scratching my head as to why.

I'm running **ruby 1.9.3p125 (2012-02-16 revision 34643) [x86_64-freebsd7.0]**, with mail version **2.5.4**.

**Comment by jeremy** [comment]
#853
