### ISSUE TITLE
Can create incorrect Content-Type for multipart messages with attachments

### ISSUE THREAD

**Issue by ChrisAshworth** [mikel/mail#73]
In lib/mail/message.rb the logic of assigning the Content-Type header field can result in an erroneous value under certain circumstances.

Consider the following:

mail = Mail.new do
    to "chris@figure53.com"
    from "support@figure53.com"
    subject "hello there"
    text_part do
      body "I hope you're well."
    end
    html_part do
      content_type "text/html; charset=UTF-8"
      body "<h1>Funky Title</h1><p>I hope you're well</p>"
    end
    add_file :filename=>"license.xml", :content=>license.licenseXML
  end

In this situation the assignment of the text_part and html_part trigger a call to add_multipart_alternate_header, which forces the the content type to be set to 'multipart/alternative'.  

When the add_file method is called the message _should_ be converted to 'multipart/mixed', but it is not.  While add_file does trigger add_multipart_mixed_header, this method checks for the presence of a content-type and therefore does nothing if it already exists.  (In contrast, add_multipart_alternate_header clobbers the content-type no matter what.)

The result is a message which is incorrectly typed as multipart/alternative.  At least in Mail.app on Snow Leopard this results in a message which only displays the last part of the message (i.e. the attachment).

FWIW, I have worked around this with the following step before calling mail.deliver!:

broken_content_type = mail.header[:content_type]
mail.header[:content_type] = Mail::ContentTypeField.new( ['multipart', 'mixed', broken_content_type.parameters] )

(I don't know the "correct" way to fix it.)

Thanks!

**Comment by shanecav84** [comment]
I ran into a similar issue with ActionMailer when attaching files _after_ the email had been rendered. My issue:

```
email = SomeMailer.some_action
email.message.content_type
=> 'text/plain'

email.message.add_file(some_file)
email.message.content_type
=> 'text/plain'
```

I expected the content type to change to 'multipart/mixed'.

Workaround:
```
email = SomeMailer.some_action
email.message.content_type
=> 'text/plain'

email.content_type = nil
email.message.add_file(some_file)
email.message.content_type
=> 'multipart/mixed'
```
