### ISSUE TITLE
Content Transfer Encoding header ignored for multipart emails

### ISSUE THREAD

**Issue by j-manu** [mikel/mail#731]
Setting a content transfer encoding fails for multipart emails

Here's the failing spec - https://github.com/j-manu/mail/commit/bb06f7852cb12c0d887733ab22d32d951e5f9f7f

It does work if you do

``` ruby
html_part do
 content_transfer_encoding 'quoted-printable'
 content_type 'text/html; charset=UTF-8'
  body '<h1>HTML</h1>'
end
```

but I was expecting it to work outside the block also just like non multipart mails.

**Comment by j-manu** [comment]
@bf4 Can you take a look at this? I have rebased the failing spec on current master.

**Comment by jeremy** [comment]
The API is, a bit confusingly, `message.transport_encoding = …`
