### ISSUE TITLE
Setting body for a base64 encoded email doesn't  work

### ISSUE THREAD

**Issue by fernandomm** [mikel/mail#793]
Consider the following email:

```
Return-Path: test@example.org
From: test@example.org
To: test@gmail.com
Date: 8 Sep 2014 15:01:11 -0300
Subject: Test
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: base64
Message-ID: <08das97123jdas61mlczpqiue@localhost>

RW0gYW5leG8gc2UgZW5jb250cmEgbyBhcnF1aXZvIGVsZXRyw7RuaWNv=
```

If I try to read it and set a new body, it will result in the content not being converted to base64.

```
[11] pry(main)> @mail = Mail.read('example.msg')
=> #<Mail::Message:70230690112340, Multipart: false, Headers: <Return-Path: test@example.org>, <Date: Mon, 08 Sep 2014 15:01:11 -0300>, <From: test@example.org>, <To: test@gmail.com>, <Message-ID: <08das97123jdas61mlczpqiue@localhost>>, <Subject: Test>, <Content-Type: text/plain; charset=utf-8>, <Content-Transfer-Encoding: base64>>
[12] pry(main)> @mail.body = 'Example'
=> "Example"
[13] pry(main)> @mail.body
=> �
[14] pry(main)> puts @mail
Return-Path: <test@example.org>
Date: Mon, 08 Sep 2014 15:01:11 -0300
From: test@example.org
To: test@gmail.com
Message-ID: <08das97123jdas61mlczpqiue@localhost>
Subject: Test
Mime-Version: 1.0
Content-Type: text/plain;
 charset=utf-8
Content-Transfer-Encoding: base64

Exam
````

Note that @mail.body is messed since it's not encoded in base64. I guess that mail gem should take care of this since it does for other content transfer encodings, no?

**Comment by richardsondx** [comment]
I think the entire email (header + body ) is usually encoded in base64.

**Comment by jeremy** [comment]
Setting the raw body directly is a low-level method. It assumes you're setting the raw source and that it matches the `Content-Transfer-Encoding` you've provided.

You can set `@mail.content_transfer_encoding = nil` along with the `@mail.body = '…'` to get back in business. Then the content transfer encoding will be set automatically for you when the message is encoded.
