### ISSUE TITLE
How to configure socket timeouts on Net::SMTP

### ISSUE THREAD

**Issue by mheffner** [mikel/mail#804]
We noticed that several of our job processors that send mail using the mail gem got stuck during an outage at our MTA provider. All of the job processors appeared to be blocked when contacting our MTA using the smtp delivery method.

Is there a way to configure some of the underlying timeouts of [Net::SMTP](http://ruby-doc.org/stdlib-2.1.2/libdoc/net/smtp/rdoc/Net/SMTP.html) in the mail gem?

**Comment by jeremy** [comment]
Added in #892
