### ISSUE TITLE
Memory Use exploded in 2.6

### ISSUE THREAD

**Issue by schneems** [mikel/mail#812]
Rails 4.2 is moving to Mail 2.6.1 and i'm seeing a huge increase in memory usage in my running application. After some digging, it looks like the culprit was the Mail version bump.

To demonstrate the issue, here's a script to reproduce without rails:
### Build Gemfiles

```
$ mkdir 2.6.1
$ cat <<  EOF > 2.6.1/Gemfile
  source 'https://rubygems.org'
  gem 'mail', '2.6.1'
  gem 'get_process_mem'
EOF

$ mkdir 2.5.4
$ cat <<  EOF > 2.5.4/Gemfile
  source 'https://rubygems.org'
  gem 'mail', '2.5.4'
  gem 'get_process_mem'
EOF
```
### Install

```
$ env BUNDLE_GEMFILE=2.6.1/gemfile bundle install
$ env BUNDLE_GEMFILE=2.5.4/gemfile bundle install
```
### Test script

```
$ cat <<  EOF > script.rb
  require 'get_process_mem'
  mem = GetProcessMem.new
  before = mem.mb
  require 'mail'
  after = mem.mb
  puts after - before
EOF 
```
### Results

```
$ env BUNDLE_GEMFILE=2.6.1/gemfile bundle exec ruby script.rb
# => 41.44140625 # mb
$ env BUNDLE_GEMFILE=2.5.4/gemfile bundle exec ruby script.rb
# => 11.41015625 # mb
```
## EWAT

Mail 2.6.1 takes up almost 4 times more memory at Require time 0_o. Initial guess is that this has to do with the switch from treetop to ragel via @bpot 

cc/@matthewd

**Comment by vishnurkrishnan** [comment]
How can we do this with rails 3.2.22 and ruby 2.0, because i can't upgrade the mail gem to 2.6, it seems that is not compatible with action mailer, i was following this https://www.schneems.com/2014/11/07/i-ram-what-i-ram.html

**Comment by grosser** [comment]
use a money-patched version that loosens the dependency
gem "mail",                 git: 'https://github.com/zendesk/mail', ref:
'261-as-259' # fake 2.5.999 version so we can use with actionmailer 3

**Comment by vishnurkrishnan** [comment]
Yes, but here in this https://www.schneems.com/2014/11/07/i-ram-what-i-ram.html says need to upgrade to 2.6.3 or higher, will it be possible with this patch?

**Comment by grosser** [comment]
nope, then do the same patch again but from 2.6.3 and it should be good
