### ISSUE TITLE
Inconsistent behaviour when setting a header to nil

### ISSUE THREAD

**Issue by lime** [mikel/mail#822]
I am parsing incoming mail which sometimes contains the `Sender` header, sometimes not. I need to remove the header, and from what I can see the way to do that is to set it to `nil`.

The behaviour of `m.sender = nil` changes depending on whether the field is set or not. See the following irb log against the current HEAD:

``` ruby
irb(main):001:0> require 'mail'
=> true
irb(main):002:0> m = Mail.new
=> #<Mail::Message:70230664095220, Multipart: false, Headers: >
irb(main):003:0> m.sender = nil
=> nil
irb(main):004:0> m
=> #<Mail::Message:70230664095220, Multipart: false, Headers: <Sender: >>
irb(main):005:0> m.sender = nil
=> nil
irb(main):006:0> m
=> #<Mail::Message:70230664095220, Multipart: false, Headers: >
irb(main):007:0> m.sender = nil
=> nil
irb(main):008:0> m
=> #<Mail::Message:70230664095220, Multipart: false, Headers: <Sender: >>
```

The behaviour is the same regardless of how I set the header (`m.sender`, `m[:sender]`, `m.header[:sender]`)

**Comment by valscion** [comment]
Hi @jeremy, I'm interested in this weird flip-flop behaviour, too. You never seemed to respond to @lime's question:

> Is there any reason to keep this flip-flop behaviour, or would it be agreeable to you if I change nil assignment behaviour to delete-or-remain-nil?

I'm curious, too.

**Comment by jeremy** [comment]
I don't think there's a reason to keep the odd flip-flop. Assigning `nil` to a field that doesn't exist should just do nothing, IMO.
