### ISSUE TITLE
undefined method `multipart' for Mail::Message

### ISSUE THREAD

**Issue by indapublic** [mikel/mail#828]
mail (2.6.1)

```
require 'mail'
message = imap.fetch(imap.search(['ALL'])[0], '(RFC822 ENVELOPE)')[0]
envelope = message.attr['ENVELOPE']
message = Mail.new(message.attr['RFC822'])
@output = message.multipart
```

undefined method `multipart' for #<Mail::Message:0x007facd91e30b0>

**Comment by kennethkalmer** [comment]
@indapublic, the [README](https://github.com/mikel/mail#reading-a-multipart-email) has a very clear example to follow, you're calling a method that doesn't exist.

@bf4 I'm sure this one can be closed.

**Comment by bf4** [comment]
Thank @kennethkalmer for the ping

Closing as resolved.  If you think the issue should be re-opened, please re-open and add new information.
