### ISSUE TITLE
Having an issue understanding how to utilize the 'quoted-printable' decoding

### ISSUE THREAD

**Issue by andrewsmhay** [mikel/mail#842]
Does anyone have any examples they could point me to (above and beyond the code)? I'm doing the following (for reference):

mailbox = '/var/mail/ubuntu'
mail = Mail.read(mailbox)
puts mail.body.decoded

(simple, right?) :)

Ultimately I want to have a clean message body that I can start extracting IPs, domains, and URLs from...but i need to get past this hurdle first.

**Comment by bf4** [comment]
Could you give an example of what the body you are getting looks like?  It's unclear to me if you're asking how to use the gem to read emails from the mailbox or what you mean by "clean message body".  Thanks

**Comment by jeremy** [comment]
Use `mail.decoded` (not `mail.body.decoded`) to get the message body.
