### ISSUE TITLE
Please add support uuencode or explain how to download the file

### ISSUE THREAD

**Issue by yuri-karpovich** [mikel/mail#844]
I'm trying to download uuencode attachment:

```
   content = email.message.attachments[0].body
   File.open("#{dir}/#{file_name}" , "wb") { |file| file.write(content) }
```

=> Mail::UnknownEncodingType: Don't know how to decode **uuencode**, please call #encoded and decode it yourself.

Can you please explain how can I download it without errors?

**Comment by bf4** [comment]
Please include some the failing code, along with your Ruby version, Mail gem version, OS, etc. per https://github.com/mikel/mail/blob/master/CONTRIBUTING.md
