### ISSUE TITLE
Possible breaking change from 2.5->2.6?

### ISSUE THREAD

**Issue by bf4** [mikel/mail#846]
- https://github.com/discourse/discourse/commit/9a8d7d3ef001ee894a4c456e4b9b01382f56e839
- https://github.com/discourse/discourse/commit/b0f35cbf6a9d555d2c6535bca25648ee024ee72e

```plain
# Rails 4.1.6+ will relax the mail gem version requirement to `~> 2.5, >= 2.5.4`.
# However, mail gem 2.6.x currently does not work with discourse because of the
# reference to `Mail::RFC2822Parser` in `lib/email.rb`. This ensure discourse
# would continue to work with Rails 4.1.6+ when it is released.
 gem 'mail', '~> 2.5.4'
```

In [2.5.4 `lib/mail/parsers/rfc2822.rb` defined a tree-top parser](https://github.com/mikel/mail/blob/2.5.4/lib/mail/parsers/rfc2822.rb) that was removed when switching to the ragel parser.

I am unsure if this is a breaking change that should be fixed in the 2.6.x series

cc @chancancode @SamSaffron

**Comment by jeremy** [comment]
Internal Mail lib usage fixed by https://github.com/discourse/discourse/commit/613761d1cddcd9e96c418748f0055e6136154bae

**Comment by SamSaffron** [comment]
thanks for mentioning that, forgot to update here
