### ISSUE TITLE
Message#to should fail explicitly when email address not parseable

### ISSUE THREAD

**Issue by Fryie** [mikel/mail#857]
Currently, I see the following behaviour:

```{ruby}
Mail.new(to: "test@example.org").to
=> ["test@example.org"]
```
Returns an array as specified by the docs.

However, if the email address is not parseable, the method returns a string:
```{ruby}
Mail.new(to: "test<@example.org").to
=> "test<@example.org"
```

IMO, this behaviour is undesirable, as this causes subsequent hard-to-debug errors down the road. A method should not return either String or Array of String. It would be much better to raise an exception.

**Comment by jeremy** [comment]
Agreed in principle. This masks some internal behavior with address list parsing.

Check out `#to_addrs` as an alternative:
```ruby
>> Mail.new(to: "test@example.org").to_addrs
=> ["test@example.org"]
>> Mail.new(to: "test<@example.org").to_addrs
=> ["test<@example.org"]
```
