### ISSUE TITLE
Invalid byte sequence in UTF-8 when calling Mail::Message.encoded

### ISSUE THREAD

**Issue by whather** [mikel/mail#861]
I sporadically get this error when calling "encoded" on a message. This is the backtrace:

```
invalid byte sequence in UTF-8
ruby/2.1.0/gems/mail-2.6.3/lib/mail/fields/unstructured_field.rb:126:in `split'
ruby/2.1.0/gems/mail-2.6.3/lib/mail/fields/unstructured_field.rb:126:in `fold',
ruby/2.1.0/gems/mail-2.6.3/lib/mail/fields/unstructured_field.rb:103:in `wrapped_value',
ruby/2.1.0/gems/mail-2.6.3/lib/mail/fields/unstructured_field.rb:69:in `do_encode',
ruby/2.1.0/gems/mail-2.6.3/lib/mail/fields/unstructured_field.rb:51:in `encoded',
ruby/2.1.0/gems/mail-2.6.3/lib/mail/field.rb:189:in `method_missing',
ruby/2.1.0/gems/mail-2.6.3/lib/mail/header.rb:210:in `block in encoded',
ruby/2.1.0/gems/mail-2.6.3/lib/mail/header.rb:209:in `each',
ruby/2.1.0/gems/mail-2.6.3/lib/mail/header.rb:209:in `encoded',
ruby/2.1.0/gems/mail-2.6.3/lib/mail/message.rb:1811:in `encoded'
```

Has anyone hit this and if so do you know of a fix/workaround? All of the other UTF-8 fixes I've seen, I believe I already have.

Cheers,
Wes

**Comment by bf4** [comment]
If you can write a failing test for it, I can write a fix. I just fixed basically the same bug in rspec... https://github.com/rspec/rspec-support/blob/ef28302a09ad5b61c3b1903bda54e0da120b25d0/spec/rspec/support/encoded_string_spec.rb#L221-L236

**Comment by jeremy** [comment]
Need to see an example message and code that are failing.
