### ISSUE TITLE
Why does the received text_part contain the content type line?

### ISSUE THREAD

**Issue by DannyBen** [mikel/mail#863]
Is it intentional that the returned `message.text_part` contains the Content type header?

This is what I get:
```
"Content-Type: text/plain;\r\n charset=UTF-8\r\nContent-Transfer-Encoding: 7bit\r\n\r\nbody here\r\n"
```

When doing this:
```
msg = Mail.last
p msg.text_part.to_s
```

And so far, the only way I found to get the actual plain text, is to do this:
```
msg = Mail.last
body = msg.text_part.to_s
body = body[/\r\n\r\n(.*)/,1]
```

Am I missing some method?

**Comment by fatihorhan** [comment]
You sould use `msg.text_part.body` .

**Comment by jeremy** [comment]
`msg.text_part.decoded`
