### ISSUE TITLE
Parsing of binary encoded message parts are mangled by call to .to_crlf

### ISSUE THREAD

**Issue by jeremyricharddavies** [mikel/mail#871]
Hi

When parsing an incoming multi-part message, the loading process assigns the raw_source property (line 1990 of message.rb), but it then calls .to_crlf on this which mangles the byte sequences of binary encoded attachments (eg: images).

Is there a reason that .to_crlf is used here? I have removed this call from my local gem source and re-tested with success (on the specific messages that I am working with) but perhaps there are other messages that require this for decoding purposes.

Thanks

**Comment by jeremy** [comment]
What `Content-Transfer-Encoding` are your incoming MIME parts? If they're `8bit` they'll be encoded as CRLF-separated octets, for example.
