### ISSUE TITLE
Request: Allow custom logger for mail

### ISSUE THREAD

**Issue by johnnyshields** [mikel/mail#873]
Currently Mail writes errors to `STDERR`.

https://github.com/mikel/mail/blob/master/lib/mail/field.rb#L219

It would be nice to be able to configure a custom logger, e.g. `Mail.logger = Logger.new` (which can default to `STDERR`). Here's a workaround courtesy of @tomduncalf

```
$stderr.reopen('/dev/null', 'w')
Mail.do_something
$stderr = STDERR
```

**Comment by bf4** [comment]
ref: https://github.com/mikel/mail/pull/856

**Comment by jeremy** [comment]
Switched to `warn` in #1105
