### ISSUE TITLE
matching_body matcher fails to check multipart emails

### ISSUE THREAD

**Issue by stefanosc** [mikel/mail#879]
Hello and thank you for the great work!
I am using the matchers in a rails project and I love them :smile: 

I found that `matching_body` only works on [mail.body.raw_source](https://github.com/mikel/mail/blob/master/lib/mail/matchers/has_sent_mail.rb#L136), if the mail is multipart (text/plain, text/html) as it is common these days then this matcher fails to check the body.

I thought it could be useful to either have an additional *arg(s) to pass to the method something like:
```ruby
have_sent_email.matching_body(/my regex/, :html, :text)
```

or have 2 additional matchers for `mail.html_part.body` and `mail.text_part.body`

I could take a crack at putting PR together if you think it would be useful :smile: 
Let me know.

Thanks again :heart:

**Comment by nicolas-fricke** [comment]
I also had similar issues and once already monkey patched a method like this for my local project – I'd be happy to submit it as a PR :smiley:

**Comment by jeremy** [comment]
Moved to #935
