### ISSUE TITLE
How to reuse the body of an retrieved mail?

### ISSUE THREAD

**Issue by RST-J** [mikel/mail#884]
I'm gratefully using mail to fetch mails from some server and process them in a Rails app. Under certain circumstances I'd like to not actually forward but send a copy of a mail to some receiver.
So I'd like to reuse the body of the mail while changing from the from and to headers.
My mailer code is this:
```ruby
def send_copy(email, sender, receiver)
  email.attachments.each do |attachment|
    content_type = Mail::ContentTypeElement.new(attachment.content_type)
    attachment_name = content_type.parameters.detect { |params| params.include?('filename') || params.include?('name') }['name']
    attachments[attachment_name] = attachment.read
  end
  mail from: sender.email, to: receiver.email, subject: "[Skynet] Forwarded message: #{email.subject}", body: email.body.raw_source
end
```
The part which is not working is the reuse of the body. It generates a body in which the original MIME blocks and headers are written out. Can someone tell me how I can reuse the body of an existing mail and maybe also how inline images can be forwarded?

**Comment by jeremy** [comment]
Clone the original email and alter its fields directly, leaving the original MIME parts intact 😁
