### ISSUE TITLE
UTF-8 characters in headers can't be round-tripped

### ISSUE THREAD

**Issue by steveh** [mikel/mail#885]
Failing test: https://github.com/mikel/mail/compare/master...steveh:round_trip_utf8

When using `Mail.new(mail.encoded)`, the original values of any UTF-8 strings can't be retrieved.
       
       expected: "user@exāmple.com"
            got: "=?UTF-8?B?dXNlckBleMSBbXBsZS5jb20=?="

**Comment by jeremy** [comment]
Fixed by #910
```ruby
>> m = Mail.new { to "user@exāmple.com" }
=> #<Mail::Message:70283270913680, Multipart: false, Headers: <To: user@exāmple.com>>
>> Mail.new(m.encoded)[:to].encoded == m[:to].encoded
=> true
```
