### ISSUE TITLE
Mail.first / .last seem to return a random email every time

### ISSUE THREAD

**Issue by prrrnd** [mikel/mail#888]
Hi,

I'm having some issues with `Mail.first` and `Mail.last`.
I am connecting to my Gmail account using the exact same code as in the [README](https://github.com/mikel/mail#getting-emails-from-a-pop-server), but the returned email is always a different one, doesn't even matter whether it has been read or not.
Am I doing missing something?

**Comment by bigtunacan** [comment]
Same problem here.  I also opened a discussion on the Google Groups, but no response so far.

Additionally `Mail.all` isn't returning all emails.  Instead it returns an array of 10 seemingly random emails from my Gmail account.

https://groups.google.com/forum/#!topic/mail-ruby/meNBbmDc-uk

**Comment by bigtunacan** [comment]
@prrrnd, in case this is helpful.  It appears this issue is limited to POP3.  It works as expected if you use IMAP instead.

**Comment by prrrnd** [comment]
@bigtunacan Thanks, I figured out and decided to use IMAP.
