### ISSUE TITLE
Mail::ToField encoding address with tilde

### ISSUE THREAD

**Issue by juankiz** [mikel/mail#890]
I'm using ```Mail::ToField.new("mail+tílde@mail.com", 'UTF-8')``` and getting a ```Mail:Address``` with an address like ```'=?UTF-8?B?anVhrandomStringQ==?='``` which seems to be some sort of encoding.
Is this type of addresses supported by Mail? Any advice on getting the real address?

**Comment by carsonreinke** [comment]
Try `#decoded` and `#encoded` on the `Mail::Address` object, `#decoded` probably being the one you were looking for.

**Comment by juankiz** [comment]
@carsonreinke I tried it but the resulting string was encoded as well. I'm using mail 2.5.4

**Comment by carsonreinke** [comment]
Oh, looks like that is not legal to have an accent like that for the local-part (https://tools.ietf.org/html/rfc2822#section-3.4.1, https://tools.ietf.org/html/rfc2822#section-3.2.4, http://stackoverflow.com/questions/760150/can-an-email-address-contain-international-non-english-characters)

**Comment by jeremy** [comment]
https://github.com/mikel/mail/pull/910
