### ISSUE TITLE
Using a proxy for pop3

### ISSUE THREAD

**Issue by introvert** [mikel/mail#893]
Hello,

The documentation doesn't say much about it, but is it possible to use proxies for accessing pop3 with the mail gem?

Thanks

**Comment by AureliusTech** [comment]
I'm also interested in using this gem via a proxy -- is that possible?  thanks

**Comment by joshzitting** [comment]
I need this too! Great gem thanks!

**Comment by corehook** [comment]
so ? Proxy support ? where ? when ?

**Comment by jeremy** [comment]
No proxy support. Consider a PR setting up a POP3Connection retriever method, similar to the SMTP and SMTPConnection retriever methods, that allows you to provide your own POP3 that's set up however you like.
