### ISSUE TITLE
Mail::SendMail shellescape broken

### ISSUE THREAD

**Issue by benmmurphy** [mikel/mail#897]
https://github.com/mikel/mail/blob/master/lib/mail/network/delivery_methods/sendmail.rb#L85

So when invoking sendmail it takes the to address and escapes it and then puts it in double quotes. However, only $, `, ", and \ and newline are supported by the \ escape in bash in double quotes. So to addresses will be mangled and contain an extra \\.

For example:

    ~$ echo "foo\'bar@.com"
    foo\'bar@.com

From Bash manpage:

       Enclosing characters in double quotes preserves the literal value of all characters within the quotes, with the exception of $, `, \, and, when  history  expansion
       is  enabled,  !.  The characters $ and ` retain their special meaning within double quotes.  The backslash retains its special meaning only when followed by one of
       the following characters: $, `, ", \, or <newline>.  A double quote may be quoted within double quotes by preceding it  with  a  backslash.   If  enabled,  history
       expansion will be performed unless an !  appearing in double quotes is escaped using a backslash.  The backslash preceding the !  is not removed.

I'm not sure why we are using shellescape here and not execv style execution which would appear to be much safer.

**Comment by jeremy** [comment]
#898
