### ISSUE TITLE
Unsupported popen option :err using Sendmail delivery method.

### ISSUE THREAD

**Issue by digitalextremist** [mikel/mail#904]
I get this with jruby `1.7.20` when running in `1.9.3` mode:

```
gems/mail-2.6.3/lib/mail/network/delivery_methods/sendmail.rb:72
warning: unsupported popen option: err
```

And yet, that option does appear in the rdoc.

**Comment by jeremy** [comment]
Looks like JRuby 1.7.20 doesn't support all Ruby 1.9.x `IO.popen` options:
https://github.com/mikel/mail/blob/master/lib/mail/network/delivery_methods/sendmail.rb#L66-L74. Similar issue: https://github.com/jruby/jruby/issues/2766

This is apparently supported in JRuby 9.0.0.0.
