### ISSUE TITLE
Performance problem

### ISSUE THREAD

**Issue by ciaoben** [mikel/mail#908]
I have this simple example:

``` ruby

      email = ...   # retrieve message via net/imap
      if email
        mail = Mail.read_from_string email.first.attr['BODY[]'] # create the message object
          if mail.multipart?
            mail.subject # very slow!
            body = {
              text: mail.text_part ? mail.text_part.decoded : '',
              html: mail.html_part ? mail.html_part.decoded : ''
            }
          else
            body = mail.decoded
          end

        ....
```

I have noticed that with `read_from_string` I can create really fast a Message object, but as soon as I try to read one of its property (in this example is `.subject`, but the thing doesn't change with `.text_part` or other....) it gets very very slow!!! 

E.G. for the operation of the code, it take almost 3 secs (counting only the operation of this gem).

Am I missing something? Is it normal?

**Comment by jeremy** [comment]
It's not normal, for sure.

Messages aren't fully parsed until you try to read something from it, so it'll seem like you can create messages very fast but reading the first property is slow. Reading another property will be fast.

Could you do some benchmarking or profiling to identify what's taking 3 sec? How does it vary between different emails you're parsing?

**Comment by etagwerker** [comment]
@ciaoben Could you provide the email content? It will make easier to debug parse performance problems. You could manually change the sensitive data before sharing it.
