### ISSUE TITLE
Unable to #delete_all with IMAP

### ISSUE THREAD

**Issue by jbm715** [mikel/mail#909]
I am unable to use #delete_all. I've attempted this with v2.60 - 2.6.3

I continue to get a `Net::IMAP::BadResponseError: No mailbox selected.` when I see that the default is 'INBOX'. Error is coming from [here](https://github.com/mikel/mail/blob/0f9393bb3ef1344aa76d6dac28db3a4934c65087/lib/mail/network/retriever_methods/imap.rb#L158)

The following works, but I'd rather understand what's going on with the #delete_all rather than work around it.

``` ruby
while (messages = mailbox.find_and_delete).size > 0
   # do some things
end
```

**Comment by jeremy** [comment]
Looks like this has been broken since a3a46fe9e624a4d435c260364e3a6aef0cb6c0a8 which removed the mailbox selection.
