### ISSUE TITLE
Mail::Parsers::AddressListsParser doesn't handle double quotes in display name well

### ISSUE THREAD

**Issue by IrvinFan** [mikel/mail#911]
```
full_address = "\"The Best \\\"Starbucks\\\" in town\" <me@example.com>"
[6] pry(main)> Mail::Parsers::AddressListsParser.new.parse(full_address).addresses.first.display_name
=> "The Best \\\"Starbucks\\\" in town"
```

expect the display_name to be `"The Best \"Starbucks\" in town"`

**Comment by jeremy** [comment]
Pry calls `#inspect` on the result. Try `puts` to see the unquoted string:
```ruby
>> puts Mail::Parsers::AddressListsParser.new.parse("\"The Best \\\"Starbucks\\\" in town\" <me@example.com>").addresses.first.display_name
The Best \"Starbucks\" in town
```

**Comment by IrvinFan** [comment]
Well, puts does certain unescaping when it prints out the result. The problem is that the raw result of the parse method is used by this code and evetually fed into `Mail::Address.new`: https://github.com/mikel/mail/blob/master/lib/mail/elements/address_list.rb#L20-L30

As the result, the encoded message header is wrong when this line of code is called: https://github.com/mikel/mail/blob/master/lib/mail/message.rb#L1814

Here I can show the result in pry (output by puts)
```
[1] pry(main)> puts Mail::Header.new("From: \"The Best \\\"Starbucks\\\" in town\" <me@example.com>\r\n").encoded
From: "The Best \\\"Starbucks\\\" in town" <me@example.com>
```

**Comment by IrvinFan** [comment]
@jeremy can you check this again? I believe this does have an issue.
