### ISSUE TITLE
Request:  Disclaim monkey-patching in the README.

### ISSUE THREAD

**Issue by odigity** [mikel/mail#913]
Last week I left Rails-land to try using simpler tools (sinatra + sequel + mail).

The sequel gem comes with an extension that you can enable to add .blank() methods to ruby's core objects, which I decided I want.

On a whim, I fired up IRB with my app loaded and decided to test for the presence of .blank() before proceeding (akin TDD, where you run the tests the first time expecting them to fail before making them pass), and to my surprise, it was already there.

So I grepped the gems directory, and discovered the mail gem is already provided .blank() implementations for nil, Object, and String.

I read the code, and the implementations look fine.  However, it would have been nice to be tipped off to this monkey-patching of core objects somewhere in the README so it didn't surprise me later.

**Comment by jeremy** [comment]
Agreed. PR welcome 😊

**Comment by darrencauthon** [comment]
Hmm, so perhaps there's a bigger demand for #937 (and #940) than I thought...
