### ISSUE TITLE
How can I get a message uid? 

### ISSUE THREAD

**Issue by Archetylator** [mikel/mail#917]
I must store the UID from the last retrieved message.

**Comment by jeremy** [comment]
Assuming you're fetching IMAP, the `imap` instance and the message `uid` are yielded to the block:

```ruby
Mail.defaults do
  retriever_method :imap, …
end

Mail.find(options) do |message, imap, uid|
  # Do something with message and the UID here
end
```

https://github.com/mikel/mail/blob/master/lib/mail/network/retriever_methods/imap.rb#L88-L92

**Comment by Archetylator** [comment]
Thank you very much.

**Comment by ilyacherevkov** [comment]
It's actually not working for me atm. 

Using mail 2.7.1
