### ISSUE TITLE
Mail not delivers when delivery_method get options from environment variables

### ISSUE THREAD

**Issue by gf59ru** [mikel/mail#920]
I have Ruby on Rails application, that must deliver email messages.
I set options for mail delivering in my application (`/config/environments/production.rb` and `/config/environments/development.rb`):

```
Mail.defaults do
  delivery_method :smtp, {
                         :address => 'smtp.email.domain',
                         :port => '12345',
                         :user_name => 'user_name',
                         :password => 'password',
                         :authentication => :plain,
                         :enable_starttls_auto => true,
                         :ssl => true,
                         :tls => true
                     }
end
```

It works both in development and production, but it's insecure.
I taked out some values to environment variables:

```
Mail.defaults do
  delivery_method :smtp, {
                         :address => ENV['SMTP_ADDRESS'],
                         :port => ENV['SMTP_PORT'],
                         :user_name => ENV['SMTP_USERNAME'],
                         :password => ENV['SMTP_PASSWORD'],
                         :authentication => :plain,
                         :enable_starttls_auto => true,
                         :ssl => true,
                         :tls => true
                     }
end
```

Values takes from environment correctly - I checked it by log messages.
But in production email doesn't deliver with error `ruby/object:ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper | SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: unknown protocol`

In development mode it works regardless of values placement.

What am I doing wrong?

My development environment:
OS Windows 7 x64
ruby 2.1.5p273 (2014-11-13 revision 48405) [i386-mingw32]
Rails 4.2.1
mail 2.6.3

And production:
OS CentOS 6.7
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]
Rails 4.2.1
mail 2.6.3

**Comment by jeremy** [comment]
You probably want `ssl: false` that's for SMTPS. Odds are you are connecting via SMTP, then using STARTTLS to upgrade to a TLS session.
