### ISSUE TITLE
Wrong encoding with chunks for long string 

### ISSUE THREAD

**Issue by macuk** [mikel/mail#922]
I have a problem with proper encoding for some long UTF-8 strings. In some cases my transactional mail service rejects sent emails because of invalid sender. I make an investigation of that and found that encoded strings with chunks sometime are valid and sometime are invalid. In my opinion it depends of position multibyte chars within the string. I wrote failing test for that in my forked repo. Please review and let me know what can we do with that case. Is it really a bug. How can I help with this issue?

Failing test commit in forked repo: https://github.com/macuk/mail/commit/7e5b8b4cc3dfab13af024fdd11ad4a42e56a0d4c

Additional info:
Running Specs under Ruby Version 2.1.7
Running Specs for Mail Version 2.6.3.edge

**Comment by jeremy** [comment]
```ruby
>> string = 'This is あ really long string This is あ really long string'
=> "This is あ really long string This is あ really long string"
>> Mail::Encodings.decode_encode(string, :encode)
=> "=?UTF-8?B?VGhpcyBpcyDjgYIgcmVhbGx5IGxvbmcgc3RyaW5nIFRoaXMgaXMg44GCIHJl?= =?UTF-8?B?YWxseSBsb25nIHN0cmluZw==?="
>> Mail::Encodings.decode_encode(_, :decode)
=> "This is あ really long string This is あ really long string"
```

(Using b value decoding directly doesn't handle multiple encoded chunks.)
