### ISSUE TITLE
Mail with no ActiveSupport

### ISSUE THREAD

**Issue by thhermansen** [mikel/mail#933]
Hi,

I'm having a problem with Mail loaded in an application with no ActiveSupport. Mail defines `ActiveSupport` ([here](https://github.com/mikel/mail/blob/master/lib/mail/multibyte/unicode.rb#L394-L400)), which gets us in to trouble when other gems looks for `ActiveSupports` and finds it and thinks that `ActiveSupport.on_load` is defined too.

To give a concrete example, here is an error I do get when I pull in Mail and Awesome print together with no ActiveSupport.

`awesome_print-1.6.1/lib/awesome_print.rb:29:in `<top (required)>': undefined method `on_load' for ActiveSupport:Module (NoMethodError)`

Can the definition of ActiveSupport be removed? I did see that it has something to do with the [mail/values/unicode_tables.dat](https://github.com/mikel/mail/blob/master/lib/mail/values/unicode_tables.dat). I tried to solve it myself and make a pull request, but I didn't come to any good working solution.

**Comment by jeremy** [comment]
Please give it a shot – We can either provide a shim that uses AS if available or implement our own version of the things we depend on.

**Comment by thhermansen** [comment]
Seems like this is related to and solved in #830 :)
