### ISSUE TITLE
Remove monkey-patching?

### ISSUE THREAD

**Issue by jodosha** [mikel/mail#936]
Hello there, thank you for this great, and I mean **great** gem. :100: 

I'm wondering if there is a chance that you would accept a PR that removes monkey patching.

This technique is dangerous and can conflict with other gems that try to redefine the same set of methods. If you [search on GitHub](https://github.com/search?l=ruby&q=%22def+blank%22+language%3ARuby&ref=advsearch&type=Code&utf8=%E2%9C%93) for `blank?` definition, you'll get ~41,000 results. These gems doesn't even care to check if that method was previously defined.

This exposes `mail` to unforeseen compatibility problems with the Ruby ecosystem.

What are your thoughts about this? I can take care of this change, by submitting a PR.

Thanks in advance for your time and thanks for evaluating this request.

**Comment by darrencauthon** [comment]
Wouldn't any library that defined ```blank?``` do so with the same basic concept of "blank-ness?"  

It seems that defining ```blank?``` on a class would actually make it **more** compatible with the Ruby ecosystem, as the concept of "blankness" as a true/false is a common idea.  Monkey-patching it into Object just sets that idea at a very low level, allowing other classes to implement it as they need.

mail's implementation looks to be the same as activesupport, which has become the standard for this implementation in the Ruby ecosystem (not saying whether that's good or bad).

**Comment by jodosha** [comment]
@darrencauthon Hello and thanks for the quick reply :smile: 

> Wouldn't any library that defined blank? do so with the same basic concept of "blank-ness?"

Not really, look at [this](https://github.com/makevoid/bitcoin_exchange/blob/a39fb5b750cd8e2efef77c6bb10d9ef6d123484b/lib/monkeypatches/string.rb#L3) implementation from https://github.com/makevoid/bitcoin_exchange

```ruby
class String
  def blank?
    self == ""
  end
end
```

With the [one](https://github.com/mikel/mail/blob/master/lib/mail/core_extensions/string.rb#L25) from `mail`:

```ruby
class String
  def blank?
    self !~ /\S/
  end
end
```

And the [one](https://github.com/rails/rails/blob/7f18ea14c893cb5c9f04d4fda9661126758332b5/activesupport/lib/active_support/core_ext/object/blank.rb#L115) from ActiveSupport:

```ruby
class String
  BLANK_RE = /\A[[:space:]]*\z/

  def blank?
    BLANK_RE === self
  end
end
```

Now imagine if someone requires `mail` and then `bitcoin_exchange`, last win in this case, but that implementation is broken and can affect `mail`, because it relies on that behavior. For instance a string like this `"     "` will be no longer considered blank because of `bitcoin_exchange`.

My suggestion is to use something like `Mail::String`, so you are totally sure that once you'll invoke `#blank?` on that object, that is the implementation that you expect.

Please remember that we've just scratched the surface here with one single implementation of `#blank?`, which is only one of the several monkey-patches that `mail` uses. I'm not judging, just willing to help to improve this library :heart:

**Comment by darrencauthon** [comment]
The mail monkey patches seem to be pretty close to active support, and they back out in favor of any other inplementation (presumably active support), so it seems to be a responsible usage of monkey patching. 




I'm not high on monkey patching core classes, either -- even active support's work. But use of some of its monkey patches are so prevalent in Ruby, specifically Active*, I wouldn't worry too much about them so long as they kept the same behavior. Or gosh maybe just tack on the active support dependency, I don't know.




The Bitcoin gem seems to be irresponsible monkey patch due to the behavior that deviates from the Ruby norm. 



—

**Comment by jodosha** [comment]
@darrencauthon 

> The mail monkey patches seem to be pretty close to active support

I'm NOT saying that `mail` implements a wrong version of `String#blank?`.

My point is: if **another** gem with a **bugged** version of `String#blank?` is activated in a `Gemfile`, it breaks `mail` behaviors.

I've prepared a Gist to show, what I mean. Pheraps code, let me to explain better what I mean :smile: 

Please try this simple test: https://gist.github.com/jodosha/d542b5d99ef4fa20bdbd

It adds a broken version of `String#blank?` that causes a bug for Mail.

---

Now, because Mail adds more or less a dozen of methods to Ruby core and stdlib, the impact of that the ecosystem (and it's broken – sigh – implementations) can be dangerous for Mail itself.

---

I hope I've better explained my point now. Thank you again for your time.

**Comment by bf4** [comment]
@jodosha I'd be interesting in see a PR that removes relying on `blank?`.  As @darrencauthon said, Mail only defines `blank?` when not already defined.  You're right that another gem that breaks blank would break Mail, but that's true for any gem, no?

FWIW, I once did this in another gem and broke blank :)  https://github.com/railsbp/rails_best_practices/pull/176

**Comment by jodosha** [comment]
@bf4 @darrencauthon 

> Mail only defines blank? when not already defined.

That is great, but unfortunately other gems don't do that. We still have a problem. :smile: 

> You're right that another gem that breaks blank would break Mail, but that's true for any gem, no?

It's not about **how** Mail monkey-patches, it's about monkey-patching. Once you use it, you're exposed to this kind of problems.

> I'd be interesting in see a PR that removes relying on blank?.

I can prepare a PR, only to remove blank in one code spot, just to show how this refactoring could be applied everywhere in the gem.

> FWIW, I once did this in another gem and broke blank :)

Ouch. :smile:

**Comment by jodosha** [comment]
@bf4 I've replaced it, just in one place, to show how it's possible to replace `String#blank?` with `Mail::String#blank?`.

I haven't created a PR request, because it requires a lot of work, and before to dive into such work, I wanted to make sure that it would be considered by you.

Anyway this is the small change: https://github.com/mikel/mail/compare/master...jodosha:replace-string-blank?expand=1

**Comment by darrencauthon** [comment]
I'd recommend against doing it this way - building an object just to get the blank? method. A slightly simpler method might be to create a String module with a single blank? method on it, then call it as a function. 




Something like:




'''

module Mail

  def self.blank? input

    # that AR logic

  end

end

'''




A String class that can be instantiated seems a little confusing. It's not really a string, as you'll never need to use it that way. You really just want the function, so you might as well keep it as a function. 



—

**Comment by darrencauthon** [comment]
I just dropped in a pull request that illustrates a much larger example of what removing the monkey patch could be.  I'm using a module like I mention above... which I strongly recommend, I think using an object in this case would make it much harder.

The gem seems to be solid.  The tests that are failing are those that depend on the monkey-patched method.  I'd continue and finish this now, but I have to get to work.

**Comment by jodosha** [comment]
@darrencauthon That is great! I've used that object syntax, because it's inspired to what we do with Lotus. I'm still offering my help to reduce the amount of monkey-patching in Mail. Please let me know. Thanks! :smile:

**Comment by shevegen** [comment]
I believe one day ruby will allow one to have fine-tuned "monkey" patches, so that you can have this behaviour as part of the Mail namespace but not outside of it; refinements go towards that way but they are not there yet. But this may be in the future... ruby 3.0 or who knows when...

jodosha has a good point about other gems causing breakage.

**Comment by bf4** [comment]
@shevegen That's already possible with refinements, though I've see some edge cases where it doesn't work right

@jodosha wrote:

> look at this implementation from https://github.com/makevoid/bitcoin_exchange

I'd say that's really a bug in bitcoin_exchange.  Whenever I add a monkey-patch inspired by activesupport but choose not to require it, I base is on or copy it from activesupport.

That said, I'm all for not monkey-patching if there's a better way :) I'm enjoying the code and discussion in https://github.com/mikel/mail/pull/937

**Comment by jeremy** [comment]
#1095
