### ISSUE TITLE
Email not sent - is the "To:" setting correct?

### ISSUE THREAD

**Issue by shevegen** [mikel/mail#941]
Hi,

I have sendmail installed and running locally.

Ruby is the latest, ruby 2.2.3p173, OS is Linux.

I use code such as this here:

    mail = Mail.new do
      from     'shevegen@gmail.com'
      to       'a9703005@unet.univie.ac.at'
      subject  'This is a test mail'
      body     'Hello world!'
    end

    mail.delivery_method :sendmail
    mail.deliver

I test this in IRB and get:

      # => #<Mail::Message:95383110, Multipart: false, Headers: <From: shevegen@gmail.com>, To: a9703005unetunivieacat, Subject: This is a test mail
      # => #<Mail::Sendmail:0xc827114 @settings={:location=>"/usr/sbin/sendmail", :arguments=>"-i"}

Is the "To:" target right?

It seems to have stripped away the '.' and the '@' and I am not sure why.

If this is not a bug then this is fine I guess, I just wonder. Also the
email was not sent so I am a bit confused.

**Comment by jeremy** [comment]
Working here:
```ruby
>> mail = Mail.new do
?>       from     'shevegen@gmail.com'
>>     to       'a9703005@unet.univie.ac.at'
>>     subject  'This is a test mail'
>>     body     'Hello world!'
>>   end
=> #<Mail::Message:70140413859100, Multipart: false, Headers: <From: shevegen@gmail.com>, <To: a9703005@unet.univie.ac.at>, <Subject: This is a test mail>>
>> puts mail.encoded
Date: Fri, 11 Dec 2015 13:30:40 -0700
From: shevegen@gmail.com
To: a9703005@unet.univie.ac.at
Message-ID: <566b3270e0600_14f313fcad643f9dc5278f@stack.local.mail>
Subject: This is a test mail
Mime-Version: 1.0
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

Hello world!
=> nil
```

What version of the mail lib are you using? Give it a shot on a current release.

**Comment by shevegen** [comment]
Yes, very strange. I just got the email in the inbox, it seems as if it was sent after some delay.

I do seem to remember that it in the past it used to be sent instantly. No idea, perhaps something is wrong with my setup.

TL,DR: The email was sent and received. Thanks.

The mail gem I was using is mail-2.6.3.gem - the "To:" confused me since the . and @ seem to be stripped.
