### ISSUE TITLE
How to store SMTP users passwords?

### ISSUE THREAD

**Issue by vincenzor** [mikel/mail#942]
Hi,

Currently, our application allows our users to emails using their own Gmail account. We use your gem with gmail gem. To do that we a oauth flow in place that give us a token. We then use this token to connect to the Gmail account. Everything is secure that way.

Now, we want to let our users specify their own SMTP server to send the emails (address, port, login, password).

My question is: how can I securely store these logins/passwords? I cannot simply store it in the database, this is absolutely not secure. 

Is there some kind of MD5 authentication for SMTP? Does your gem allows me to do something 100% secure?

Thx!

**Comment by ConradIrwin** [comment]
This isn't directly related to the mail gem, and there's not much we can do to help you here.

When I've had to do this previously, I had a small proxy server responsible for SMTP authentication. My app used a modified XOAUTH2 to log into the proxy server, and that server decrypted the user's password and established the connection, which the other app could then use.

Things to ensure:

1. passwords are encrypted in a way that cannot be reversed if someone has access to your codebase and database. We did this using PBKDF2 to establish a per-user encryption key using the fake oauth tokens as the password, and a secret only known to the proxy app. (in our use-case the oauth tokens were not stored except on the client devices
2. the SMTP proxy validates the SSL certificate of the upstream connection before sending any passwords over it.
3. the password store logs all reads and writes for auditing purposes.
