### ISSUE TITLE
Mail::Utilities.to_crlf Improvement

### ISSUE THREAD

**Issue by carsonreinke** [mikel/mail#955]
`Mail::Utilities.to_crlf` seems like it can be changed to not use a `Regexp` instead by using `String#encode`.

Running this test:
```ruby
require 'benchmark'

CRLF = "\r\n"
CRLF_REGEX = Regexp.new("(?<!\r)\n|\r(?!\n)")

string = "\n\r\n\n" * 10_000

Benchmark.bm do |x|
  x.report('to_crlf:') do
    10_000.times do
      string.gsub(CRLF_REGEX, CRLF)
    end
  end
  
  x.report('encode:') do
    10_000.times do
      string.encode(:universal_newline => true).encode!(:crlf_newline => true)
    end
  end
end
```
... I get these results on 2.3.0:
```
       user     system      total        real
to_crlf: 57.450000   0.120000  57.570000 ( 57.580348)
encode:  7.790000   0.090000   7.880000 (  7.889390)
```

Am I missing something here?  I will put in a PR if not.

**Comment by kjg** [comment]
I'm not a maintainer or anything, but I say make a PR, include this perf info there. If all the tests still pass in the CI run for the PR, I can't see why they'd turn it down.

**Comment by jeremy** [comment]
Please do pursue a PR! Note we support older rubies, so we'd need
version-specific shims.

**Comment by jeremy** [comment]
:metal:
