### ISSUE TITLE
Mail::Address#display_name returns encoded or decoded value

### ISSUE THREAD

**Issue by afn** [mikel/mail#960]
Related to #359 and #411, the `Mail::Address#display_name` method will return either an encoded or a decoded string depending on whether `encoded` or `decoded` was called last. Reading the code, this seems very intentional (`display_name`, along with other methods, explicitly refers to `@output_type`, which is set to `:encode` or `:decode` by the `encoded` and `decoded` methods), but it's extremely counterintuitive. Why should calling `encode` on an address suddenly change the return value of `display_name`? I would expect the result of `display_name` to **always** be decoded; this method (along with `domain`, `local`, etc.) should be independent of the wire protocol.

For example, suppose you have a debug flag that conditionally logs the message being processed. Turning debugging on/off will change the output:

``` ruby
def extract_name(message, logger=nil)
  if logger
    logger.debug "Extracting address from #{message}"
  end
  message[:from].addrs.first.display_name
end

extract_name(Mail::Message.new("From: Tony =?UTF-8?B?Tm92w6Fr?= <tony@example.com>"))
# => "Tony Novák"
extract_name(Mail::Message.new("From: Tony =?UTF-8?B?Tm92w6Fr?= <tony@example.com>"), Logger.new(nil))
# => "Tony =?UTF-8?B?Tm92w6Fr?="
```

I propose doing away with `@output_type` entirely. Thoughts?

**Comment by kjg** [comment]
I agree that this behaviour is confusing. I'd love to see a pull request that changes the way this works. I assume they'd hold off on merging a change like this until a major version release since it would change the API of the object, but I for one would love to see this happen.
