### ISSUE TITLE
Is it possible to read the email data from say an array of lines?

### ISSUE THREAD

**Issue by philiprhoades** [mikel/mail#964]
I already have an email as an array of text lines - is there some way of getting this information into a mail object for manipulation? It seems silly having to write the array out to a file just so I can use MAIL.read on it . .

Thanks,
Phil.

**Comment by mariokostelac** [comment]
It is.
```
Mail.new(arr.join)
```

**Comment by philiprhoades** [comment]
Wow!  Many thanks for the super fast response!
