### ISSUE TITLE
any known issues with 2.6.4.rc2?

### ISSUE THREAD

**Issue by maia** [mikel/mail#967]
As I'd like to use the gem `mime-types` in version 3.x, I'd want to upgrade mail `2.6.3` to `2.6.4.rc2` (or a release, assuming it might be available shortly). The old version is restricting `mime-types` to `< 3`.

I've looked through the open issues and none specifically referenced `2.6.4`. Is `2.6.4` ready for release, or are there issues that suggest not using it in production yet? 

Thanks!

**Comment by jeremy** [comment]
Haven't heard any issues! But also haven't heard from many trying the gem. We'll release shortly.

**Comment by maia** [comment]
@jeremy Thanks for the info!

**Comment by jeremy** [comment]
2.6.4 is released.

**Comment by maia** [comment]
thanks!
