### ISSUE TITLE
No attachments found when sent from Yahoo and filename has no extension

### ISSUE THREAD

**Issue by faelsoto** [mikel/mail#969]
There's a weird behaviour when an attachment is sent from Yahoo with no extension (the file name is `noname`), as the `attachments` method returns an empty array.

This behaviour is consistent within that email, if I download the attachment and send it through a Gmail account, the attachment is found. However, if that email is forwarded, the problem persists, so I think it might be an issue with the headers and not with the file.

How can I provide the information required to test and analyze this issue? Should I post the header information or should I send it to specific email account?

(This is partially reposted from [gmailgem](https://github.com/gmailgem/gmail/issues/218))

**Comment by jeremy** [comment]
Could you share the entire raw email in a gist?

**Comment by faelsoto** [comment]
Here's the gist: https://gist.github.com/faelsoto/524b90c1d5418066c732

**Comment by jeremy** [comment]
Confirm. The MIME part isn't recognized as an attachment because it doesn't have a filename. Check out #792 for more.

**Comment by faelsoto** [comment]
Thanks.

For the record, I monkeypatched the `find_attachment` method:

```
module Mail
  class Message
    def find_attachment
      content_type_name = header[:content_type].filename rescue nil
      content_disp_name = header[:content_disposition].filename rescue nil
      content_loc_name  = header[:content_location].location rescue nil
      case
      when content_type && content_type_name
        filename = content_type_name
      when content_disposition && content_disp_name
        filename = content_disp_name
      when content_location && content_loc_name
        filename = content_loc_name
      else
        filename = nil
      end
      filename = Mail::Encodings.decode_encode(filename, :decode) if filename rescue filename
      
      return filename if filename.present?

      if self['Content-Disposition'].to_s.split(";").first == "attachment"
        "att-#{rand(0..99999)}-#{rand(0..99999)}"
      end
    end
  end
end
```
