### ISSUE TITLE
No attachments found in email

### ISSUE THREAD

**Issue by faelsoto** [mikel/mail#971]
I have this email in which everything seems ok—the attachment file name is not empty, the message seems fine, but the gem reports no attachments. Might be the headers?

[Here's the raw message](https://gist.github.com/faelsoto/a382ba0b0c568dfa0e48)

**Comment by jeremy** [comment]
There aren't any MIME parts in this message. Looks like you have a uuencoded file included inline in the plaintext message body. That's not something the mail lib can recognize or extract.

**Comment by faelsoto** [comment]
Thank you. Didn't know it was a legacy issue.
