### ISSUE TITLE
Attachment#decoded does not keep original encoding on Ruby >= 2.1

### ISSUE THREAD

**Issue by marutosi** [mikel/mail#972]
Original reported issue:
http://www.redmine.org/issues/21742

mail (2.6.3) pinned by Rails 4.2:

Test https://github.com/redmine/redmine/commit/e28cc10a35a9390faef72689148e762ac3425ae0
Pass:
- ruby-1.9.3-p551
- ruby-2.0.0-p648

Fail:
- ruby-2.1.8
- ruby-2.2.4

https://github.com/redmine/redmine/commit/5414d86050887945780ea5e9bf2c8c6ff12faa9c fixes.

``` diff
@@ -290,7 +290,7 @@ def add_attachments(obj)
       email.attachments.each do |attachment|
         next unless accept_attachment?(attachment)
         obj.attachments << Attachment.create(:container => obj,
-                          :file => attachment.decoded,
+                          :file => attachment.body.decoded,
                           :filename => attachment.filename,
                           :author => user,
                           :content_type => attachment.mime_type)
```

**Comment by marutosi** [comment]
I tried at Gemfile, but no change.
```ruby
gem "mail", :github => "mikel/mail", :branch => "master"
```

It uses 728942f2bc3a24fc84d6653e80d842b08a8858a0 .

**Comment by jeremy** [comment]
Likely because the Part sets the body content type according to its charset, but it's omitted here:
```ruby
                           :content_type => attachment.mime_type
```
(that's just the `text/plain` mime type without the full `; charset=…` params)
