### ISSUE TITLE
Email address display_name and comments not being split properly for some email headers

### ISSUE THREAD

**Issue by daveespo** [mikel/mail#975]
I am using the mail gem (2.6.3) to index emails from the Gmail V1 API

The format of the From header in both the API response and when using the 'Show original' UI in Gmail have many emails with From headers that look like:

`From: "David Esposito (Some Comment)" <dave@someplace.com>`

(notice the quotation marks)

This causes the Mail::Address to incorrectly report the display_name as 

`David Esposito (Some Comment)`

This is the repro case:

````
irb(main):020:0> k = Mail::Address.new('"David Esposito (Some Comment)" <dave@someplace.com>') 
=> #<Mail::Address:70295609057740 Address: |"David Esposito (Some Comment)" <dave@someplace.com>| >
irb(main):021:0> k.display_name
=> "David Esposito (Some Comment)"
````

versus the same without quotation marks:

````
irb(main):022:0> k = Mail::Address.new('David Esposito (Some Comment) <dave@someplace.com>')  
=> #<Mail::Address:70295608934300 Address: |David Esposito <dave@someplace.com> (Some Comment)| >
irb(main):023:0> k.display_name
=> "David Esposito"
irb(main):024:0> k.comments
=> ["Some Comment"]
````

And here's a screen shot of a 'show original' from Gmail:

http://screencast.com/t/TJc6d77d

Is this expected behavior?

**Comment by jeremy** [comment]
This is indeed confusing, but it's correct. Gmail is including parens within the quoted display name—that's not a separate comment.
