### ISSUE TITLE
IMAP > Retrieved Mail Ordering is incorrect

### ISSUE THREAD

**Issue by gavk34** [mikel/mail#977]
Using the defaults, i.e.
emails = Mail.find(:mailbox => 'my_mailbox', :keys => ['SUBJECT','my_subject'])

The returned emails are in the following order:
To: benton@example.org
Date: 2016-03-23T09:25:59+00:00

To: darrin@example.net
Date: 2016-03-23T09:25:59+00:00

To: nannie_kris@example.net
Date: 2016-03-23T09:26:00+00:00

To: sample@example.net
Date: 2016-03-23T09:25:59+00:00

To: sample_test@example.com
Date: 2016-03-23T09:26:00+00:00

You can see that the second last email is in the wrong order, it should be in position above.

**Comment by jeremy** [comment]
That's up to your IMAP server. Check out the `:order` and `:what` options to change the sort order and such as well.
