### ISSUE TITLE
Encode the recipients in Punycode

### ISSUE THREAD

**Issue by wukerplank** [mikel/mail#985]
I'm trying to send my mails via Amazon SES. I have a bunch of recipients with valid UTF-8 addresses. Amazon SES doesn't like the the UTF-8 encoded addresses, but instead wants me to encode them in Punycode (http://docs.aws.amazon.com/ses/latest/DeveloperGuide/ses-errors.html).

I wonder what the best way forward is for me: Blindly encode all my recipients or monkey patch the mail gem. Or is there something I can hook into?

**Comment by carsonreinke** [comment]
> to or from email addresses that contain unicode characters in the domain part of an address

They are just referring to the domain part of the email address.  It sounds like you just can't provide UTF-8 domains.  The ultimate address will be encoded normally.

Maybe this gem should support automatic domain punycode, but there are gems out there that do that (e.g. https://github.com/mmriis/simpleidn)

**Comment by wukerplank** [comment]
@carsonreinke Thanks for your response! I've already tried simpleidn and it works great.

One rejected example would be `max.müster@test.com`, with an umlaut in the local part. This gets encoded as `=?UTF-8?B?bWF4Lm3DvHN0ZXJAdGVzdC5jb20=?=` and Amazon won't have it. The full Punycode version of it is `max.xn--mster@test-9db.com`, which Amazon accepts.

I'd like to try to avoid to puny-encode all of my recipients (most of them already are in ASCII7) since I don't know if their servers can handle punycode. I'm sure I'll find a way.

**Comment by jeremy** [comment]
Punycoding is an ASCII-compatible-encoding (ACE) algorithm for internationalized domain names only (IDNA). So confirmed @carsonreinke that it's for the domain part only.

For mailbox and address, we'd need to go (much) further.

https://en.wikipedia.org/wiki/Unicode_and_email has a good high level view.

**Comment by wukerplank** [comment]
Thanks @jeremy for chiming in! While RFCs are always interesting, I still have a hard time reconciling them with the example I provided above. The standards matter very little to me if I can't send mails via Amazon... Anyways, I think I'll close this. Sorry for wasting your time.

**Comment by jeremy** [comment]
SES follows the same RFCs as everyone else. Their docs indicate that 7-bit ASCII addresses are required and that punycode encoding may be used for the domain part. If punycode encoding works for other parts of the address, it may be a coincidence or an unsupported feature.

**Comment by mohammed-gharbi** [comment]
@jeremy [the documentation](https://docs.aws.amazon.com/ses/latest/dg/send-email-raw.html) now says that punycode encoding should be used in the local part, probably that changed since then?!

I am running into the same issue, is there any chance to be supported by the mail gem? instead of adding other dependencies.
