### ISSUE TITLE
QUESTION: Can you mock Pop3 emails with body text set?

### ISSUE THREAD

**Issue by jongillies** [mikel/mail#992]
I found the MockPopMail and MockPOP3 in spec_helper.rb and was wondering if you can add a specific body text to the mock emails?  I tried adding a body method to MockPopEmail, but no luck when I'm reading emails.

**Comment by jeremy** [comment]
What would be calling the `#body` method you added?

What's calling which methods when you read emails?

Which method needs to be mocked in order to read a body you provide? (… What is `#rfc2822`?)

Step through with a debugger to discern where and how to mock this out 😁
