### ISSUE TITLE
How do I use Mail::TestMailer effectively?

### ISSUE THREAD

**Issue by Vanders** [mikel/mail#993]
I have a method that uses Mail to send the final email via. SMTP: https://github.com/Liqwyd/Cyclid/blob/vanders/notifiers/lib/cyclid/plugins/action/email.rb#L40

How would I effectively test this method with RSpec? If I set Mail.defaults to use the :test transport it just gets reset as soon as the method calls mail.delivery_method to set up its own SMTP connection details (and my test ends up sending an email: luckily only to myself!). I can't see any way to use TestMailer here without introducing test logic into the method I.e. check if delivery_method is set to :test before it sets up the SMTP connection details, but obviously that would be bad.

**Comment by jeremy** [comment]
Hi @Vanders. This is a classic code design question that'll lead you to refactor your implementation so your `#perform` method doesn't do SMTP connection config or setup itself. It may help to imagine wanting to instantiate the plugin with some configuration that sets up sendmail delivery instead of SMTP, for example. Then, for tests, you'd configure your plugin with test delivery instead of SMTP or sendmail.

**Comment by Vanders** [comment]
Hang on, that isn't an answer. That plugin is *specifically* designed to do SMTP delivery and SMTP delivery only, and I absolutely do not want to leak the abstraction of the Mail Gem out to users who are configuring that plugin to deliver email.

More to the point, if the SMTP setup doesn't happen in the plugin, it still has to happen *somewhere*. That SMTP plugin is part of a service which provides a REST API: the Email plugin runs as part of a background process. Where should I move the Mail setup too, precisely? Have the user's client create the Mail object and then serialize it across HTTP to the server?

**Comment by Vanders** [comment]
For anyone looking for a solution to this problem themselves in future, the following worked for me:
```
context 'sending an email' do
  it 'sends an email' do
    allow_any_instance_of(Mail::Message).to receive(:deliver).and_return(true)
    # Your tests...
  end
end
```
I.e. just use RSpec mocks to stub out Mail::Message#deliver. You don't have access to any of the TestMailer functionality but it stops the test email being sent, which is fine for my case.
